// packages/react/src/dropdown-menu/DropdownMenu.tsx
/**
 * DropdownMenu — accessible action menu following the WAI-ARIA menu-button
 * pattern.
 *
 * Portal-mounted with auto-flip placement. Click the trigger to open; navigate
 * with Arrow keys, activate with Enter/Space, close with Escape or outside
 * click.
 */
import type React from "react";
import {
  cloneElement,
  isValidElement,
  useCallback,
  useEffect,
  useId,
  useMemo,
  useRef,
  useState,
  type ReactElement,
} from "react";
import { Portal } from "@sisyphos-ui/portal";
import { cx, computePosition, useEscapeKey, type Placement } from "@sisyphos-ui/core/internal";
import type { DropdownMenuItem, DropdownMenuAction } from "./types";
import "./DropdownMenu.scss";

export interface DropdownMenuProps {
  items: DropdownMenuItem[];
  placement?: Placement;
  offset?: number;
  open?: boolean;
  defaultOpen?: boolean;
  onOpenChange?: (open: boolean) => void;
  disabled?: boolean;
  className?: string;
  /** Header slot rendered above items (for "Notifications · 3" style labels). */
  header?: React.ReactNode;
  /** Footer slot rendered below items (for "View all" links). */
  footer?: React.ReactNode;
  /** Rendered when `items` is empty. */
  emptyState?: React.ReactNode;
  /**
   * Fires when the menu content scrolls within `scrollEndThreshold` px of the
   * bottom. Use to load more items for infinite notification/alert lists.
   */
  onScrollEnd?: () => void;
  /** Pixel distance from bottom that triggers `onScrollEnd`. Default 48. */
  scrollEndThreshold?: number;
  /** Cap the menu height so long item lists become scrollable. */
  maxHeight?: number | string;
  /** Single focusable element — the trigger. */
  children: ReactElement;
}

function isAction(item: DropdownMenuItem): item is DropdownMenuAction {
  return item.type === undefined || item.type === "action";
}

export const DropdownMenu: React.FC<DropdownMenuProps> = ({
  items,
  placement = "bottom-start",
  offset = 4,
  open: openProp,
  defaultOpen = false,
  onOpenChange,
  disabled = false,
  className,
  header,
  footer,
  emptyState,
  onScrollEnd,
  scrollEndThreshold = 48,
  maxHeight,
  children,
}) => {
  const reactId = useId();
  const menuId = `sisyphos-menu-${reactId}`;

  const anchorRef = useRef<HTMLElement | null>(null);
  const menuRef = useRef<HTMLUListElement | null>(null);
  const containerRef = useRef<HTMLDivElement | null>(null);
  const itemRefs = useRef<Array<HTMLLIElement | null>>([]);

  const isControlled = openProp !== undefined;
  const [internalOpen, setInternalOpen] = useState(defaultOpen);
  const open = (isControlled ? openProp : internalOpen) && !disabled;

  const [pos, setPos] = useState<{ left: number; top: number; placement: Placement } | null>(null);
  const [activeIndex, setActiveIndex] = useState(-1);

  const setOpen = useCallback(
    (next: boolean) => {
      if (!isControlled) setInternalOpen(next);
      onOpenChange?.(next);
    },
    [isControlled, onOpenChange]
  );

  const actionIndexes = useMemo(
    () => items.map((item, i) => (isAction(item) && !item.disabled ? i : -1)).filter((i) => i >= 0),
    [items]
  );

  const firstFocusable = actionIndexes[0] ?? -1;
  const lastFocusable = actionIndexes[actionIndexes.length - 1] ?? -1;

  const moveFocus = useCallback(
    (direction: 1 | -1) => {
      setActiveIndex((current) => {
        const pool = actionIndexes;
        if (pool.length === 0) return -1;
        if (current === -1) return direction === 1 ? pool[0] : pool[pool.length - 1];
        const idx = pool.indexOf(current);
        if (idx === -1) return pool[0];
        const next = pool[(idx + direction + pool.length) % pool.length];
        return next;
      });
    },
    [actionIndexes]
  );

  useEscapeKey(() => {
    setOpen(false);
    (anchorRef.current as HTMLElement | null)?.focus?.();
  }, open);

  useEffect(() => {
    if (!open) return;
    const handler = (e: MouseEvent) => {
      const tgt = e.target as Node | null;
      if (!tgt) return;
      if (anchorRef.current?.contains(tgt)) return;
      if (containerRef.current?.contains(tgt)) return;
      if (menuRef.current?.contains(tgt)) return;
      setOpen(false);
    };
    document.addEventListener("mousedown", handler);
    return () => document.removeEventListener("mousedown", handler);
  }, [open, setOpen]);

  useEffect(() => {
    if (!open) {
      setPos(null);
      setActiveIndex(firstFocusable);
      return;
    }
    let raf = 0;
    const update = () => {
      const anchor = anchorRef.current;
      const box = containerRef.current ?? menuRef.current;
      if (!anchor || !box) return;
      const a = anchor.getBoundingClientRect();
      const size = { width: box.offsetWidth, height: box.offsetHeight };
      const p = computePosition(a, size, placement, offset);
      setPos(p);
    };
    raf = requestAnimationFrame(() => requestAnimationFrame(update));
    const onWin = () => update();
    window.addEventListener("scroll", onWin, true);
    window.addEventListener("resize", onWin);
    setActiveIndex(firstFocusable);
    return () => {
      cancelAnimationFrame(raf);
      window.removeEventListener("scroll", onWin, true);
      window.removeEventListener("resize", onWin);
    };
  }, [open, placement, offset, firstFocusable]);

  useEffect(() => {
    if (!open) return;
    const el = itemRefs.current[activeIndex];
    el?.focus?.();
  }, [activeIndex, open]);

  const handleSelect = useCallback(
    (item: DropdownMenuAction, event: React.SyntheticEvent) => {
      if (item.disabled) return;
      item.onSelect(event);
      if (item.closeOnSelect !== false) {
        setOpen(false);
        anchorRef.current?.focus?.();
      }
    },
    [setOpen]
  );

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === "ArrowDown") {
      e.preventDefault();
      moveFocus(1);
    } else if (e.key === "ArrowUp") {
      e.preventDefault();
      moveFocus(-1);
    } else if (e.key === "Home") {
      e.preventDefault();
      setActiveIndex(firstFocusable);
    } else if (e.key === "End") {
      e.preventDefault();
      setActiveIndex(lastFocusable);
    } else if ((e.key === "Enter" || e.key === " ") && activeIndex >= 0) {
      e.preventDefault();
      const item = items[activeIndex];
      if (item && isAction(item)) handleSelect(item, e);
    } else if (e.key === "Tab") {
      setOpen(false);
    }
  };

  if (!isValidElement(children)) {
    throw new Error("[@sisyphos-ui/dropdown-menu] Expected a single React element as child.");
  }

  const childProps = children.props as Record<string, unknown>;

  const triggerEl = cloneElement(children as ReactElement<Record<string, unknown>>, {
    ref: (node: HTMLElement) => {
      anchorRef.current = node;
      const orig = (children as unknown as { ref?: React.Ref<HTMLElement> }).ref;
      if (typeof orig === "function") orig(node);
      else if (orig && typeof orig === "object") {
        (orig as React.MutableRefObject<HTMLElement | null>).current = node;
      }
    },
    "aria-haspopup": "menu",
    "aria-expanded": open || undefined,
    "aria-controls": open ? menuId : undefined,
    onClick: (e: React.MouseEvent) => {
      (childProps.onClick as ((e: React.MouseEvent) => void) | undefined)?.(e);
      setOpen(!open);
    },
    onKeyDown: (e: React.KeyboardEvent) => {
      (childProps.onKeyDown as ((e: React.KeyboardEvent) => void) | undefined)?.(e);
      if (!open) {
        if (e.key === "ArrowDown" || e.key === "Enter" || e.key === " ") {
          e.preventDefault();
          setOpen(true);
        }
        return;
      }
      // While open the trigger keeps focus, so delegate menu navigation here.
      handleKeyDown(e);
    },
  });

  const handleScroll = useCallback(
    (e: React.UIEvent<HTMLDivElement>) => {
      if (!onScrollEnd) return;
      const el = e.currentTarget;
      const distance = el.scrollHeight - el.scrollTop - el.clientHeight;
      if (distance <= scrollEndThreshold) onScrollEnd();
    },
    [onScrollEnd, scrollEndThreshold]
  );

  const renderItems = () =>
    items.length === 0 && emptyState ? (
      <div className="sisyphos-dropdown-menu-empty" role="note">
        {emptyState}
      </div>
    ) : (
      <ul
        ref={menuRef}
        id={menuId}
        role="menu"
        className="sisyphos-dropdown-menu-list"
        onKeyDown={handleKeyDown}
      >
        {items.map((item, i) => {
          if (item.type === "separator") {
            return (
              <li
                key={item.key ?? `sep-${i}`}
                className="sisyphos-dropdown-menu-separator"
                role="separator"
              />
            );
          }
          if (item.type === "label") {
            return (
              <li
                key={item.key ?? `label-${i}`}
                className="sisyphos-dropdown-menu-label"
                role="presentation"
              >
                {item.label}
              </li>
            );
          }
          const action = item;
          return (
            <li
              ref={(el) => {
                itemRefs.current[i] = el;
              }}
              key={action.key ?? `item-${i}`}
              role="menuitem"
              tabIndex={activeIndex === i ? 0 : -1}
              aria-disabled={action.disabled || undefined}
              className={cx(
                "sisyphos-dropdown-menu-item",
                action.destructive && "destructive",
                action.disabled && "disabled"
              )}
              onMouseEnter={() => setActiveIndex(i)}
              onClick={(e) => handleSelect(action, e)}
            >
              {action.icon && (
                <span className="sisyphos-dropdown-menu-item-icon">{action.icon}</span>
              )}
              <span className="sisyphos-dropdown-menu-item-label">{action.label}</span>
              {action.shortcut && (
                <span className="sisyphos-dropdown-menu-item-shortcut">{action.shortcut}</span>
              )}
            </li>
          );
        })}
      </ul>
    );

  return (
    <>
      {triggerEl}
      {open && (
        <Portal>
          <div
            ref={containerRef}
            className={cx(
              "sisyphos-dropdown-menu",
              pos?.placement ?? placement,
              (header || footer) && "rich",
              className
            )}
            style={{
              position: "fixed",
              left: pos?.left ?? 0,
              top: pos?.top ?? 0,
              opacity: pos ? 1 : 0,
              maxHeight,
            }}
            onScroll={handleScroll}
          >
            {header && <div className="sisyphos-dropdown-menu-header">{header}</div>}
            {renderItems()}
            {footer && <div className="sisyphos-dropdown-menu-footer">{footer}</div>}
          </div>
        </Portal>
      )}
    </>
  );
};

// packages/vue/src/dropdown-menu/DropdownMenu.vue
<script setup lang="ts">
/**
 * DropdownMenu — Vue 3 binding. Click trigger + portal-mounted menu list
 * with keyboard navigation, escape, and outside-click close.
 */
import { computePosition, type Placement } from "@sisyphos-ui/core/internal";
import { computed, nextTick, onBeforeUnmount, ref, useId, watch } from "vue";
import { useEscapeKey, useOutsideClick } from "../composables";
import type { DropdownMenuAction, DropdownMenuItem } from "./types";

interface Props {
  items: DropdownMenuItem[];
  placement?: Placement;
  offset?: number;
  open?: boolean;
  defaultOpen?: boolean;
  /** Called when scrolling reaches the end (within `scrollEndThreshold` px). */
  scrollEndThreshold?: number;
  maxHeight?: number | string;
  emptyState?: string;
  disabled?: boolean;
}

const props = withDefaults(defineProps<Props>(), {
  placement: "bottom-start",
  offset: 6,
  defaultOpen: false,
  scrollEndThreshold: 24,
});

const emit = defineEmits<{
  (e: "update:open", value: boolean): void;
  (e: "scrollEnd"): void;
}>();

const menuId = `sisyphos-dropdown-menu-${useId()}`;
const anchorWrapperRef = ref<HTMLElement | null>(null);
const menuRef = ref<HTMLDivElement | null>(null);

const internalOpen = ref(props.defaultOpen);
const isControlled = computed(() => props.open !== undefined);
const isOpen = computed(() => (isControlled.value ? props.open! : internalOpen.value));
const visible = computed(() => isOpen.value && !props.disabled);

const pos = ref<{ left: number; top: number; placement: Placement } | null>(null);
const activeIndex = ref(-1);

const actionItems = computed(() =>
  props.items
    .map((item, idx) => ({ item, idx }))
    .filter(({ item }) => (item.type ?? "action") === "action") as { item: DropdownMenuAction; idx: number }[]
);

function setOpen(next: boolean) {
  if (!isControlled.value) internalOpen.value = next;
  emit("update:open", next);
  if (next) {
    activeIndex.value = -1;
  }
}

useEscapeKey(() => setOpen(false), visible);
useOutsideClick([anchorWrapperRef, menuRef], () => setOpen(false), visible);

async function updatePosition() {
  if (!visible.value) return;
  await nextTick();
  const anchor = anchorWrapperRef.value?.firstElementChild as HTMLElement | null;
  const menu = menuRef.value;
  if (!anchor || !menu) return;
  const rect = anchor.getBoundingClientRect();
  pos.value = computePosition(
    rect,
    { width: menu.offsetWidth, height: menu.offsetHeight },
    props.placement,
    props.offset
  );
}

watch(visible, (v) => {
  if (v) updatePosition();
  else pos.value = null;
});

function onAnchorClick() {
  if (props.disabled) return;
  setOpen(!isOpen.value);
}

function selectAction(item: DropdownMenuAction, e: Event) {
  if (item.disabled) return;
  item.onSelect(e);
  if (item.closeOnSelect !== false) setOpen(false);
}

function handleKeyDown(e: KeyboardEvent) {
  if (!visible.value) return;
  const all = actionItems.value;
  if (all.length === 0) return;
  if (e.key === "ArrowDown") {
    e.preventDefault();
    activeIndex.value = (activeIndex.value + 1) % all.length;
  } else if (e.key === "ArrowUp") {
    e.preventDefault();
    activeIndex.value = (activeIndex.value - 1 + all.length) % all.length;
  } else if (e.key === "Home") {
    e.preventDefault();
    activeIndex.value = 0;
  } else if (e.key === "End") {
    e.preventDefault();
    activeIndex.value = all.length - 1;
  } else if (e.key === "Enter" || e.key === " ") {
    if (activeIndex.value >= 0) {
      e.preventDefault();
      selectAction(all[activeIndex.value].item, e);
    }
  }
}

function onScroll(e: Event) {
  const el = e.target as HTMLElement;
  if (el.scrollTop + el.clientHeight >= el.scrollHeight - props.scrollEndThreshold) {
    emit("scrollEnd");
  }
}

const menuStyle = computed(() => ({
  position: "fixed" as const,
  left: `${pos.value?.left ?? 0}px`,
  top: `${pos.value?.top ?? 0}px`,
  opacity: pos.value ? 1 : 0,
  maxHeight: typeof props.maxHeight === "number" ? `${props.maxHeight}px` : props.maxHeight,
}));

const menuClasses = computed(() => ["sisyphos-dropdown-menu", pos.value?.placement ?? props.placement]);

if (typeof window !== "undefined") {
  const onWindowChange = () => visible.value && updatePosition();
  window.addEventListener("scroll", onWindowChange, true);
  window.addEventListener("resize", onWindowChange);
  onBeforeUnmount(() => {
    window.removeEventListener("scroll", onWindowChange, true);
    window.removeEventListener("resize", onWindowChange);
  });
}
</script>

<template>
  <span
    ref="anchorWrapperRef"
    class="sisyphos-dropdown-anchor"
    aria-haspopup="menu"
    :aria-expanded="isOpen || undefined"
    :aria-controls="visible ? menuId : undefined"
    @click="onAnchorClick"
    @keydown="handleKeyDown"
  >
    <slot />
  </span>
  <Teleport to="body">
    <div
      v-if="visible"
      ref="menuRef"
      :id="menuId"
      role="menu"
      :class="menuClasses"
      :style="menuStyle"
      @scroll="onScroll"
      @keydown="handleKeyDown"
    >
      <div v-if="$slots.header" class="sisyphos-dropdown-menu-header">
        <slot name="header" />
      </div>
      <template v-if="items.length === 0 && emptyState">
        <div class="sisyphos-dropdown-menu-empty" role="note">{{ emptyState }}</div>
      </template>
      <ul v-else class="sisyphos-dropdown-menu-list">
        <template v-for="(item, idx) in items" :key="item.key ?? idx">
          <li v-if="item.type === 'separator'" class="sisyphos-dropdown-menu-separator" role="separator" />
          <li v-else-if="item.type === 'label'" class="sisyphos-dropdown-menu-label" role="presentation">
            {{ item.label }}
          </li>
          <li v-else role="none">
            <button
              type="button"
              role="menuitem"
              :class="[
                'sisyphos-dropdown-menu-item',
                item.disabled && 'disabled',
                item.destructive && 'destructive',
                actionItems.findIndex((a) => a.idx === idx) === activeIndex && 'active',
              ]"
              :disabled="item.disabled"
              @click="selectAction(item, $event)"
            >
              <span v-if="item.icon" class="sisyphos-dropdown-menu-item-icon"><slot name="icon" :item="item" /></span>
              <span class="sisyphos-dropdown-menu-item-label">{{ item.label }}</span>
              <span v-if="item.shortcut" class="sisyphos-dropdown-menu-item-shortcut">{{ item.shortcut }}</span>
            </button>
          </li>
        </template>
      </ul>
      <div v-if="$slots.footer" class="sisyphos-dropdown-menu-footer">
        <slot name="footer" />
      </div>
    </div>
  </Teleport>
</template>

<style src="./DropdownMenu.scss"></style>
