// packages/empty-state/src/EmptyState.tsx
/**
 * EmptyState — placeholder for zero-data views with slots for icon, title,
 * description, and call-to-action buttons.
 */
import React from "react";
import { cx } from "@sisyphos-ui/core/internal";
import "./EmptyState.scss";

export interface EmptyStateProps extends Omit<React.HTMLAttributes<HTMLDivElement>, "title"> {
  icon?: React.ReactNode;
  title?: React.ReactNode;
  description?: React.ReactNode;
  /** Action buttons slot — typically one or two `<Button>` elements. */
  actions?: React.ReactNode;
  /** Size/density scale. */
  size?: "sm" | "md" | "lg";
  /** Dashed border + subtle background. Defaults to `false` (bare). */
  bordered?: boolean;
  /**
   * Layout mode.
   *   `block`  — vertical full-bleed (default) — icon above title + description.
   *   `inline` — compact horizontal row — icon next to text; fits inside modals, cards, filter rows.
   */
  variant?: "block" | "inline";
}

export const EmptyState = React.forwardRef<HTMLDivElement, EmptyStateProps>(function EmptyState(
  {
    icon,
    title,
    description,
    actions,
    size = "md",
    bordered = false,
    variant = "block",
    className,
    children,
    ...rest
  },
  ref
) {
  return (
    <div
      ref={ref}
      role="status"
      className={cx("sisyphos-empty-state", size, variant, bordered && "bordered", className)}
      {...rest}
    >
      {icon && (
        <div className="sisyphos-empty-state-icon" aria-hidden="true">
          {icon}
        </div>
      )}
      {title && <h3 className="sisyphos-empty-state-title">{title}</h3>}
      {description && <p className="sisyphos-empty-state-description">{description}</p>}
      {children}
      {actions && <div className="sisyphos-empty-state-actions">{actions}</div>}
    </div>
  );
});

EmptyState.displayName = "EmptyState";

// packages/vue/src/empty-state/EmptyState.vue
<script setup lang="ts">
/**
 * EmptyState — Vue 3 binding. Slots for icon / title / description /
 * actions plus three layout dimensions (size, variant, bordered).
 */
import { computed } from "vue";

interface Props {
  /** Title rendered as a heading. Use the `title` slot for richer markup. */
  title?: string;
  /** Description rendered as a paragraph. Use the `description` slot for richer markup. */
  description?: string;
  size?: "sm" | "md" | "lg";
  /** Dashed border + subtle background. Defaults to `false`. */
  bordered?: boolean;
  /** Layout mode. `block` (default) is vertical, `inline` is a compact row. */
  variant?: "block" | "inline";
}

const props = withDefaults(defineProps<Props>(), {
  size: "md",
  bordered: false,
  variant: "block",
});

const rootClasses = computed(() => [
  "sisyphos-empty-state",
  props.size,
  props.variant,
  props.bordered && "bordered",
]);
</script>

<template>
  <div role="status" :class="rootClasses">
    <div v-if="$slots.icon" class="sisyphos-empty-state-icon" aria-hidden="true">
      <slot name="icon" />
    </div>
    <h3 v-if="title || $slots.title" class="sisyphos-empty-state-title">
      <slot name="title">{{ title }}</slot>
    </h3>
    <p v-if="description || $slots.description" class="sisyphos-empty-state-description">
      <slot name="description">{{ description }}</slot>
    </p>
    <slot />
    <div v-if="$slots.actions" class="sisyphos-empty-state-actions">
      <slot name="actions" />
    </div>
  </div>
</template>

<style src="./EmptyState.scss"></style>
