// packages/angular/src/breadcrumb/breadcrumb.component.ts
/**
 * Breadcrumb — Angular 18 standalone navigation trail.
 *
 * Mirrors the React/Vue versions: takes an `items` array, marks the last
 * entry as the current page (`aria-current="page"`), supports middle
 * collapse via `maxItems` + `itemsBeforeCollapse` + `itemsAfterCollapse`,
 * and lets consumers swap the separator.
 *
 * Icons accept either a string (rendered as text — emoji/Unicode glyphs)
 * or a `TemplateRef<unknown>` for rich SVG/component content. Same idea
 * as a `ReactNode` slot, expressed in Angular's idiom.
 *
 * Usage:
 *   items = [
 *     { label: 'Home', href: '/', icon: '🏠' },
 *     { label: 'Users', href: '/users' },
 *     { label: 'Volkan' },          // the last item — rendered as current page
 *   ];
 *   <sui-breadcrumb [items]="items" />
 */
import type {
  TemplateRef} from "@angular/core";
import {
  ChangeDetectionStrategy,
  Component,
  EventEmitter,
  Input,
  Output,
  computed,
  signal,
} from "@angular/core";
import { NgTemplateOutlet } from "@angular/common";

export interface BreadcrumbItem {
  label: string;
  href?: string;
  /** Mutually exclusive with `href`; renders the entry as a `<button>`. */
  onClick?: () => void;
  /** Inline glyph (string) or rich `<ng-template>` icon. */
  icon?: string | TemplateRef<unknown>;
  /** Stable identifier for `track` in @for. Falls back to index. */
  key?: string | number;
}

type RenderedNode = ({ kind: "item"; item: BreadcrumbItem } | { kind: "ellipsis" }) & {
  trackKey: string;
};

@Component({
  selector: "sui-breadcrumb",
  standalone: true,
  imports: [NgTemplateOutlet],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <nav class="sisyphos-breadcrumb" aria-label="breadcrumb">
      <ol class="sisyphos-breadcrumb-list">
        @for (node of rendered(); track node.trackKey; let idx = $index, isLast = $last) {
          @if (node.kind === 'ellipsis') {
            <li class="sisyphos-breadcrumb-ellipsis" aria-hidden="true">…</li>
          } @else {
            <li class="sisyphos-breadcrumb-item">
              @if (isLast) {
                <span class="sisyphos-breadcrumb-current" aria-current="page">
                  <ng-container *ngTemplateOutlet="iconTpl; context: { $implicit: node.item }" />
                  <span>{{ node.item.label }}</span>
                </span>
              } @else if (node.item.href) {
                <a
                  class="sisyphos-breadcrumb-link"
                  [attr.href]="node.item.href"
                  (click)="handleClick(node.item, $event)"
                >
                  <ng-container *ngTemplateOutlet="iconTpl; context: { $implicit: node.item }" />
                  <span>{{ node.item.label }}</span>
                </a>
              } @else if (node.item.onClick) {
                <button
                  type="button"
                  class="sisyphos-breadcrumb-link as-button"
                  (click)="handleClick(node.item, $event)"
                >
                  <ng-container *ngTemplateOutlet="iconTpl; context: { $implicit: node.item }" />
                  <span>{{ node.item.label }}</span>
                </button>
              } @else {
                <span class="sisyphos-breadcrumb-text">
                  <ng-container *ngTemplateOutlet="iconTpl; context: { $implicit: node.item }" />
                  <span>{{ node.item.label }}</span>
                </span>
              }
            </li>
          }
          @if (!isLast) {
            <li class="sisyphos-breadcrumb-separator" aria-hidden="true">
              @if (separatorTemplate()) {
                <ng-container *ngTemplateOutlet="separatorTemplate()!" />
              } @else {
                {{ separator() }}
              }
            </li>
          }
        }
      </ol>
    </nav>

    <ng-template #iconTpl let-item>
      @if (item.icon) {
        @if (isStringIcon(item.icon)) {
          <span class="sisyphos-breadcrumb-icon">{{ item.icon }}</span>
        } @else {
          <span class="sisyphos-breadcrumb-icon">
            <ng-container *ngTemplateOutlet="item.icon" />
          </span>
        }
      }
    </ng-template>
  `,
})
export class Breadcrumb {
  private readonly _items = signal<BreadcrumbItem[]>([]);
  private readonly _separator = signal<string>("/");
  private readonly _separatorTemplate = signal<TemplateRef<unknown> | undefined>(undefined);
  private readonly _maxItems = signal<number | undefined>(undefined);
  private readonly _itemsBefore = signal<number>(1);
  private readonly _itemsAfter = signal<number>(1);

  readonly separator = this._separator.asReadonly();
  readonly separatorTemplate = this._separatorTemplate.asReadonly();

  @Input("items") set itemsInput(v: BreadcrumbItem[]) { this._items.set(v ?? []); }
  @Input("separator") set separatorInput(v: string) { this._separator.set(v); }
  @Input("separatorTemplate") set separatorTemplateInput(v: TemplateRef<unknown> | undefined) {
    this._separatorTemplate.set(v);
  }
  @Input("maxItems") set maxItemsInput(v: number | undefined) { this._maxItems.set(v); }
  @Input("itemsBeforeCollapse") set itemsBeforeInput(v: number) { this._itemsBefore.set(v); }
  @Input("itemsAfterCollapse") set itemsAfterInput(v: number) { this._itemsAfter.set(v); }

  /** Emitted when an item with `onClick` is activated. Useful when consumers
   * prefer a single output handler over per-item callbacks. */
  @Output() readonly itemClick = new EventEmitter<BreadcrumbItem>();

  readonly rendered = computed<RenderedNode[]>(() => {
    const items = this._items();
    const max = this._maxItems();
    const before = this._itemsBefore();
    const after = this._itemsAfter();

    const collapsed =
      typeof max === "number" && items.length > max
        ? [
            ...items.slice(0, before).map((item, i) => ({ kind: "item" as const, item, trackKey: keyFor(item, i) })),
            { kind: "ellipsis" as const, trackKey: "__ellipsis__" },
            ...items.slice(items.length - after).map((item, i) => ({
              kind: "item" as const,
              item,
              trackKey: keyFor(item, items.length - after + i),
            })),
          ]
        : items.map((item, i) => ({ kind: "item" as const, item, trackKey: keyFor(item, i) }));

    return collapsed;
  });

  isStringIcon(icon: unknown): icon is string {
    return typeof icon === "string";
  }

  handleClick(item: BreadcrumbItem, event: Event): void {
    if (item.onClick) {
      // Prevent navigation when consumers handle clicks themselves.
      if (item.href) event.preventDefault();
      item.onClick();
    }
    this.itemClick.emit(item);
  }
}

function keyFor(item: BreadcrumbItem, idx: number): string {
  return item.key !== undefined ? String(item.key) : `idx-${idx}`;
}

// packages/breadcrumb/src/Breadcrumb.tsx
/**
 * Breadcrumb — navigation trail with optional middle-collapse (via `maxItems`)
 * and a customizable separator.
 *
 * Rendered inside a `<nav aria-label="breadcrumb">` and marks the final item
 * with `aria-current="page"`.
 */
import React from "react";
import { cx } from "@sisyphos-ui/core/internal";
import "./Breadcrumb.scss";

export interface BreadcrumbItem {
  label: React.ReactNode;
  href?: string;
  onClick?: (event: React.MouseEvent) => void;
  icon?: React.ReactNode;
  key?: string;
}

export interface BreadcrumbProps extends React.HTMLAttributes<HTMLElement> {
  /** Ordered list of breadcrumb entries. The last item is treated as the current page. */
  items: BreadcrumbItem[];
  /** Custom separator rendered between items. Defaults to "/". */
  separator?: React.ReactNode;
  /**
   * When set, collapses middle items into a `…` when total exceeds this count.
   * Keeps `itemsBeforeCollapse` before and `itemsAfterCollapse` after the ellipsis.
   */
  maxItems?: number;
  /** Items kept before the ellipsis when collapsing. */
  itemsBeforeCollapse?: number;
  /** Items kept after the ellipsis when collapsing. */
  itemsAfterCollapse?: number;
}

const DefaultSeparator = () => <span aria-hidden="true">/</span>;

function collapseItems(
  items: BreadcrumbItem[],
  max: number,
  before: number,
  after: number
): Array<BreadcrumbItem | { ellipsis: true }> {
  if (items.length <= max) return items;
  return [...items.slice(0, before), { ellipsis: true }, ...items.slice(items.length - after)];
}

export const Breadcrumb = React.forwardRef<HTMLElement, BreadcrumbProps>(function Breadcrumb(
  {
    items,
    separator = <DefaultSeparator />,
    maxItems,
    itemsBeforeCollapse = 1,
    itemsAfterCollapse = 1,
    className,
    ...rest
  },
  ref
) {
  const rendered =
    typeof maxItems === "number"
      ? collapseItems(items, maxItems, itemsBeforeCollapse, itemsAfterCollapse)
      : items;

  return (
    <nav
      ref={ref}
      aria-label="breadcrumb"
      className={cx("sisyphos-breadcrumb", className)}
      {...rest}
    >
      <ol className="sisyphos-breadcrumb-list">
        {rendered.map((node, idx) => {
          const isLast = idx === rendered.length - 1;
          const sep = !isLast && (
            <li aria-hidden="true" className="sisyphos-breadcrumb-separator">
              {separator}
            </li>
          );

          if ("ellipsis" in node) {
            return (
              <React.Fragment key={`ellipsis-${idx}`}>
                <li className="sisyphos-breadcrumb-ellipsis" aria-hidden="true">
                  …
                </li>
                {sep}
              </React.Fragment>
            );
          }

          const item = node;
          const content = (
            <>
              {item.icon && <span className="sisyphos-breadcrumb-icon">{item.icon}</span>}
              <span>{item.label}</span>
            </>
          );

          let body: React.ReactNode;
          if (isLast) {
            body = (
              <span className="sisyphos-breadcrumb-current" aria-current="page">
                {content}
              </span>
            );
          } else if (item.href) {
            body = (
              <a className="sisyphos-breadcrumb-link" href={item.href} onClick={item.onClick}>
                {content}
              </a>
            );
          } else if (item.onClick) {
            body = (
              <button
                type="button"
                className="sisyphos-breadcrumb-link as-button"
                onClick={item.onClick}
              >
                {content}
              </button>
            );
          } else {
            body = <span className="sisyphos-breadcrumb-text">{content}</span>;
          }

          return (
            <React.Fragment key={item.key ?? idx}>
              <li className="sisyphos-breadcrumb-item">{body}</li>
              {sep}
            </React.Fragment>
          );
        })}
      </ol>
    </nav>
  );
});

Breadcrumb.displayName = "Breadcrumb";
