// packages/kbd/src/Kbd.tsx
/**
 * Kbd — renders a keyboard key or a shortcut combination.
 *
 * Three input modes (pick one):
 * - `children` — free-form content, rendered inside a single `<kbd>`.
 * - `keys` — array of keys; each gets its own `<kbd>` with a separator between.
 * - `shortcut` — string like "cmd+k" or "ctrl shift p"; parsed into keys.
 *
 * Platform-aware: `mod` resolves to ⌘ on macOS and Ctrl elsewhere. `cmd`, `ctrl`,
 * `alt`, `shift`, arrow keys, etc. are normalized to glyphs via KEY_GLYPHS.
 */
import React, { useMemo } from "react";
import { cx } from "@sisyphos-ui/core/internal";
import "./Kbd.scss";
import { CN, DEFAULTS, KEY_GLYPHS, type Scale } from "./constants";

export interface KbdProps extends Omit<React.HTMLAttributes<HTMLElement>, "children"> {
  /** Visual style. `outlined` has a border, `soft` uses a muted background. */
  variant?: "outlined" | "soft";
  size?: Scale;
  /** Free-form content. Mutually exclusive with `keys` and `shortcut`. */
  children?: React.ReactNode;
  /** Explicit list of keys. Aliases (cmd/ctrl/shift/...) are normalized to glyphs. */
  keys?: string[];
  /** Shortcut string parsed on `+` or whitespace. e.g. "cmd+k", "ctrl shift p". */
  shortcut?: string;
  /** String or node rendered between keys when multiple. Defaults to none (visually joined). */
  separator?: React.ReactNode;
}

function isMac(): boolean {
  if (typeof navigator === "undefined") return false;
  const p = navigator.platform || "";
  return /Mac|iPhone|iPad|iPod/.test(p);
}

function normalizeKey(raw: string, mac: boolean): string {
  const trimmed = raw.trim();
  if (!trimmed) return "";
  const lower = trimmed.toLowerCase();
  if (lower === "mod") return mac ? KEY_GLYPHS.cmd : KEY_GLYPHS.ctrl;
  if (KEY_GLYPHS[lower]) return KEY_GLYPHS[lower];
  // Single letters uppercase for display; multi-char tokens left as-is (e.g. F1, Home).
  return trimmed.length === 1 ? trimmed.toUpperCase() : trimmed;
}

function parseShortcut(s: string): string[] {
  return s.split(/[\s+]+/).filter(Boolean);
}

export const Kbd = React.forwardRef<HTMLElement, KbdProps>(function Kbd(
  {
    children,
    className,
    variant = DEFAULTS.variant,
    size = DEFAULTS.size,
    keys,
    shortcut,
    separator,
    ...rest
  },
  ref
) {
  const resolvedKeys = useMemo<string[]>(() => {
    if (keys?.length) return keys;
    if (shortcut) return parseShortcut(shortcut);
    return [];
  }, [keys, shortcut]);

  const mac = useMemo(() => isMac(), []);

  const rootClass = cx(CN.root, variant, CN.size(size), className);

  // Single key / free-form: one <kbd>.
  if (resolvedKeys.length === 0) {
    return (
      <kbd ref={ref} className={rootClass} {...rest}>
        {children}
      </kbd>
    );
  }

  // Multi-key: group with role="group"; each key is its own <kbd>.
  return (
    <span
      ref={ref as React.Ref<HTMLSpanElement>}
      className={rootClass}
      role="group"
      {...rest}
    >
      {resolvedKeys.map((raw, i) => {
        const glyph = normalizeKey(raw, mac);
        return (
          <React.Fragment key={`${raw}-${i}`}>
            {i > 0 && separator != null && (
              <span className={CN.separator} aria-hidden="true">
                {separator}
              </span>
            )}
            <kbd className={CN.key}>{glyph}</kbd>
          </React.Fragment>
        );
      })}
    </span>
  );
});

Kbd.displayName = "Kbd";

// packages/vue/src/kbd/Kbd.vue
<script setup lang="ts">
/**
 * Kbd — Vue 3 binding. Three input modes (default slot, `keys` array,
 * or `shortcut` string), platform-aware `mod` resolution.
 */
import { computed } from "vue";

interface Props {
  variant?: "outlined" | "soft";
  size?: "xs" | "sm" | "md" | "lg" | "xl";
  /** Explicit list of keys. Aliases (cmd/ctrl/shift/...) are normalized to glyphs. */
  keys?: string[];
  /** Shortcut string parsed on `+` or whitespace. e.g. "cmd+k", "ctrl shift p". */
  shortcut?: string;
  /** Visual separator between keys when multiple. */
  separator?: string;
}

const props = withDefaults(defineProps<Props>(), {
  variant: "outlined",
  size: "sm",
});

const KEY_GLYPHS: Record<string, string> = {
  cmd: "⌘",
  command: "⌘",
  meta: "⌘",
  ctrl: "⌃",
  control: "⌃",
  alt: "⌥",
  option: "⌥",
  opt: "⌥",
  shift: "⇧",
  enter: "↵",
  return: "↵",
  tab: "⇥",
  backspace: "⌫",
  delete: "⌦",
  esc: "⎋",
  escape: "⎋",
  space: "␣",
  up: "↑",
  down: "↓",
  left: "←",
  right: "→",
  pageup: "⇞",
  pagedown: "⇟",
  home: "↖",
  end: "↘",
};

function isMac(): boolean {
  if (typeof navigator === "undefined") return false;
  return /Mac|iPhone|iPad|iPod/.test(navigator.platform || "");
}

function normalizeKey(raw: string, mac: boolean): string {
  const trimmed = raw.trim();
  if (!trimmed) return "";
  const lower = trimmed.toLowerCase();
  if (lower === "mod") return mac ? KEY_GLYPHS.cmd : KEY_GLYPHS.ctrl;
  if (KEY_GLYPHS[lower]) return KEY_GLYPHS[lower];
  return trimmed.length === 1 ? trimmed.toUpperCase() : trimmed;
}

const resolvedKeys = computed<string[]>(() => {
  if (props.keys?.length) return props.keys;
  if (props.shortcut) return props.shortcut.split(/[\s+]+/).filter(Boolean);
  return [];
});

const mac = isMac();
const rootClasses = computed(() => ["sisyphos-kbd", props.variant, props.size]);
</script>

<template>
  <kbd v-if="resolvedKeys.length === 0" :class="rootClasses">
    <slot />
  </kbd>
  <span v-else :class="rootClasses" role="group">
    <template v-for="(raw, i) in resolvedKeys" :key="`${raw}-${i}`">
      <span v-if="i > 0 && separator" class="sisyphos-kbd-separator" aria-hidden="true">
        {{ separator }}
      </span>
      <kbd class="sisyphos-kbd-key">{{ normalizeKey(raw, mac) }}</kbd>
    </template>
  </span>
</template>

<style src="./Kbd.scss"></style>
