// packages/angular/src/skeleton/page-skeleton.component.ts
/**
 * PageSkeleton — preset layout skeletons for full pages.
 *
 * Same layout presets and section-toggle props as the React/Vue versions
 * (`default`, `cards`, `table`, `detail`). Mounts `<sui-skeleton>` and
 * `<sui-skeleton-text>` building blocks under the same class names so the
 * shared stylesheet works.
 */
import { ChangeDetectionStrategy, Component, Input, computed, signal } from "@angular/core";
import { Skeleton, type SkeletonAnimation } from "./skeleton.component";
import { SkeletonText } from "./skeleton-text.component";

export type PageSkeletonLayout = "default" | "cards" | "table" | "detail";

@Component({
  selector: "sui-page-skeleton",
  standalone: true,
  imports: [Skeleton, SkeletonText],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div [class]="rootClasses()" role="status" aria-label="Loading page">
      @if (showHeader()) {
        <div class="sisyphos-page-skeleton-header">
          <sui-skeleton shape="circular" [width]="40" [height]="40" [animation]="animation()" />
          <div class="sisyphos-page-skeleton-header-text">
            <sui-skeleton width="40%" [height]="18" [animation]="animation()" />
            <sui-skeleton width="60%" [height]="12" [animation]="animation()" />
          </div>
        </div>
      }

      @if (layout() === "default" || layout() === "cards") {
        @if (cardCount() > 0) {
          <div
            class="sisyphos-page-skeleton-cards"
            [style.grid-template-columns]="cardsGridTemplate()"
          >
            @for (_ of cardIndexes(); track $index) {
              <div class="sisyphos-page-skeleton-card">
                <sui-skeleton width="40%" [height]="12" [animation]="animation()" />
                <sui-skeleton width="70%" [height]="24" [animation]="animation()" />
                <sui-skeleton width="30%" [height]="10" [animation]="animation()" />
              </div>
            }
          </div>
        }
      }

      @if (layout() === "default" || layout() === "table") {
        @if (tableRows() > 0) {
          <div class="sisyphos-page-skeleton-table">
            <div class="sisyphos-page-skeleton-table-header">
              @for (_ of columnIndexes(); track $index) {
                <sui-skeleton [height]="12" width="70%" [animation]="animation()" />
              }
            </div>
            @for (_ of rowIndexes(); track $index) {
              <div class="sisyphos-page-skeleton-table-row">
                @for (c of columnIndexes(); track c) {
                  <sui-skeleton [height]="12" [width]="cellWidth(c)" [animation]="animation()" />
                }
              </div>
            }
          </div>
        }
      }

      @if (layout() === "detail") {
        <div class="sisyphos-page-skeleton-detail">
          <sui-skeleton [width]="160" [height]="120" [animation]="animation()" />
          <div class="sisyphos-page-skeleton-detail-body">
            <sui-skeleton width="50%" [height]="20" [animation]="animation()" />
            <sui-skeleton-text [lines]="4" [animation]="animation()" />
          </div>
        </div>
      }
    </div>
  `,
})
export class PageSkeleton {
  private readonly _layout = signal<PageSkeletonLayout>("default");
  private readonly _showHeader = signal(true);
  private readonly _cardCount = signal(3);
  private readonly _tableRows = signal(5);
  private readonly _tableColumns = signal(4);
  private readonly _animation = signal<SkeletonAnimation>("shimmer");

  readonly layout = this._layout.asReadonly();
  readonly showHeader = this._showHeader.asReadonly();
  readonly cardCount = this._cardCount.asReadonly();
  readonly tableRows = this._tableRows.asReadonly();
  readonly animation = this._animation.asReadonly();

  @Input("layout") set layoutInput(v: PageSkeletonLayout) {
    this._layout.set(v);
  }
  @Input("showHeader") set showHeaderInput(v: boolean) {
    this._showHeader.set(v);
  }
  @Input("cardCount") set cardCountInput(v: number) {
    this._cardCount.set(v);
  }
  @Input("tableRows") set tableRowsInput(v: number) {
    this._tableRows.set(v);
  }
  @Input("tableColumns") set tableColumnsInput(v: number) {
    this._tableColumns.set(v);
  }
  @Input("animation") set animationInput(v: SkeletonAnimation) {
    this._animation.set(v);
  }

  readonly rootClasses = computed(() => `sisyphos-page-skeleton ${this._layout()}`);
  readonly cardsGridTemplate = computed(() => `repeat(${this._cardCount()}, minmax(0, 1fr))`);

  readonly cardIndexes = computed(() => Array.from({ length: this._cardCount() }, (_, i) => i));
  readonly rowIndexes = computed(() => Array.from({ length: this._tableRows() }, (_, i) => i));
  readonly columnIndexes = computed(() =>
    Array.from({ length: this._tableColumns() }, (_, i) => i)
  );

  /** Mirrors React's per-column width pattern. */
  cellWidth = (c: number): string => {
    const widths = ["90%", "65%", "80%", "45%"];
    return widths[c % widths.length]!;
  };
}

// packages/react/src/skeleton/PageSkeleton.tsx
/**
 * PageSkeleton — preset layout skeletons for full pages.
 *
 * Saves teams from wiring `<Skeleton>` primitives into the same header-cards-
 * table shape on every dashboard. Opt out of any section with `showHeader`,
 * `cardCount`, or `tableRows={0}` — or build a custom layout with the
 * primitive `<Skeleton>` yourself.
 */
import React from "react";
import { cx } from "@sisyphos-ui/core/internal";
import { Skeleton } from "./Skeleton";
import { SkeletonText } from "./SkeletonText";
import "./Skeleton.scss";

export interface PageSkeletonProps extends React.HTMLAttributes<HTMLDivElement> {
  /** Layout preset. */
  layout?: "default" | "cards" | "table" | "detail";
  /** Render the top "title + subtitle + icon" header bar. Default true. */
  showHeader?: boolean;
  /** Number of summary cards in the top row. Default 3. */
  cardCount?: number;
  /** Number of body rows for the bottom list/table. Default 5. 0 hides it. */
  tableRows?: number;
  /** Number of table columns (skeletons per row). Default 4. */
  tableColumns?: number;
  /** Animation forwarded to every underlying `<Skeleton>`. */
  animation?: "shimmer" | "pulse" | "none";
}

export const PageSkeleton = React.forwardRef<HTMLDivElement, PageSkeletonProps>(
  function PageSkeleton(
    {
      layout = "default",
      showHeader = true,
      cardCount = 3,
      tableRows = 5,
      tableColumns = 4,
      animation = "shimmer",
      className,
      ...rest
    },
    ref
  ) {
    const renderHeader = () => (
      <div className="sisyphos-page-skeleton-header">
        <Skeleton shape="circular" width={40} height={40} animation={animation} />
        <div className="sisyphos-page-skeleton-header-text">
          <Skeleton width="40%" height={18} animation={animation} />
          <Skeleton width="60%" height={12} animation={animation} />
        </div>
      </div>
    );

    const renderCards = () => (
      <div
        className="sisyphos-page-skeleton-cards"
        style={{ gridTemplateColumns: `repeat(${cardCount}, minmax(0, 1fr))` }}
      >
        {Array.from({ length: cardCount }).map((_, i) => (
          <div key={i} className="sisyphos-page-skeleton-card">
            <Skeleton width="40%" height={12} animation={animation} />
            <Skeleton width="70%" height={24} animation={animation} />
            <Skeleton width="30%" height={10} animation={animation} />
          </div>
        ))}
      </div>
    );

    const renderTable = () => (
      <div className="sisyphos-page-skeleton-table">
        <div className="sisyphos-page-skeleton-table-header">
          {Array.from({ length: tableColumns }).map((_, i) => (
            <Skeleton key={i} height={12} width="70%" animation={animation} />
          ))}
        </div>
        {Array.from({ length: tableRows }).map((_, r) => (
          <div key={r} className="sisyphos-page-skeleton-table-row">
            {Array.from({ length: tableColumns }).map((_, c) => {
              const widths = ["90%", "65%", "80%", "45%"];
              return (
                <Skeleton
                  key={c}
                  height={12}
                  width={widths[c % widths.length]}
                  animation={animation}
                />
              );
            })}
          </div>
        ))}
      </div>
    );

    const renderDetail = () => (
      <div className="sisyphos-page-skeleton-detail">
        <Skeleton width={160} height={120} animation={animation} />
        <div className="sisyphos-page-skeleton-detail-body">
          <Skeleton width="50%" height={20} animation={animation} />
          <SkeletonText lines={4} animation={animation} />
        </div>
      </div>
    );

    return (
      <div
        ref={ref}
        role="status"
        aria-label="Loading page"
        className={cx("sisyphos-page-skeleton", layout, className)}
        {...rest}
      >
        {showHeader && renderHeader()}
        {layout === "default" && (
          <>
            {cardCount > 0 && renderCards()}
            {tableRows > 0 && renderTable()}
          </>
        )}
        {layout === "cards" && cardCount > 0 && renderCards()}
        {layout === "table" && tableRows > 0 && renderTable()}
        {layout === "detail" && renderDetail()}
      </div>
    );
  }
);

PageSkeleton.displayName = "PageSkeleton";
