// packages/tree-select/src/TreeSelect.tsx
/**
 * TreeSelect — hierarchical multi-select with search, optional cascade
 * selection, and partial (mixed) state for parent nodes.
 *
 * The dropdown is portal-mounted with auto-flip placement. Works controlled
 * (`value`) or uncontrolled (`defaultValue`).
 */
import React, {
  useCallback,
  useEffect,
  useId,
  useMemo,
  useRef,
  useState,
} from "react";
import { Portal } from "@sisyphos-ui/portal";
import { cx, computePosition, useEscapeKey, type Placement } from "@sisyphos-ui/core/internal";
import type { TreeNode, TreeNodeId } from "./types";
import { descendantIds, filterTree, nodeState, findNode } from "./utils";
import "./TreeSelect.scss";

export interface TreeSelectProps {
  /** Tree data rendered in the dropdown. */
  nodes: TreeNode[];
  /** Selected node ids (controlled). */
  value?: TreeNodeId[];
  /** Initial selection (uncontrolled). */
  defaultValue?: TreeNodeId[];
  /** Called with the next selection when it changes. */
  onChange?: (ids: TreeNodeId[]) => void;
  /** Field label rendered above the trigger. */
  label?: string;
  /** Placeholder when nothing is selected. */
  placeholder?: string;
  /** Overrides the trigger text while closed. */
  triggerLabel?: string;
  /** Marks the field as invalid for styling and ARIA. */
  error?: boolean;
  /** Message rendered below the field when `error` is true. */
  errorMessage?: string;
  disabled?: boolean;
  required?: boolean;
  /** Show a search input above the tree. */
  searchable?: boolean;
  searchPlaceholder?: string;
  /** Show a clear button when there is a selection. */
  clearable?: boolean;
  fullWidth?: boolean;
  size?: "sm" | "md" | "lg";
  /** Cascade child selection when toggling a parent. Default `true`. */
  cascade?: boolean;
  /** Tags to show in the trigger before collapsing into `+N`. Default 3. */
  maxTagCount?: number;
  placement?: Placement;
  className?: string;
}

const ChevronIcon = ({ rotated }: { rotated?: boolean }) => (
  <svg viewBox="0 0 24 24" width="18" height="18" aria-hidden="true" style={{ transform: rotated ? "rotate(180deg)" : undefined, transition: "transform 150ms" }}>
    <path d="M7 10l5 5 5-5z" fill="currentColor" />
  </svg>
);
const ChevronRight = () => (
  <svg viewBox="0 0 24 24" width="14" height="14" aria-hidden="true">
    <path d="M9 6l6 6-6 6" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
  </svg>
);
const ChevronDown = () => (
  <svg viewBox="0 0 24 24" width="14" height="14" aria-hidden="true">
    <path d="M6 9l6 6 6-6" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
  </svg>
);
const ClearIcon = () => (
  <svg viewBox="0 0 24 24" width="14" height="14" aria-hidden="true">
    <path d="M19 6.41 17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12z" fill="currentColor" />
  </svg>
);

export const TreeSelect: React.FC<TreeSelectProps> = ({
  nodes,
  value: valueProp,
  defaultValue,
  onChange,
  label,
  placeholder = "Select…",
  triggerLabel,
  error = false,
  errorMessage,
  disabled = false,
  required = false,
  searchable = true,
  searchPlaceholder = "Search…",
  clearable = false,
  fullWidth = false,
  size = "md",
  cascade = true,
  maxTagCount = 3,
  placement = "bottom-start",
  className,
}) => {
  const reactId = useId();
  const listboxId = `sisyphos-tree-${reactId}`;

  const isControlled = valueProp !== undefined;
  const [internal, setInternal] = useState<TreeNodeId[]>(defaultValue ?? []);
  const selectedIds = isControlled ? (valueProp ?? []) : internal;
  const selectedSet = useMemo(() => new Set<TreeNodeId>(selectedIds), [selectedIds]);

  const [open, setOpen] = useState(false);
  const [search, setSearch] = useState("");
  const [expanded, setExpanded] = useState<Record<string, boolean>>({});
  const [pos, setPos] = useState<{ left: number; top: number; placement: Placement; width: number } | null>(null);

  const triggerRef = useRef<HTMLDivElement | null>(null);
  const listRef = useRef<HTMLDivElement | null>(null);
  const searchRef = useRef<HTMLInputElement | null>(null);

  useEscapeKey(() => setOpen(false), open);

  useEffect(() => {
    if (!open) return;
    const handler = (e: MouseEvent) => {
      const tgt = e.target as Node | null;
      if (!tgt) return;
      if (triggerRef.current?.contains(tgt)) return;
      if (listRef.current?.contains(tgt)) return;
      setOpen(false);
      setSearch("");
    };
    document.addEventListener("mousedown", handler);
    return () => document.removeEventListener("mousedown", handler);
  }, [open]);

  useEffect(() => {
    if (!open) {
      setPos(null);
      return;
    }
    if (searchable && searchRef.current) searchRef.current.focus();
    let raf = 0;
    const update = () => {
      const anchor = triggerRef.current;
      const list = listRef.current;
      if (!anchor || !list) return;
      const a = anchor.getBoundingClientRect();
      const sz = { width: list.offsetWidth, height: list.offsetHeight };
      const p = computePosition(a, sz, placement, 4);
      setPos({ ...p, width: a.width });
    };
    raf = requestAnimationFrame(() => requestAnimationFrame(update));
    const onWin = () => update();
    window.addEventListener("scroll", onWin, true);
    window.addEventListener("resize", onWin);
    return () => {
      cancelAnimationFrame(raf);
      window.removeEventListener("scroll", onWin, true);
      window.removeEventListener("resize", onWin);
    };
  }, [open, placement, searchable]);

  const filtered = useMemo(() => filterTree(nodes, search), [nodes, search]);

  const emit = useCallback(
    (next: TreeNodeId[]) => {
      if (!isControlled) setInternal(next);
      onChange?.(next);
    },
    [isControlled, onChange]
  );

  const toggleNode = (node: TreeNode) => {
    if (node.disabled) return;
    const ids = cascade ? descendantIds(node) : [node.id];
    const isSelected = nodeState(node, selectedSet) === "checked";
    if (isSelected) {
      const removeSet = new Set(ids);
      emit(selectedIds.filter((id) => !removeSet.has(id)));
    } else {
      const merged = new Set([...selectedIds, ...ids]);
      emit(Array.from(merged));
    }
  };

  const toggleExpand = (id: TreeNodeId, e: React.MouseEvent) => {
    e.stopPropagation();
    setExpanded((prev) => ({ ...prev, [String(id)]: !prev[String(id)] }));
  };

  const selectedItems = useMemo(() => {
    return selectedIds
      .map((id) => findNode(nodes, id))
      .filter((n): n is TreeNode => Boolean(n));
  }, [selectedIds, nodes]);

  const renderNode = (node: TreeNode, level: number): React.ReactNode => {
    const hasChildren = !!(node.children && node.children.length);
    const isOpenNode = expanded[String(node.id)];
    const state = nodeState(node, selectedSet);

    return (
      <div key={String(node.id)} className="sisyphos-tree-node">
        <div
          className={cx(
            "sisyphos-tree-row",
            state === "checked" && "checked",
            state === "partial" && "partial",
            node.disabled && "disabled"
          )}
          style={{ paddingLeft: `${level * 20 + 8}px` }}
        >
          {hasChildren ? (
            <button
              type="button"
              className="sisyphos-tree-expand"
              onClick={(e) => toggleExpand(node.id, e)}
              aria-label={isOpenNode ? "Collapse" : "Expand"}
              aria-expanded={isOpenNode}
            >
              {isOpenNode ? <ChevronDown /> : <ChevronRight />}
            </button>
          ) : (
            <span className="sisyphos-tree-expand-spacer" />
          )}
          <button
            type="button"
            className="sisyphos-tree-toggle"
            onClick={() => toggleNode(node)}
            aria-checked={state === "checked" ? "true" : state === "partial" ? "mixed" : "false"}
            role="checkbox"
            disabled={node.disabled}
          >
            <span className={cx("sisyphos-tree-checkbox", state)}>
              {state === "checked" && (
                <svg viewBox="0 0 16 16" width="10" height="10" aria-hidden="true">
                  <path d="M2 8l4 4 8-8" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" />
                </svg>
              )}
              {state === "partial" && <span className="sisyphos-tree-partial" />}
            </span>
            <span className="sisyphos-tree-label" title={node.label}>{node.label}</span>
          </button>
        </div>
        {hasChildren && isOpenNode && (
          <div className="sisyphos-tree-children">
            {node.children!.map((c) => renderNode(c, level + 1))}
          </div>
        )}
      </div>
    );
  };

  const handleClear = (e: React.MouseEvent) => {
    e.stopPropagation();
    emit([]);
  };

  const tags = selectedItems.slice(0, maxTagCount);
  const overflow = selectedItems.length - tags.length;

  return (
    <div
      className={cx(
        "sisyphos-tree-select",
        size,
        error && "error",
        disabled && "disabled",
        fullWidth && "full-width",
        className
      )}
    >
      {label && (
        <label className={cx("sisyphos-tree-select-label", error && "error", required && "required")}>
          {label}
        </label>
      )}
      <div
        ref={triggerRef}
        className={cx("sisyphos-tree-select-trigger", open && "open")}
        onClick={() => !disabled && setOpen((o) => !o)}
        role="combobox"
        aria-haspopup="tree"
        aria-expanded={open}
        aria-controls={open ? listboxId : undefined}
        tabIndex={disabled ? -1 : 0}
      >
        <div className="sisyphos-tree-select-value">
          {selectedItems.length === 0 ? (
            <span className="sisyphos-tree-select-placeholder">{triggerLabel ?? placeholder}</span>
          ) : (
            <div className="sisyphos-tree-select-tags">
              {tags.map((t) => (
                <span key={String(t.id)} className="sisyphos-tree-select-tag" title={t.label}>
                  {t.label}
                </span>
              ))}
              {overflow > 0 && <span className="sisyphos-tree-select-tag more">+{overflow}</span>}
            </div>
          )}
        </div>
        {clearable && selectedItems.length > 0 && !disabled && (
          <button
            type="button"
            className="sisyphos-tree-select-clear"
            onClick={handleClear}
            aria-label="Clear all"
          >
            <ClearIcon />
          </button>
        )}
        <span className="sisyphos-tree-select-chevron"><ChevronIcon rotated={open} /></span>
      </div>

      {open && (
        <Portal>
          <div
            ref={listRef}
            id={listboxId}
            role="tree"
            className="sisyphos-tree-select-dropdown"
            style={{
              position: "fixed",
              left: pos?.left ?? 0,
              top: pos?.top ?? 0,
              minWidth: pos?.width ?? 0,
              opacity: pos ? 1 : 0,
            }}
          >
            {searchable && (
              <div className="sisyphos-tree-select-search">
                <input
                  ref={searchRef}
                  type="text"
                  placeholder={searchPlaceholder}
                  value={search}
                  onChange={(e) => setSearch(e.target.value)}
                />
              </div>
            )}
            <div className="sisyphos-tree-select-content">
              {filtered.length === 0 ? (
                <div className="sisyphos-tree-select-empty">No results</div>
              ) : (
                filtered.map((n) => renderNode(n, 0))
              )}
            </div>
          </div>
        </Portal>
      )}

      {error && errorMessage && (
        <span className="sisyphos-tree-select-error" role="alert">{errorMessage}</span>
      )}
    </div>
  );
};

// packages/angular/src/tree-select/tree-select.component.ts
/**
 * TreeSelect — Angular 18 standalone hierarchical multi-select with search,
 * cascade selection, and partial state for parent nodes. Mirrors the
 * React/Vue versions exactly: same class names, same node shape, same
 * `descendantIds` / `nodeState` rules from the shared `utils`.
 */
import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  EventEmitter,
  HostListener,
  Input as NgInput,
  OnDestroy,
  Output,
  ViewChild,
  computed,
  effect,
  signal,
} from "@angular/core";
import { computePosition, type Placement } from "@sisyphos-ui/core/internal";
import { TreeNodeRow } from "./tree-node-row.component";
import {
  descendantIds,
  filterTree,
  findNode,
  nodeState,
} from "./utils";
import type { TreeNode, TreeNodeId } from "./types";

let treeCounter = 0;

@Component({
  selector: "sui-tree-select",
  standalone: true,
  imports: [TreeNodeRow],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div [class]="rootClasses()">
      @if (label()) {
        <label [class]="labelClasses()">{{ label() }}</label>
      }
      <div
        #trigger
        [class]="triggerClasses()"
        role="combobox"
        aria-haspopup="tree"
        [attr.aria-expanded]="open()"
        [attr.aria-controls]="open() ? listboxId : null"
        [tabindex]="disabled() ? -1 : 0"
        (click)="toggleOpen()"
      >
        <div class="sisyphos-tree-select-value">
          @if (selectedItems().length === 0) {
            <span class="sisyphos-tree-select-placeholder">
              {{ triggerLabel() ?? placeholder() }}
            </span>
          } @else {
            <div class="sisyphos-tree-select-tags">
              @for (t of visibleTags(); track t.id) {
                <span class="sisyphos-tree-select-tag" [title]="t.label">{{ t.label }}</span>
              }
              @if (overflow() > 0) {
                <span class="sisyphos-tree-select-tag more">+{{ overflow() }}</span>
              }
            </div>
          }
        </div>
        @if (clearable() && selectedItems().length > 0 && !disabled()) {
          <button
            type="button"
            class="sisyphos-tree-select-clear"
            aria-label="Clear all"
            (click)="clearAll($event)"
          >
            <svg viewBox="0 0 24 24" width="14" height="14" aria-hidden="true">
              <path d="M19 6.41 17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12z" fill="currentColor" />
            </svg>
          </button>
        }
        <span class="sisyphos-tree-select-chevron">
          <svg viewBox="0 0 24 24" width="18" height="18" aria-hidden="true"
               [style.transform]="open() ? 'rotate(180deg)' : null"
               [style.transition]="'transform 150ms'">
            <path d="M7 10l5 5 5-5z" fill="currentColor" />
          </svg>
        </span>
      </div>

      @if (open()) {
        <div
          #list
          [id]="listboxId"
          role="tree"
          class="sisyphos-tree-select-dropdown"
          [style.position]="'fixed'"
          [style.left.px]="pos()?.left ?? 0"
          [style.top.px]="pos()?.top ?? 0"
          [style.min-width.px]="pos()?.width ?? 0"
          [style.opacity]="pos() ? 1 : 0"
          [style.z-index]="1100"
        >
          @if (searchable()) {
            <div class="sisyphos-tree-select-search">
              <input
                #searchInput
                type="text"
                [placeholder]="searchPlaceholder()"
                [value]="search()"
                (input)="onSearchInput($event)"
              />
            </div>
          }
          <div class="sisyphos-tree-select-content">
            @if (filtered().length === 0) {
              <div class="sisyphos-tree-select-empty">No results</div>
            } @else {
              @for (n of filtered(); track n.id) {
                <sui-tree-node-row
                  [node]="n"
                  [level]="0"
                  [selectedSet]="selectedSet()"
                  [expanded]="expanded()"
                  [searchActive]="!!search()"
                  (toggleNode)="onToggleNode($event)"
                  (toggleExpand)="onToggleExpand($event)"
                />
              }
            }
          </div>
        </div>
      }

      @if (error() && errorMessage()) {
        <span class="sisyphos-tree-select-error" role="alert">{{ errorMessage() }}</span>
      }
    </div>
  `,
})
export class TreeSelect implements OnDestroy {
  readonly listboxId = `sisyphos-tree-${++treeCounter}`;

  private readonly _nodes = signal<TreeNode[]>([]);
  private readonly _value = signal<TreeNodeId[]>([]);
  private readonly _label = signal<string | undefined>(undefined);
  private readonly _placeholder = signal<string>("Select…");
  private readonly _triggerLabel = signal<string | undefined>(undefined);
  private readonly _error = signal(false);
  private readonly _errorMessage = signal<string | undefined>(undefined);
  private readonly _disabled = signal(false);
  private readonly _required = signal(false);
  private readonly _searchable = signal(true);
  private readonly _searchPlaceholder = signal<string>("Search…");
  private readonly _clearable = signal(false);
  private readonly _fullWidth = signal(false);
  private readonly _size = signal<"sm" | "md" | "lg">("md");
  private readonly _cascade = signal(true);
  private readonly _maxTagCount = signal(3);
  private readonly _placement = signal<Placement>("bottom-start");

  private readonly _open = signal(false);
  private readonly _search = signal("");
  private readonly _expanded = signal<Record<string, boolean>>({});
  protected readonly pos = signal<{ left: number; top: number; placement: Placement; width: number } | null>(null);

  readonly value = this._value.asReadonly();
  readonly label = this._label.asReadonly();
  readonly placeholder = this._placeholder.asReadonly();
  readonly triggerLabel = this._triggerLabel.asReadonly();
  readonly error = this._error.asReadonly();
  readonly errorMessage = this._errorMessage.asReadonly();
  readonly disabled = this._disabled.asReadonly();
  readonly searchable = this._searchable.asReadonly();
  readonly searchPlaceholder = this._searchPlaceholder.asReadonly();
  readonly clearable = this._clearable.asReadonly();
  readonly open = this._open.asReadonly();
  readonly search = this._search.asReadonly();
  readonly expanded = this._expanded.asReadonly();

  @NgInput("nodes") set nodesInput(v: TreeNode[]) { this._nodes.set(v ?? []); }
  @NgInput("value") set valueInput(v: TreeNodeId[] | undefined) {
    if (v !== undefined) this._value.set(v);
  }
  @NgInput("label") set labelInput(v: string | undefined) { this._label.set(v); }
  @NgInput("placeholder") set placeholderInput(v: string) { this._placeholder.set(v); }
  @NgInput("triggerLabel") set triggerLabelInput(v: string | undefined) {
    this._triggerLabel.set(v);
  }
  @NgInput("error") set errorInput(v: boolean) { this._error.set(v); }
  @NgInput("errorMessage") set errorMessageInput(v: string | undefined) {
    this._errorMessage.set(v);
  }
  @NgInput("disabled") set disabledInput(v: boolean) { this._disabled.set(v); }
  @NgInput("required") set requiredInput(v: boolean) { this._required.set(v); }
  @NgInput("searchable") set searchableInput(v: boolean) { this._searchable.set(v); }
  @NgInput("searchPlaceholder") set searchPlaceholderInput(v: string) {
    this._searchPlaceholder.set(v);
  }
  @NgInput("clearable") set clearableInput(v: boolean) { this._clearable.set(v); }
  @NgInput("fullWidth") set fullWidthInput(v: boolean) { this._fullWidth.set(v); }
  @NgInput("size") set sizeInput(v: "sm" | "md" | "lg") { this._size.set(v); }
  @NgInput("cascade") set cascadeInput(v: boolean) { this._cascade.set(v); }
  @NgInput("maxTagCount") set maxTagCountInput(v: number) { this._maxTagCount.set(v); }
  @NgInput("placement") set placementInput(v: Placement) { this._placement.set(v); }

  @Output() readonly valueChange = new EventEmitter<TreeNodeId[]>();

  @ViewChild("trigger") triggerRef?: ElementRef<HTMLDivElement>;
  @ViewChild("list") listRef?: ElementRef<HTMLDivElement>;
  @ViewChild("searchInput") searchInputRef?: ElementRef<HTMLInputElement>;

  readonly selectedSet = computed(() => new Set<TreeNodeId>(this._value()));

  readonly selectedItems = computed<TreeNode[]>(() => {
    const out: TreeNode[] = [];
    for (const id of this._value()) {
      const n = findNode(this._nodes(), id);
      if (n) out.push(n);
    }
    return out;
  });

  readonly visibleTags = computed(() => this.selectedItems().slice(0, this._maxTagCount()));
  readonly overflow = computed(() => this.selectedItems().length - this.visibleTags().length);

  readonly filtered = computed(() => filterTree(this._nodes(), this._search()));

  readonly rootClasses = computed(() =>
    [
      "sisyphos-tree-select",
      this._size(),
      this._error() && "error",
      this._disabled() && "disabled",
      this._fullWidth() && "full-width",
    ]
      .filter(Boolean)
      .join(" ")
  );

  readonly labelClasses = computed(() =>
    [
      "sisyphos-tree-select-label",
      this._error() && "error",
      this._required() && "required",
    ]
      .filter(Boolean)
      .join(" ")
  );

  readonly triggerClasses = computed(() =>
    [
      "sisyphos-tree-select-trigger",
      this._open() && "open",
    ]
      .filter(Boolean)
      .join(" ")
  );

  private resizeListener?: () => void;
  private scrollListener?: () => void;

  constructor() {
    effect(() => {
      if (this._open()) {
        if (this._searchable()) queueMicrotask(() => this.searchInputRef?.nativeElement.focus());
        queueMicrotask(() => requestAnimationFrame(() => this.reposition()));
        this.installScrollListeners();
      } else {
        this.pos.set(null);
        this._search.set("");
        this.removeScrollListeners();
      }
    });
  }

  ngOnDestroy(): void { this.removeScrollListeners(); }

  // ── trigger + dropdown ───────────────────────────────────────────────

  toggleOpen(): void {
    if (this._disabled()) return;
    this._open.set(!this._open());
  }

  onSearchInput(event: Event): void {
    this._search.set((event.target as HTMLInputElement).value);
  }

  // ── selection ────────────────────────────────────────────────────────

  onToggleNode(node: TreeNode): void {
    if (node.disabled) return;
    const ids = this._cascade() ? descendantIds(node) : [node.id];
    const current = this._value();
    const set = this.selectedSet();
    const isSelected = nodeState(node, set) === "checked";
    const next = isSelected
      ? current.filter((id) => !ids.includes(id))
      : Array.from(new Set([...current, ...ids]));
    this._value.set(next);
    this.valueChange.emit(next);
  }

  onToggleExpand(id: TreeNodeId): void {
    this._expanded.update((prev) => ({ ...prev, [String(id)]: !prev[String(id)] }));
  }

  clearAll(event: MouseEvent): void {
    event.stopPropagation();
    this._value.set([]);
    this.valueChange.emit([]);
  }

  // ── outside-click + escape ───────────────────────────────────────────

  @HostListener("document:keydown.escape")
  onEscape(): void {
    if (this._open()) this._open.set(false);
  }

  @HostListener("document:mousedown", ["$event"])
  onDocumentMousedown(event: MouseEvent): void {
    if (!this._open()) return;
    const tgt = event.target as Node | null;
    if (this.triggerRef?.nativeElement.contains(tgt as Node)) return;
    if (this.listRef?.nativeElement.contains(tgt as Node)) return;
    this._open.set(false);
  }

  // ── positioning ──────────────────────────────────────────────────────

  private reposition(): void {
    const anchor = this.triggerRef?.nativeElement;
    const list = this.listRef?.nativeElement;
    if (!anchor || !list) return;
    const a = anchor.getBoundingClientRect();
    const size = { width: list.offsetWidth, height: list.offsetHeight };
    const p = computePosition(a, size, this._placement(), 4);
    this.pos.set({ ...p, width: a.width });
  }

  private installScrollListeners(): void {
    this.scrollListener = () => this.reposition();
    this.resizeListener = () => this.reposition();
    window.addEventListener("scroll", this.scrollListener, true);
    window.addEventListener("resize", this.resizeListener);
  }

  private removeScrollListeners(): void {
    if (this.scrollListener) {
      window.removeEventListener("scroll", this.scrollListener, true);
      this.scrollListener = undefined;
    }
    if (this.resizeListener) {
      window.removeEventListener("resize", this.resizeListener);
      this.resizeListener = undefined;
    }
  }
}
