// packages/vue/src/dialog/Dialog.vue
<script setup lang="ts">
/**
 * Dialog — Vue 3 binding. Modal surface with backdrop, escape close,
 * scroll lock, and focus restoration. Compound API rendered as
 * `<Dialog>` + `<DialogHeader>` + `<DialogTitle>` + `<DialogBody>` +
 * `<DialogFooter>` + `<DialogClose>`.
 */
import { computed, nextTick, onBeforeUnmount, provide, ref, useId, watch } from "vue";
import { useEscapeKey } from "../composables";
import { DialogKey } from "./context";

interface Props {
  open: boolean;
  size?: "sm" | "md" | "lg" | "xl" | "full";
  closeOnBackdropClick?: boolean;
  closeOnEscape?: boolean;
  /** Show the auto-rendered close button in the corner. */
  showCloseButton?: boolean;
  /** aria-label for the auto close button. */
  closeButtonLabel?: string;
}

const props = withDefaults(defineProps<Props>(), {
  size: "md",
  closeOnBackdropClick: true,
  closeOnEscape: true,
  showCloseButton: false,
  closeButtonLabel: "Close",
});

const emit = defineEmits<{
  (e: "update:open", value: boolean): void;
}>();

const baseId = `sisyphos-dialog-${useId()}`;
const titleId = `${baseId}-title`;
const dialogRef = ref<HTMLDivElement | null>(null);
let restoreFocusEl: HTMLElement | null = null;
let prevOverflow = "";

function close() {
  emit("update:open", false);
}

useEscapeKey(
  () => {
    if (props.closeOnEscape) close();
  },
  computed(() => props.open)
);

watch(
  () => props.open,
  async (v) => {
    if (v) {
      restoreFocusEl = (document.activeElement as HTMLElement) ?? null;
      prevOverflow = document.body.style.overflow;
      document.body.style.overflow = "hidden";
      await nextTick();
      const target = (dialogRef.value?.querySelector(
        '[autofocus], button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])'
      ) ?? dialogRef.value) as HTMLElement | null;
      target?.focus?.();
    } else {
      document.body.style.overflow = prevOverflow;
      restoreFocusEl?.focus?.();
    }
  }
);

onBeforeUnmount(() => {
  if (props.open) document.body.style.overflow = prevOverflow;
});

function onBackdropClick() {
  if (props.closeOnBackdropClick) close();
}

const dialogClasses = computed(() => ["sisyphos-dialog", props.size]);

provide(DialogKey, {
  get titleId() {
    return titleId;
  },
  close,
});
</script>

<template>
  <Teleport to="body">
    <div v-if="open" class="sisyphos-dialog-backdrop" @mousedown.self="onBackdropClick">
      <div
        ref="dialogRef"
        role="dialog"
        aria-modal="true"
        :aria-labelledby="titleId"
        :class="dialogClasses"
        tabindex="-1"
      >
        <slot />
        <button
          v-if="showCloseButton"
          type="button"
          class="sisyphos-dialog-close-auto"
          :aria-label="closeButtonLabel"
          @click="close"
        >
          <svg viewBox="0 0 24 24" width="1em" height="1em" aria-hidden="true">
            <path
              d="M19 6.41 17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12z"
              fill="currentColor"
            />
          </svg>
        </button>
      </div>
    </div>
  </Teleport>
</template>

<style src="./Dialog.scss"></style>

// packages/dialog/src/Dialog.tsx
/**
 * Dialog — accessible modal with portal mounting, focus trap, and scroll lock.
 *
 * Closes on backdrop click and Escape by default; both are configurable.
 * Automatically wires `aria-labelledby` to `Dialog.Title`. Compose with
 * `Dialog.Header`, `Dialog.Title`, `Dialog.Description`, `Dialog.Body`,
 * `Dialog.Footer`, and `Dialog.Close`.
 */
import React, { useCallback, useEffect, useId, useMemo, useRef } from "react";
import { Portal, useFocusTrap, useScrollLock } from "@sisyphos-ui/portal";
import { cx, useEscapeKey } from "@sisyphos-ui/core/internal";
import { DialogContext } from "./context";
import "./Dialog.scss";

export type DialogSize = "sm" | "md" | "lg" | "xl" | "full";

export interface DialogProps {
  /** Whether the dialog is open. */
  open: boolean;
  /** Called with the next open state when the dialog requests to close. */
  onOpenChange: (open: boolean) => void;
  size?: DialogSize;
  /** Close when the backdrop is clicked. Default `true`. */
  closeOnBackdropClick?: boolean;
  /** Close when Escape is pressed. Default `true`. */
  closeOnEscape?: boolean;
  /** Render the backdrop. Disable for transparent dialogs. Default `true`. */
  backdrop?: boolean;
  /**
   * Render a floating close button in the top-right of the dialog. Default `false`.
   * Use this when you want a close affordance without composing `<Dialog.Close />`
   * yourself. For custom placement (e.g. inside a header), use the compound instead.
   */
  showCloseButton?: boolean;
  /** aria-label for the auto-rendered close button. Default `"Close"`. */
  closeButtonLabel?: string;
  /** Element that receives focus on open. Defaults to the first focusable child. */
  initialFocus?: React.RefObject<HTMLElement>;
  className?: string;
  children: React.ReactNode;
}

interface DialogComponent extends React.FC<DialogProps> {
  Header: typeof DialogHeader;
  Title: typeof DialogTitle;
  Description: typeof DialogDescription;
  Body: typeof DialogBody;
  Footer: typeof DialogFooter;
  Close: typeof DialogClose;
}

const DialogRoot: React.FC<DialogProps> = ({
  open,
  onOpenChange,
  size = "md",
  closeOnBackdropClick = true,
  closeOnEscape = true,
  backdrop = true,
  showCloseButton = false,
  closeButtonLabel = "Close",
  initialFocus,
  className,
  children,
}) => {
  const reactId = useId();
  const titleId = `sisyphos-dialog-title-${reactId}`;
  const descriptionId = `sisyphos-dialog-desc-${reactId}`;

  const contentRef = useRef<HTMLDivElement>(null);

  const close = useCallback(() => onOpenChange(false), [onOpenChange]);
  useEscapeKey(close, open && closeOnEscape);
  useScrollLock(open);
  useFocusTrap(contentRef, open);

  useEffect(() => {
    if (!open) return;
    const t = initialFocus?.current;
    if (t) {
      t.focus({ preventScroll: true });
    }
  }, [open, initialFocus]);

  const ctx = useMemo(
    () => ({ titleId, descriptionId, onClose: close }),
    [titleId, descriptionId, close]
  );

  if (!open) return null;

  return (
    <Portal>
      <div
        className={cx("sisyphos-dialog-root", backdrop && "with-backdrop")}
        onMouseDown={(e) => {
          if (!closeOnBackdropClick) return;
          if (e.target === e.currentTarget) close();
        }}
      >
        <div
          ref={contentRef}
          className={cx("sisyphos-dialog", size, showCloseButton && "has-auto-close", className)}
          role="dialog"
          aria-modal="true"
          aria-labelledby={titleId}
          aria-describedby={descriptionId}
          tabIndex={-1}
        >
          <DialogContext.Provider value={ctx}>
            {showCloseButton && (
              <DialogClose className="sisyphos-dialog-close--auto" aria-label={closeButtonLabel} />
            )}
            {children}
          </DialogContext.Provider>
        </div>
      </div>
    </Portal>
  );
};

const DialogHeader: React.FC<React.HTMLAttributes<HTMLDivElement>> = ({
  className,
  children,
  ...rest
}) => (
  <header className={cx("sisyphos-dialog-header", className)} {...rest}>
    {children}
  </header>
);

const DialogTitle: React.FC<React.HTMLAttributes<HTMLHeadingElement>> = ({
  className,
  children,
  ...rest
}) => {
  const { titleId } = React.useContext(DialogContext)!;
  return (
    <h2 id={titleId} className={cx("sisyphos-dialog-title", className)} {...rest}>
      {children}
    </h2>
  );
};

const DialogDescription: React.FC<React.HTMLAttributes<HTMLParagraphElement>> = ({
  className,
  children,
  ...rest
}) => {
  const { descriptionId } = React.useContext(DialogContext)!;
  return (
    <p id={descriptionId} className={cx("sisyphos-dialog-description", className)} {...rest}>
      {children}
    </p>
  );
};

const DialogBody: React.FC<React.HTMLAttributes<HTMLDivElement>> = ({
  className,
  children,
  ...rest
}) => (
  <div className={cx("sisyphos-dialog-body", className)} {...rest}>
    {children}
  </div>
);

const DialogFooter: React.FC<React.HTMLAttributes<HTMLDivElement>> = ({
  className,
  children,
  ...rest
}) => (
  <div className={cx("sisyphos-dialog-footer", className)} {...rest}>
    {children}
  </div>
);

const DialogClose: React.FC<Omit<React.ButtonHTMLAttributes<HTMLButtonElement>, "type">> = ({
  className,
  children,
  onClick,
  "aria-label": ariaLabel = "Close",
  ...rest
}) => {
  const { onClose } = React.useContext(DialogContext)!;
  return (
    <button
      type="button"
      className={cx("sisyphos-dialog-close", className)}
      aria-label={ariaLabel}
      onClick={(e) => {
        onClick?.(e);
        if (!e.defaultPrevented) onClose();
      }}
      {...rest}
    >
      {children ?? (
        <svg viewBox="0 0 24 24" width="1em" height="1em" aria-hidden="true">
          <path
            d="M19 6.41 17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12z"
            fill="currentColor"
          />
        </svg>
      )}
    </button>
  );
};

export const Dialog = DialogRoot as DialogComponent;
Dialog.Header = DialogHeader;
Dialog.Title = DialogTitle;
Dialog.Description = DialogDescription;
Dialog.Body = DialogBody;
Dialog.Footer = DialogFooter;
Dialog.Close = DialogClose;
