// packages/vue/src/tabs/Tabs.vue
<script setup lang="ts">
/**
 * Tabs — Vue 3 binding. Compound API rendered as `<Tabs>` + `<TabsList>` +
 * `<TabsTrigger>` + `<TabsPanel>`. Provides shared baseId + value via
 * provide/inject so siblings stay decoupled.
 */
import { provide, ref, useId, watch } from "vue";
import { TabsKey, type TabsOrientation } from "./context";

interface Props {
  /** Controlled active tab. */
  value?: string;
  /** Initial active tab when uncontrolled. */
  defaultValue?: string;
  orientation?: TabsOrientation;
  fullWidth?: boolean;
  variant?: "underline" | "pill" | "soft";
  size?: "sm" | "md" | "lg";
}

const props = withDefaults(defineProps<Props>(), {
  orientation: "horizontal",
  fullWidth: false,
  variant: "underline",
  size: "md",
});

const emit = defineEmits<{
  (e: "update:value", value: string): void;
  (e: "valueChange", value: string): void;
}>();

const baseId = `sisyphos-tabs-${useId()}`;
const internal = ref<string>(props.defaultValue ?? "");
const value = ref<string>(props.value ?? internal.value);

watch(
  () => props.value,
  (v) => {
    if (v !== undefined) value.value = v;
  }
);

function setValue(next: string) {
  if (props.value === undefined) {
    internal.value = next;
    value.value = next;
  }
  emit("update:value", next);
  emit("valueChange", next);
}

const triggers = new Map<string, HTMLButtonElement>();
function registerTrigger(v: string, el: HTMLButtonElement | null) {
  if (el) triggers.set(v, el);
  else triggers.delete(v);
}
function values(): string[] {
  return Array.from(triggers.keys());
}
function focusValue(v: string) {
  triggers.get(v)?.focus();
}

provide(TabsKey, {
  baseId,
  value,
  setValue,
  orientation: props.orientation,
  registerTrigger,
  focusValue,
  values,
});
</script>

<template>
  <div :class="['sisyphos-tabs', orientation, variant, size, fullWidth && 'full-width']">
    <slot />
  </div>
</template>

<style src="./Tabs.scss"></style>

// packages/tabs/src/Tabs.tsx
/**
 * Tabs — accessible tab list with roving tabindex, arrow-key navigation, and an
 * animated active indicator.
 *
 * Compound API: compose with `Tabs.List`, `Tabs.Trigger`, and `Tabs.Panel`.
 * Works as controlled (`value`) or uncontrolled (`defaultValue`).
 */
import type React from "react";
import { useCallback, useEffect, useId, useLayoutEffect, useMemo, useRef, useState } from "react";
import { cx } from "@sisyphos-ui/core/internal";
import { TabsContext, useTabs, type TabsOrientation } from "./context";
import "./Tabs.scss";

export interface TabsProps extends Omit<React.HTMLAttributes<HTMLDivElement>, "onChange"> {
  /** Active tab value (controlled). */
  value?: string;
  /** Initial active tab value (uncontrolled). */
  defaultValue?: string;
  /** Called with the new value when the active tab changes. */
  onValueChange?: (value: string) => void;
  orientation?: TabsOrientation;
  /** Stretch triggers to fill the list width. */
  fullWidth?: boolean;
  variant?: "underline" | "pill" | "soft";
  size?: "sm" | "md" | "lg";
}

interface TabsComponent extends React.FC<TabsProps> {
  List: typeof TabsList;
  Trigger: typeof TabsTrigger;
  Panel: typeof TabsPanel;
}

const TabsRoot: React.FC<TabsProps> = ({
  value: valueProp,
  defaultValue,
  onValueChange,
  orientation = "horizontal",
  fullWidth = false,
  variant = "underline",
  size = "md",
  className,
  children,
  ...rest
}) => {
  const reactId = useId();
  const baseId = `sisyphos-tabs-${reactId}`;

  const isControlled = valueProp !== undefined;
  const [internal, setInternal] = useState<string>(defaultValue ?? "");
  const value = isControlled ? (valueProp as string) : internal;

  const triggers = useRef<Map<string, HTMLButtonElement | null>>(new Map());

  const setValue = useCallback(
    (next: string) => {
      if (!isControlled) setInternal(next);
      onValueChange?.(next);
    },
    [isControlled, onValueChange]
  );

  const registerTrigger = useCallback((v: string, el: HTMLButtonElement | null) => {
    if (el) triggers.current.set(v, el);
    else triggers.current.delete(v);
  }, []);

  const focusValue = useCallback((v: string) => {
    triggers.current.get(v)?.focus();
  }, []);

  const values = useCallback(() => Array.from(triggers.current.keys()), []);

  const ctx = useMemo(
    () => ({ baseId, value, setValue, orientation, registerTrigger, focusValue, values }),
    [baseId, value, setValue, orientation, registerTrigger, focusValue, values]
  );

  useEffect(() => {
    if (value || !defaultValue) return;
    setValue(defaultValue);
  }, [value, defaultValue, setValue]);

  return (
    <div
      data-orientation={orientation}
      className={cx(
        "sisyphos-tabs",
        orientation,
        variant,
        size,
        fullWidth && "full-width",
        className
      )}
      {...rest}
    >
      <TabsContext.Provider value={ctx}>{children}</TabsContext.Provider>
    </div>
  );
};

export interface TabsListProps extends React.HTMLAttributes<HTMLDivElement> {}

const TabsList: React.FC<TabsListProps> = ({ className, children, ...rest }) => {
  const ctx = useTabs();
  const listRef = useRef<HTMLDivElement | null>(null);
  const [indicator, setIndicator] = useState<{
    x: number;
    y: number;
    width: number;
    height: number;
  } | null>(null);

  useLayoutEffect(() => {
    const update = () => {
      const list = listRef.current;
      if (!list) return;
      const active = list.querySelector<HTMLButtonElement>(
        `[data-sisyphos-tab-value="${CSS.escape(ctx.value)}"]`
      );
      if (!active) {
        setIndicator(null);
        return;
      }
      const aRect = active.getBoundingClientRect();
      const lRect = list.getBoundingClientRect();
      setIndicator({
        x: aRect.left - lRect.left,
        y: aRect.top - lRect.top,
        width: aRect.width,
        height: aRect.height,
      });
    };
    update();
    const ro = typeof ResizeObserver !== "undefined" ? new ResizeObserver(update) : null;
    if (ro && listRef.current) ro.observe(listRef.current);
    window.addEventListener("resize", update);
    return () => {
      window.removeEventListener("resize", update);
      ro?.disconnect();
    };
  }, [ctx.value]);

  const handleKeyDown = (e: React.KeyboardEvent) => {
    const horizontal = ctx.orientation === "horizontal";
    const next = horizontal ? "ArrowRight" : "ArrowDown";
    const prev = horizontal ? "ArrowLeft" : "ArrowUp";
    if (e.key !== next && e.key !== prev && e.key !== "Home" && e.key !== "End") return;
    e.preventDefault();
    const all = ctx.values();
    if (all.length === 0) return;
    const idx = Math.max(0, all.indexOf(ctx.value));
    let nextIdx = idx;
    if (e.key === next) nextIdx = (idx + 1) % all.length;
    else if (e.key === prev) nextIdx = (idx - 1 + all.length) % all.length;
    else if (e.key === "Home") nextIdx = 0;
    else if (e.key === "End") nextIdx = all.length - 1;
    const target = all[nextIdx];
    ctx.setValue(target);
    ctx.focusValue(target);
  };

  return (
    <div
      ref={listRef}
      role="tablist"
      aria-orientation={ctx.orientation}
      className={cx("sisyphos-tabs-list", className)}
      onKeyDown={handleKeyDown}
      {...rest}
    >
      {indicator && (
        <span
          className="sisyphos-tabs-indicator"
          style={{
            transform: `translate(${indicator.x}px, ${indicator.y}px)`,
            width: indicator.width,
            height: indicator.height,
          }}
          aria-hidden="true"
        />
      )}
      {children}
    </div>
  );
};

export interface TabsTriggerProps extends Omit<
  React.ButtonHTMLAttributes<HTMLButtonElement>,
  "value" | "onSelect"
> {
  /** Identifier matching a sibling `Tabs.Panel`. */
  value: string;
  /** Optional icon rendered before the label. */
  icon?: React.ReactNode;
  disabled?: boolean;
}

const TabsTrigger: React.FC<TabsTriggerProps> = ({
  value,
  icon,
  disabled = false,
  className,
  children,
  onClick,
  ...rest
}) => {
  const ctx = useTabs();
  const ref = useRef<HTMLButtonElement | null>(null);
  const selected = ctx.value === value;

  useEffect(() => {
    ctx.registerTrigger(value, ref.current);
    return () => ctx.registerTrigger(value, null);
  }, [ctx, value]);

  return (
    <button
      ref={ref}
      type="button"
      role="tab"
      id={`${ctx.baseId}-trigger-${value}`}
      aria-selected={selected}
      aria-controls={`${ctx.baseId}-panel-${value}`}
      tabIndex={selected ? 0 : -1}
      disabled={disabled}
      data-sisyphos-tab-value={value}
      className={cx(
        "sisyphos-tabs-trigger",
        selected && "active",
        disabled && "disabled",
        className
      )}
      onClick={(e) => {
        onClick?.(e);
        if (!disabled) ctx.setValue(value);
      }}
      {...rest}
    >
      {icon && (
        <span className="sisyphos-tabs-trigger-icon" aria-hidden="true">
          {icon}
        </span>
      )}
      <span className="sisyphos-tabs-trigger-label">{children}</span>
    </button>
  );
};

export interface TabsPanelProps extends Omit<React.HTMLAttributes<HTMLDivElement>, "value"> {
  /** Identifier matching a sibling `Tabs.Trigger`. */
  value: string;
  /** Keep the panel mounted when inactive; set `false` to unmount. Default `true`. */
  forceMount?: boolean;
}

const TabsPanel: React.FC<TabsPanelProps> = ({
  value,
  forceMount = true,
  className,
  children,
  ...rest
}) => {
  const ctx = useTabs();
  const selected = ctx.value === value;
  if (!selected && !forceMount) return null;
  return (
    <div
      role="tabpanel"
      id={`${ctx.baseId}-panel-${value}`}
      aria-labelledby={`${ctx.baseId}-trigger-${value}`}
      hidden={!selected}
      className={cx("sisyphos-tabs-panel", className)}
      tabIndex={0}
      {...rest}
    >
      {children}
    </div>
  );
};

export const Tabs = TabsRoot as TabsComponent;
Tabs.List = TabsList;
Tabs.Trigger = TabsTrigger;
Tabs.Panel = TabsPanel;
