// packages/angular/src/accordion/context.ts
/**
 * Accordion DI tokens — bridges Accordion → AccordionItem → Accordion
 * Trigger/Content. Item-scoped data (value, open, IDs) is provided by
 * AccordionItem itself; the root-level state (toggle, openness check, baseId,
 * single-vs-multiple mode) lives on Accordion.
 */
import { InjectionToken, type Signal } from "@angular/core";

export interface AccordionContextValue {
  baseId: Signal<string>;
  isOpen: (value: string) => boolean;
  toggle: (value: string) => void;
  multiple: Signal<boolean>;
}

export interface AccordionItemContextValue {
  value: Signal<string>;
  open: Signal<boolean>;
  triggerId: Signal<string>;
  contentId: Signal<string>;
}

export const AccordionCtx = new InjectionToken<AccordionContextValue>("sisyphos.accordion");
export const AccordionItemCtx = new InjectionToken<AccordionItemContextValue>(
  "sisyphos.accordion-item"
);

// packages/react/src/accordion/context.ts
import { createContext, useContext } from "react";

export interface AccordionContextValue {
  baseId: string;
  isOpen: (value: string) => boolean;
  toggle: (value: string) => void;
  multiple: boolean;
}

export const AccordionContext = createContext<AccordionContextValue | null>(null);

export function useAccordion(): AccordionContextValue {
  const ctx = useContext(AccordionContext);
  if (!ctx) throw new Error("[@sisyphos-ui/accordion] subcomponent used outside <Accordion>.");
  return ctx;
}

export interface AccordionItemContextValue {
  value: string;
  open: boolean;
  triggerId: string;
  contentId: string;
}

export const AccordionItemContext = createContext<AccordionItemContextValue | null>(null);

export function useAccordionItem(): AccordionItemContextValue {
  const ctx = useContext(AccordionItemContext);
  if (!ctx)
    throw new Error("[@sisyphos-ui/accordion] Trigger/Content must be inside <Accordion.Item>.");
  return ctx;
}
