// packages/angular/src/form-control/form-control.component.ts
/**
 * FormControl — Angular 18 standalone wrapper that coordinates id/ARIA
 * wiring between `<sui-form-label>`, the input element, `<sui-form-helper-text>`,
 * and `<sui-form-error-text>`.
 *
 * @example
 *   <sui-form-control [required]="true" [error]="!!err">
 *     <sui-form-label>Email</sui-form-label>
 *     <input type="email" formControlName="email" />
 *     <sui-form-helper-text>We'll never share it.</sui-form-helper-text>
 *     <sui-form-error-text>{{ err }}</sui-form-error-text>
 *   </sui-form-control>
 */
import {
  ChangeDetectionStrategy,
  Component,
  Input,
  computed,
  signal,
} from "@angular/core";
import { FormControlCtx, type FormControlContextValue } from "./context";

let fcCounter = 0;

@Component({
  selector: "sui-form-control",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  providers: [{ provide: FormControlCtx, useExisting: FormControl }],
  template: `
    <div [class]="rootClasses()">
      <ng-content />
    </div>
  `,
})
export class FormControl implements FormControlContextValue {
  private readonly _id = signal<string>(`sisyphos-field-${++fcCounter}`);
  private readonly _disabled = signal(false);
  private readonly _required = signal(false);
  private readonly _readOnly = signal(false);
  private readonly _error = signal(false);
  private readonly _fullWidth = signal(false);

  readonly id = this._id.asReadonly();
  readonly disabled = this._disabled.asReadonly();
  readonly required = this._required.asReadonly();
  readonly readOnly = this._readOnly.asReadonly();
  readonly error = this._error.asReadonly();

  readonly labelId = computed(() => `${this._id()}-label`);
  readonly helperId = computed(() => `${this._id()}-helper`);
  readonly errorId = computed(() => `${this._id()}-error`);

  readonly describedBy = computed(() =>
    this._error() ? this.errorId() : this.helperId()
  );

  @Input("id") set idInput(v: string | undefined) {
    if (v) this._id.set(v);
  }
  @Input("disabled") set disabledInput(v: boolean) { this._disabled.set(v); }
  @Input("required") set requiredInput(v: boolean) { this._required.set(v); }
  @Input("readOnly") set readOnlyInput(v: boolean) { this._readOnly.set(v); }
  @Input("error") set errorInput(v: boolean) { this._error.set(v); }
  @Input("fullWidth") set fullWidthInput(v: boolean) { this._fullWidth.set(v); }

  readonly rootClasses = computed(() =>
    [
      "sisyphos-form-control",
      this._error() && "error",
      this._disabled() && "disabled",
      this._fullWidth() && "full-width",
    ]
      .filter(Boolean)
      .join(" ")
  );
}

// packages/vue/src/form-control/FormControl.vue
<script setup lang="ts">
/**
 * FormControl — compound wrapper that coordinates id/ARIA wiring between
 * `<FormLabel>`, the input element, `<FormHelperText>`, and `<FormErrorText>`.
 *
 * @example
 *   <FormControl required :error="!!err">
 *     <FormLabel>Email</FormLabel>
 *     <input v-model="email" type="email" />
 *     <FormHelperText>We'll never share it.</FormHelperText>
 *     <FormErrorText>{{ err }}</FormErrorText>
 *   </FormControl>
 */
import { computed, provide, useId } from "vue";
import { FormControlInjectionKey } from "./context";

const props = withDefaults(
  defineProps<{
    /** Stable id for the input element. Auto-generated when omitted. */
    id?: string;
    disabled?: boolean;
    required?: boolean;
    readOnly?: boolean;
    error?: boolean;
    fullWidth?: boolean;
  }>(),
  {
    disabled: false,
    required: false,
    readOnly: false,
    error: false,
    fullWidth: false,
  }
);

const generatedId = `sisyphos-field-${useId()}`;
const fieldId = computed(() => props.id ?? generatedId);

const ctx = computed(() => {
  const id = fieldId.value;
  return {
    id,
    labelId: `${id}-label`,
    helperId: `${id}-helper`,
    errorId: `${id}-error`,
    disabled: props.disabled,
    required: props.required,
    readOnly: props.readOnly,
    error: props.error,
    describedBy: props.error ? `${id}-error` : `${id}-helper`,
  };
});

provide(FormControlInjectionKey, ctx);

const rootClasses = computed(() => [
  "sisyphos-form-control",
  props.error && "error",
  props.disabled && "disabled",
  props.fullWidth && "full-width",
]);
</script>

<template>
  <div :class="rootClasses">
    <slot />
  </div>
</template>

<style src="./FormControl.scss"></style>
