// packages/switch/src/Switch.tsx
/**
 * Switch — controlled toggle with `role="switch"` semantics.
 *
 * Always controlled: pass `checked` and `onChange`. An `aria-label` is required
 * when no visible label is rendered alongside the switch.
 */
import React, { useMemo, useCallback } from "react";
import "./Switch.scss";
import { CN, DEFAULTS } from "./constants";
import { mergeRefs } from "@sisyphos-ui/core/internal";

export interface SwitchProps extends Omit<React.ButtonHTMLAttributes<HTMLButtonElement>, "onChange"> {
  /** Current checked state. */
  checked: boolean;
  /** Semantic color used when checked. */
  color?: "neutral" | "primary" | "success" | "error" | "warning" | "info";
  size?: (typeof DEFAULTS)["size"];
  /** Called with the new checked value when the user toggles the switch. */
  onChange?: (checked: boolean) => void;
  /** Required when no adjacent visible label exists. */
  "aria-label"?: string;
}

export const Switch = React.forwardRef<HTMLButtonElement, SwitchProps>(
  function Switch(
    {
      checked,
      color = DEFAULTS.color,
      size = DEFAULTS.size,
      disabled = false,
      onChange,
      className = "",
      "aria-label": ariaLabel,
      ...props
    },
    ref
  ) {
    const buttonRef = React.useRef<HTMLButtonElement>(null);

    const switchClasses = useMemo(
      () =>
        [
          CN.switch,
          color,
          CN.size(size),
          checked && "checked",
          !checked && "unchecked",
          disabled && "disabled",
          className,
        ]
          .filter(Boolean)
          .join(" "),
      [color, size, checked, disabled, className]
    );

    const handleClick = useCallback(() => {
      if (disabled) return;
      onChange?.(!checked);
    }, [disabled, checked, onChange]);

    const handleKeyDown = useCallback(
      (e: React.KeyboardEvent) => {
        if (e.key === " " || e.key === "Enter") {
          e.preventDefault();
          handleClick();
        }
      },
      [handleClick]
    );

    return (
      <button
        ref={mergeRefs(buttonRef, ref)}
        type="button"
        role="switch"
        aria-checked={checked}
        aria-label={ariaLabel}
        aria-disabled={disabled || undefined}
        disabled={disabled}
        className={switchClasses}
        onClick={handleClick}
        onKeyDown={handleKeyDown}
        tabIndex={disabled ? -1 : undefined}
        {...props}
      >
        <span className={CN.toggle} aria-hidden />
      </button>
    );
  }
);

Switch.displayName = "Switch";

// packages/angular/src/switch/switch.component.ts
/**
 * Switch — Angular 18 standalone toggle with `role="switch"` semantics.
 *
 * Two-way bind via `[(checked)]`:
 *   <sui-switch [(checked)]="enabled" aria-label="Notifications" />
 *
 * Mirrors React/Vue: `checked` is the source of truth, click and Enter/Space
 * fire `(checkedChange)`. An `aria-label` is required when no visible label
 * is rendered alongside the switch.
 */
import {
  ChangeDetectionStrategy,
  Component,
  HostListener,
  Input,
  computed,
  model,
  signal,
} from "@angular/core";

export type SwitchColor = "neutral" | "primary" | "success" | "error" | "warning" | "info";
export type SwitchSize = "sm" | "md" | "lg";

@Component({
  selector: "sui-switch",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <button
      type="button"
      role="switch"
      [class]="rootClasses()"
      [attr.aria-checked]="checked()"
      [attr.aria-label]="ariaLabel() || null"
      [attr.aria-disabled]="disabled() || null"
      [disabled]="disabled()"
      [attr.tabindex]="disabled() ? -1 : null"
      (click)="toggle()"
    >
      <span class="sisyphos-switch-toggle" aria-hidden="true"></span>
    </button>
  `,
})
export class Switch {
  readonly checked = model<boolean>(false);

  private readonly _color = signal<SwitchColor>("primary");
  private readonly _size = signal<SwitchSize>("md");
  private readonly _disabled = signal(false);
  private readonly _ariaLabel = signal<string | undefined>(undefined);

  readonly disabled = this._disabled.asReadonly();
  readonly ariaLabel = this._ariaLabel.asReadonly();

  @Input("color") set colorInput(v: SwitchColor) {
    this._color.set(v);
  }
  @Input("size") set sizeInput(v: SwitchSize) {
    this._size.set(v);
  }
  @Input("disabled") set disabledInput(v: boolean) {
    this._disabled.set(v);
  }
  @Input("aria-label") set ariaLabelInput(v: string | undefined) {
    this._ariaLabel.set(v);
  }

  readonly rootClasses = computed(() =>
    [
      "sisyphos-switch",
      this._color(),
      this._size(),
      this.checked() ? "checked" : "unchecked",
      this._disabled() && "disabled",
    ]
      .filter(Boolean)
      .join(" ")
  );

  toggle(): void {
    if (this._disabled()) return;
    this.checked.set(!this.checked());
  }

  @HostListener("keydown", ["$event"])
  handleKeydown(event: KeyboardEvent): void {
    if (event.key === " " || event.key === "Enter") {
      event.preventDefault();
      this.toggle();
    }
  }
}
