// apps/preview-angular/src/demos/accordion-default.component.ts
import { ChangeDetectionStrategy, Component } from "@angular/core";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@sisyphos-ui/angular";

@Component({
  standalone: true,
  selector: "demo-accordion-default",
  imports: [Accordion, AccordionItem, AccordionTrigger, AccordionContent],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <sui-accordion defaultValue="install">
      <sui-accordion-item value="install">
        <sui-accordion-trigger>How do I install it?</sui-accordion-trigger>
        <sui-accordion-content>
          <code>pnpm add &#64;sisyphos-ui/angular</code> and import the stylesheet once.
        </sui-accordion-content>
      </sui-accordion-item>
      <sui-accordion-item value="theme">
        <sui-accordion-trigger>Can I theme it?</sui-accordion-trigger>
        <sui-accordion-content>Yes — every token is a CSS variable.</sui-accordion-content>
      </sui-accordion-item>
      <sui-accordion-item value="a11y">
        <sui-accordion-trigger>Is it accessible?</sui-accordion-trigger>
        <sui-accordion-content>Every component targets WAI-ARIA practices.</sui-accordion-content>
      </sui-accordion-item>
    </sui-accordion>
  `,
})
export class AccordionDefaultDemo {}

// apps/preview-vue/src/demos/accordion-default.vue
<script setup lang="ts">
import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from "@sisyphos-ui/vue";
</script>

<template>
  <Accordion defaultValue="install">
    <AccordionItem value="install">
      <AccordionTrigger>How do I install it?</AccordionTrigger>
      <AccordionContent>
        <code>pnpm add @sisyphos-ui/vue</code> and import the stylesheet once.
      </AccordionContent>
    </AccordionItem>
    <AccordionItem value="theme">
      <AccordionTrigger>Can I theme it?</AccordionTrigger>
      <AccordionContent>Yes — every token is a CSS variable.</AccordionContent>
    </AccordionItem>
    <AccordionItem value="a11y">
      <AccordionTrigger>Is it accessible?</AccordionTrigger>
      <AccordionContent>Every component targets WAI-ARIA practices.</AccordionContent>
    </AccordionItem>
  </Accordion>
</template>
