// apps/preview-angular/src/demos/button-variants.component.ts
import { ChangeDetectionStrategy, Component } from "@angular/core";
import { Button } from "@sisyphos-ui/angular";

@Component({
  standalone: true,
  selector: "demo-button-variants",
  imports: [Button],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div style="display:flex;gap:12px;flex-wrap:wrap">
      <sui-button variant="contained">contained</sui-button>
      <sui-button variant="outlined">outlined</sui-button>
      <sui-button variant="soft">soft</sui-button>
      <sui-button variant="text">text</sui-button>
    </div>
  `,
})
export class ButtonVariantsDemo {}

// apps/preview-vue/src/demos/button-variants.vue
<script setup lang="ts">
import { Button } from "@sisyphos-ui/vue";
</script>

<template>
  <div style="display: flex; gap: 12px; flex-wrap: wrap;">
    <Button variant="contained">contained</Button>
    <Button variant="outlined">outlined</Button>
    <Button variant="soft">soft</Button>
    <Button variant="text">text</Button>
  </div>
</template>
