// apps/preview-angular/src/demos/card-default.component.ts
import { ChangeDetectionStrategy, Component } from "@angular/core";
import { Card, CardBody, CardFooter, CardHeader } from "@sisyphos-ui/angular";

@Component({
  standalone: true,
  selector: "demo-card-default",
  imports: [Card, CardHeader, CardBody, CardFooter],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <sui-card style="max-width:360px">
      <sui-card-header>Profile</sui-card-header>
      <sui-card-body>Welcome back, Volkan.</sui-card-body>
      <sui-card-footer>Updated 5 minutes ago</sui-card-footer>
    </sui-card>
  `,
})
export class CardDefaultDemo {}

// apps/preview-vue/src/demos/card-default.vue
<script setup lang="ts">
import { Card, CardHeader, CardBody, CardFooter } from "@sisyphos-ui/vue";
</script>

<template>
  <Card style="max-width: 360px;">
    <CardHeader>Profile</CardHeader>
    <CardBody>Welcome back, Volkan.</CardBody>
    <CardFooter>Updated 5 minutes ago</CardFooter>
  </Card>
</template>
