// apps/preview-angular/src/demos/file-upload-default.component.ts
import { ChangeDetectionStrategy, Component } from "@angular/core";
import { FileUpload } from "@sisyphos-ui/angular";

@Component({
  standalone: true,
  selector: "demo-file-upload-default",
  imports: [FileUpload],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <sui-file-upload
      label="Profile photo"
      accept="image/*"
      [maxSize]="2 * 1024 * 1024"
    />
  `,
})
export class FileUploadDefaultDemo {}

// apps/preview-vue/src/demos/file-upload-default.vue
<script setup lang="ts">
import { ref } from "vue";
import { FileUpload } from "@sisyphos-ui/vue";
import type { UploadedFile } from "@sisyphos-ui/vue";

const files = ref<UploadedFile[]>([]);
</script>

<template>
  <FileUpload
    v-model="files"
    label="Profile photo"
    accept="image/*"
    :maxSize="2 * 1024 * 1024"
  />
</template>
