// apps/preview-angular/src/demos/spinner-default.component.ts
import { ChangeDetectionStrategy, Component } from "@angular/core";
import { Spinner } from "@sisyphos-ui/angular";

@Component({
  standalone: true,
  selector: "demo-spinner-default",
  imports: [Spinner],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div style="display:flex;gap:16px;align-items:center">
      <sui-spinner size="sm" color="primary" />
      <sui-spinner size="md" color="info" />
      <sui-spinner variant="double" color="success" size="lg" />
    </div>
  `,
})
export class SpinnerDefaultDemo {}

// apps/preview-vue/src/demos/spinner-default.vue
<script setup lang="ts">
import { Spinner } from "@sisyphos-ui/vue";
</script>

<template>
  <div style="display: flex; gap: 16px; align-items: center;">
    <Spinner size="sm" color="primary" />
    <Spinner size="md" color="info" />
    <Spinner variant="double" color="success" size="lg" />
  </div>
</template>
