// apps/preview-angular/src/demos/tabs-default.component.ts
import { ChangeDetectionStrategy, Component, signal } from "@angular/core";
import { Tabs, TabsList, TabsPanel, TabsTrigger } from "@sisyphos-ui/angular";

@Component({
  standalone: true,
  selector: "demo-tabs-default",
  imports: [Tabs, TabsList, TabsTrigger, TabsPanel],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <sui-tabs [(value)]="tab" variant="pill">
      <sui-tabs-list>
        <sui-tabs-trigger value="overview">Overview</sui-tabs-trigger>
        <sui-tabs-trigger value="activity">Activity</sui-tabs-trigger>
        <sui-tabs-trigger value="settings">Settings</sui-tabs-trigger>
      </sui-tabs-list>
      <sui-tabs-panel value="overview">Overview content.</sui-tabs-panel>
      <sui-tabs-panel value="activity">Activity content.</sui-tabs-panel>
      <sui-tabs-panel value="settings">Settings content.</sui-tabs-panel>
    </sui-tabs>
  `,
})
export class TabsDefaultDemo {
  protected readonly tab = signal("overview");
}

// apps/preview-vue/src/demos/tabs-default.vue
<script setup lang="ts">
import { ref } from "vue";
import { Tabs, TabsList, TabsTrigger, TabsPanel } from "@sisyphos-ui/vue";

const tab = ref("overview");
</script>

<template>
  <Tabs v-model:value="tab" variant="pill">
    <TabsList>
      <TabsTrigger value="overview">Overview</TabsTrigger>
      <TabsTrigger value="activity">Activity</TabsTrigger>
      <TabsTrigger value="settings">Settings</TabsTrigger>
    </TabsList>
    <TabsPanel value="overview">Overview content.</TabsPanel>
    <TabsPanel value="activity">Activity content.</TabsPanel>
    <TabsPanel value="settings">Settings content.</TabsPanel>
  </Tabs>
</template>
