// packages/vue/src/popover/Popover.vue
<script setup lang="ts">
/**
 * Popover — Vue 3 binding. Click-toggle (or hover) panel mounted via
 * `<Teleport>` with auto-flip placement. Use `Tooltip` for short hints
 * and `Popover` for richer interactive content.
 */
import { computePosition, type Placement } from "@sisyphos-ui/core/internal";
import { computed, nextTick, onBeforeUnmount, ref, useId, watch } from "vue";
import { useEscapeKey, useOutsideClick } from "../composables";

interface Props {
  placement?: Placement;
  offset?: number;
  /** `"click"` | `"hover"` | `"manual"`. */
  trigger?: "click" | "hover" | "manual";
  openDelay?: number;
  closeDelay?: number;
  arrow?: boolean;
  open?: boolean;
  closeOnEscape?: boolean;
  closeOnOutsideClick?: boolean;
  disabled?: boolean;
}

const props = withDefaults(defineProps<Props>(), {
  placement: "bottom",
  offset: 8,
  trigger: "click",
  openDelay: 100,
  closeDelay: 100,
  arrow: false,
  closeOnEscape: true,
  closeOnOutsideClick: true,
  disabled: false,
});

const emit = defineEmits<{
  (e: "update:open", value: boolean): void;
}>();

const popoverId = `sisyphos-popover-${useId()}`;
const anchorWrapperRef = ref<HTMLElement | null>(null);
const popoverRef = ref<HTMLDivElement | null>(null);

const internalOpen = ref(false);
const isControlled = computed(() => props.open !== undefined);
const isOpen = computed(() => (isControlled.value ? props.open! : internalOpen.value));

const visible = computed(() => isOpen.value && !props.disabled);
const pos = ref<{ left: number; top: number; placement: Placement } | null>(null);

let openTimer: ReturnType<typeof setTimeout> | null = null;
let closeTimer: ReturnType<typeof setTimeout> | null = null;
function clearTimers() {
  if (openTimer) clearTimeout(openTimer);
  if (closeTimer) clearTimeout(closeTimer);
  openTimer = null;
  closeTimer = null;
}

function setOpen(next: boolean) {
  if (!isControlled.value) internalOpen.value = next;
  emit("update:open", next);
}

function toggle() {
  if (props.disabled) return;
  setOpen(!isOpen.value);
}

function show() {
  clearTimers();
  if (props.disabled) return;
  openTimer = setTimeout(() => setOpen(true), props.openDelay);
}
function hide() {
  clearTimers();
  closeTimer = setTimeout(() => setOpen(false), props.closeDelay);
}

useEscapeKey(
  () => {
    if (props.closeOnEscape) setOpen(false);
  },
  visible
);
useOutsideClick(
  [anchorWrapperRef, popoverRef],
  () => {
    if (props.closeOnOutsideClick) setOpen(false);
  },
  visible
);

async function updatePosition() {
  if (!visible.value) return;
  await nextTick();
  const anchor = anchorWrapperRef.value?.firstElementChild as HTMLElement | null;
  const popover = popoverRef.value;
  if (!anchor || !popover) return;
  const rect = anchor.getBoundingClientRect();
  pos.value = computePosition(
    rect,
    { width: popover.offsetWidth, height: popover.offsetHeight },
    props.placement,
    props.offset
  );
}

watch(visible, (v) => {
  if (v) updatePosition();
  else pos.value = null;
});

watch(() => [props.placement, props.offset] as const, () => visible.value && updatePosition());

function onWindowChange() {
  if (visible.value) updatePosition();
}

if (typeof window !== "undefined") {
  window.addEventListener("scroll", onWindowChange, true);
  window.addEventListener("resize", onWindowChange);
  onBeforeUnmount(() => {
    window.removeEventListener("scroll", onWindowChange, true);
    window.removeEventListener("resize", onWindowChange);
    clearTimers();
  });
}

const popoverStyle = computed(() => ({
  position: "fixed" as const,
  left: `${pos.value?.left ?? 0}px`,
  top: `${pos.value?.top ?? 0}px`,
  opacity: pos.value ? 1 : 0,
}));

const popoverClasses = computed(() => [
  "sisyphos-popover",
  pos.value?.placement ?? props.placement,
]);

function onAnchorClick() {
  if (props.trigger === "click") toggle();
}
function onAnchorEnter() {
  if (props.trigger === "hover") show();
}
function onAnchorLeave() {
  if (props.trigger === "hover") hide();
}
</script>

<template>
  <span
    ref="anchorWrapperRef"
    class="sisyphos-popover-anchor"
    :aria-haspopup="trigger === 'click' ? 'dialog' : undefined"
    :aria-expanded="isOpen || undefined"
    :aria-controls="visible ? popoverId : undefined"
    @click="onAnchorClick"
    @mouseenter="onAnchorEnter"
    @mouseleave="onAnchorLeave"
  >
    <slot />
  </span>
  <Teleport to="body">
    <div
      v-if="visible"
      ref="popoverRef"
      :id="popoverId"
      role="dialog"
      :class="popoverClasses"
      :style="popoverStyle"
    >
      <slot name="content" />
      <span v-if="arrow" class="sisyphos-popover-arrow" aria-hidden="true" />
    </div>
  </Teleport>
</template>

<style src="./Popover.scss"></style>

// packages/react/src/popover/Popover.tsx
/**
 * Popover — interactive floating panel anchored to a trigger element.
 *
 * Portal-mounted with auto-flip placement. Closes on outside click and Escape
 * by default. Works controlled (`open`) or uncontrolled (`defaultOpen`). Wraps
 * a single focusable child as the trigger; use `Tooltip` for read-only hints.
 */
import type React from "react";
import {
  cloneElement,
  isValidElement,
  useCallback,
  useEffect,
  useId,
  useMemo,
  useRef,
  useState,
  type ReactElement,
} from "react";
import { Portal } from "../internal/portal";
import { cx, computePosition, useEscapeKey, type Placement } from "@sisyphos-ui/core/internal";
import "./Popover.scss";

export interface PopoverProps {
  /** Floating content rendered inside the popover. */
  content: React.ReactNode;
  /** Preferred placement; auto-flips to the opposite side if it doesn't fit. */
  placement?: Placement;
  /** Pixel gap between trigger and popover. Defaults to 8. */
  offset?: number;
  /** Interaction that opens the popover. `manual` only opens via the `open` prop. */
  trigger?: "click" | "hover" | "manual";
  /** Delay before opening on the hover trigger. */
  openDelay?: number;
  /** Delay before closing on the hover trigger. */
  closeDelay?: number;
  /** Render an arrow pointing at the trigger. */
  arrow?: boolean;
  /** Open state (controlled). */
  open?: boolean;
  /** Initial open state (uncontrolled). */
  defaultOpen?: boolean;
  /** Called whenever the open state changes. */
  onOpenChange?: (open: boolean) => void;
  /** Close when Escape is pressed. Default `true`. */
  closeOnEscape?: boolean;
  /** Close when a click occurs outside the trigger and panel. Default `true`. */
  closeOnOutsideClick?: boolean;
  disabled?: boolean;
  className?: string;
  /** Single focusable React element used as the trigger. */
  children: ReactElement;
}

export const Popover: React.FC<PopoverProps> = ({
  content,
  placement = "bottom",
  offset = 8,
  trigger = "click",
  openDelay = 100,
  closeDelay = 150,
  arrow = true,
  open: openProp,
  defaultOpen = false,
  onOpenChange,
  closeOnEscape = true,
  closeOnOutsideClick = true,
  disabled = false,
  className,
  children,
}) => {
  const reactId = useId();
  const popoverId = `sisyphos-popover-${reactId}`;
  const anchorRef = useRef<HTMLElement | null>(null);
  const floatingRef = useRef<HTMLDivElement | null>(null);
  const timerRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  const isControlled = openProp !== undefined;
  const [internalOpen, setInternalOpen] = useState(defaultOpen);
  const open = (isControlled ? openProp : internalOpen) && !disabled;

  const [pos, setPos] = useState<{ left: number; top: number; placement: Placement } | null>(null);

  const setOpen = useCallback(
    (next: boolean) => {
      if (!isControlled) setInternalOpen(next);
      onOpenChange?.(next);
    },
    [isControlled, onOpenChange]
  );

  const clearTimer = () => {
    if (timerRef.current) clearTimeout(timerRef.current);
    timerRef.current = null;
  };
  const schedule = useCallback(
    (next: boolean, delay: number) => {
      clearTimer();
      timerRef.current = setTimeout(() => setOpen(next), delay);
    },
    [setOpen]
  );

  useEffect(() => () => clearTimer(), []);

  useEscapeKey(() => setOpen(false), open && closeOnEscape);

  useEffect(() => {
    if (!open || !closeOnOutsideClick) return;
    const handler = (e: MouseEvent) => {
      const tgt = e.target as Node;
      if (anchorRef.current?.contains(tgt)) return;
      if (floatingRef.current?.contains(tgt)) return;
      setOpen(false);
    };
    document.addEventListener("mousedown", handler);
    return () => document.removeEventListener("mousedown", handler);
  }, [open, closeOnOutsideClick, setOpen]);

  useEffect(() => {
    if (!open) {
      setPos(null);
      return;
    }
    let raf = 0;
    const update = () => {
      const anchor = anchorRef.current;
      const tooltip = floatingRef.current;
      if (!anchor || !tooltip) return;
      const a = anchor.getBoundingClientRect();
      const p = computePosition(
        a,
        { width: tooltip.offsetWidth, height: tooltip.offsetHeight },
        placement,
        offset
      );
      setPos(p);
    };
    raf = requestAnimationFrame(() => requestAnimationFrame(update));
    const onWin = () => update();
    window.addEventListener("scroll", onWin, true);
    window.addEventListener("resize", onWin);
    return () => {
      cancelAnimationFrame(raf);
      window.removeEventListener("scroll", onWin, true);
      window.removeEventListener("resize", onWin);
    };
  }, [open, placement, offset, content]);

  if (!isValidElement(children)) {
    throw new Error("[@sisyphos-ui/popover] <Popover> expects a single React element as child.");
  }

  const childProps = children.props as Record<string, unknown>;

  const triggerHandlers = useMemo(() => {
    const handlers: Record<string, unknown> = {};
    if (trigger === "click") {
      handlers.onClick = (e: React.MouseEvent) => {
        (childProps.onClick as ((e: React.MouseEvent) => void) | undefined)?.(e);
        setOpen(!open);
      };
    } else if (trigger === "hover") {
      handlers.onMouseEnter = (e: React.MouseEvent) => {
        (childProps.onMouseEnter as ((e: React.MouseEvent) => void) | undefined)?.(e);
        schedule(true, openDelay);
      };
      handlers.onMouseLeave = (e: React.MouseEvent) => {
        (childProps.onMouseLeave as ((e: React.MouseEvent) => void) | undefined)?.(e);
        schedule(false, closeDelay);
      };
      handlers.onFocus = (e: React.FocusEvent) => {
        (childProps.onFocus as ((e: React.FocusEvent) => void) | undefined)?.(e);
        schedule(true, openDelay);
      };
      handlers.onBlur = (e: React.FocusEvent) => {
        (childProps.onBlur as ((e: React.FocusEvent) => void) | undefined)?.(e);
        schedule(false, closeDelay);
      };
    }
    return handlers;
  }, [trigger, childProps, open, setOpen, schedule, openDelay, closeDelay]);

  const merged = cloneElement(children as ReactElement<Record<string, unknown>>, {
    ref: (node: HTMLElement) => {
      anchorRef.current = node;
      const orig = (children as unknown as { ref?: React.Ref<HTMLElement> }).ref;
      if (typeof orig === "function") orig(node);
      else if (orig && typeof orig === "object") {
        (orig as React.MutableRefObject<HTMLElement | null>).current = node;
      }
    },
    "aria-expanded": open || undefined,
    "aria-controls": open ? popoverId : undefined,
    "aria-haspopup": "dialog",
    ...triggerHandlers,
  });

  return (
    <>
      {merged}
      {open && (
        <Portal>
          <div
            ref={floatingRef}
            id={popoverId}
            role="dialog"
            className={cx("sisyphos-popover", pos?.placement ?? placement, className)}
            style={{
              position: "fixed",
              left: pos?.left ?? 0,
              top: pos?.top ?? 0,
              opacity: pos ? 1 : 0,
            }}
            onMouseEnter={trigger === "hover" ? () => clearTimer() : undefined}
            onMouseLeave={trigger === "hover" ? () => schedule(false, closeDelay) : undefined}
          >
            {content}
            {arrow && <span className="sisyphos-popover-arrow" aria-hidden="true" />}
          </div>
        </Portal>
      )}
    </>
  );
};
