// packages/angular/src/datepicker/datepicker.component.ts
/**
 * DatePicker — Angular 18 standalone single-date or range picker with
 * optional time, min/max constraints, day/month/year views, and localized
 * weekday/month names. Mirrors the React/Vue versions feature-for-feature.
 *
 * Use `[isRange]="true"` to switch to range mode; bind via `[(value)]` for
 * single (Date | null) or `[(values)]` for range ([Date | null, Date | null]).
 */
import type { ElementRef, OnDestroy } from "@angular/core";
import {
  ChangeDetectionStrategy,
  Component,
  EventEmitter,
  HostListener,
  Input as NgInput,
  Output,
  ViewChild,
  computed,
  effect,
  signal,
} from "@angular/core";
import { computePosition, type Placement } from "@sisyphos-ui/core/internal";
import { formatDate, sameDay, withTime } from "./format";
import { MONTHS, PLACEHOLDERS, RANGE_LABELS, WEEK_DAYS, type DateLocale } from "./locale";

type ViewMode = "days" | "months" | "years";

let dpCounter = 0;

function buildCalendar(month: Date, locale: DateLocale): Date[] {
  const year = month.getFullYear();
  const m = month.getMonth();
  const firstDay = new Date(year, m, 1);
  const lastDay = new Date(year, m + 1, 0);
  const dayOfWeek = locale === "tr" ? (firstDay.getDay() + 6) % 7 : firstDay.getDay();
  const days: Date[] = [];
  for (let i = dayOfWeek - 1; i >= 0; i--) days.push(new Date(year, m, -i));
  for (let d = 1; d <= lastDay.getDate(); d++) days.push(new Date(year, m, d));
  const remaining = 7 - (days.length % 7);
  if (remaining < 7) for (let i = 1; i <= remaining; i++) days.push(new Date(year, m + 1, i));
  return days;
}

@Component({
  selector: "sui-datepicker",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div [class]="rootClasses()">
      @if (label()) {
        <label [for]="fieldId" [class]="labelClasses()">{{ label() }}</label>
      }
      <div #trigger [class]="triggerClasses()" (click)="openPicker()">
        <span class="sisyphos-datepicker-start-icon" aria-hidden="true">
          <svg
            viewBox="0 0 24 24"
            width="20"
            height="20"
            fill="none"
            stroke="currentColor"
            stroke-width="1.5"
            stroke-linecap="round"
            stroke-linejoin="round"
            aria-hidden="true"
          >
            <rect x="3" y="4" width="18" height="18" rx="2" />
            <line x1="16" y1="2" x2="16" y2="6" />
            <line x1="8" y1="2" x2="8" y2="6" />
            <line x1="3" y1="10" x2="21" y2="10" />
          </svg>
        </span>
        <input
          [id]="fieldId"
          class="sisyphos-datepicker-input"
          type="text"
          readonly
          [disabled]="disabled()"
          [value]="displayValue()"
          [placeholder]="placeholder() || PLACEHOLDERS[locale()]"
          [attr.aria-invalid]="error() || null"
          aria-haspopup="dialog"
          [attr.aria-expanded]="isOpen()"
        />
        <div class="sisyphos-datepicker-end-icons">
          @if (allowClear() && hasValue() && !disabled()) {
            <button
              type="button"
              class="sisyphos-datepicker-clear"
              aria-label="Clear date"
              (click)="onClear($event)"
            >
              <svg viewBox="0 0 24 24" width="14" height="14" aria-hidden="true">
                <path
                  d="M19 6.41 17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12z"
                  fill="currentColor"
                />
              </svg>
            </button>
          }
          <span class="sisyphos-datepicker-chevron" aria-hidden="true">
            <svg
              viewBox="0 0 24 24"
              width="16"
              height="16"
              aria-hidden="true"
              [style.transform]="isOpen() ? 'rotate(180deg)' : null"
            >
              <path d="M7 10l5 5 5-5z" fill="currentColor" />
            </svg>
          </span>
        </div>
      </div>

      @if (isOpen()) {
        <div
          #dropdown
          role="dialog"
          [attr.aria-label]="label() ?? 'Date picker'"
          class="sisyphos-datepicker-dropdown"
          [style.position]="'fixed'"
          [style.left.px]="pos()?.left ?? 0"
          [style.top.px]="pos()?.top ?? 0"
          [style.min-width.px]="pos()?.width ?? 0"
          [style.opacity]="pos() ? 1 : 0"
          [style.z-index]="1100"
        >
          <div class="sisyphos-datepicker-header">
            <button
              type="button"
              class="sisyphos-datepicker-nav"
              aria-label="Previous"
              (click)="navPrev()"
            >
              ‹
            </button>
            <button
              type="button"
              class="sisyphos-datepicker-header-title"
              (click)="cycleViewMode()"
            >
              @switch (viewMode()) {
                @case ("days") {
                  {{ MONTHS[locale()][cursor().getMonth()] }} {{ cursor().getFullYear() }}
                }
                @case ("months") {
                  {{ cursor().getFullYear() }}
                }
                @case ("years") {
                  {{ years()[0] }} - {{ years()[9] }}
                }
              }
            </button>
            <button
              type="button"
              class="sisyphos-datepicker-nav"
              aria-label="Next"
              (click)="navNext()"
            >
              ›
            </button>
          </div>

          @if (viewMode() === "days") {
            <div class="sisyphos-datepicker-weekdays">
              @for (d of WEEK_DAYS[locale()]; track d) {
                <div class="sisyphos-datepicker-weekday">{{ d }}</div>
              }
            </div>
            <div class="sisyphos-datepicker-days">
              @for (d of calendarDays(); track $index) {
                <button
                  type="button"
                  [class]="dayClasses(d)"
                  [disabled]="isDateDisabled(d) || d.getMonth() !== cursor().getMonth()"
                  [attr.aria-selected]="isSelected(d) || null"
                  (click)="onDaySelect(d)"
                >
                  {{ d.getDate() }}
                </button>
              }
            </div>
          } @else if (viewMode() === "months") {
            <div class="sisyphos-datepicker-months">
              @for (m of MONTHS[locale()]; track m; let idx = $index) {
                <button
                  type="button"
                  [class]="
                    'sisyphos-datepicker-month' + (idx === cursor().getMonth() ? ' selected' : '')
                  "
                  (click)="selectMonth(idx)"
                >
                  {{ m }}
                </button>
              }
            </div>
          } @else {
            <div class="sisyphos-datepicker-years">
              @for (y of years(); track y) {
                <button
                  type="button"
                  [class]="
                    'sisyphos-datepicker-year' + (y === cursor().getFullYear() ? ' selected' : '')
                  "
                  (click)="selectYear(y)"
                >
                  {{ y }}
                </button>
              }
            </div>
          }

          @if (showTime()) {
            <div [class]="'sisyphos-datepicker-time' + (isRange() ? ' range' : '')">
              @if (isRange()) {
                <div class="sisyphos-datepicker-time-group">
                  <div class="sisyphos-datepicker-time-label">
                    {{ RANGE_LABELS[locale()].start }}
                  </div>
                  <div class="sisyphos-datepicker-time-row">
                    <select
                      [attr.aria-label]="RANGE_LABELS[locale()].start + ' hour'"
                      [disabled]="!rangeAt(0)"
                      [value]="rangeAt(0)?.getHours() ?? 0"
                      (change)="changeTime('start', 'hour', $event)"
                    >
                      @for (h of HOURS; track h) {
                        <option [value]="h">{{ pad(h) }}</option>
                      }
                    </select>
                    :
                    <select
                      [attr.aria-label]="RANGE_LABELS[locale()].start + ' minute'"
                      [disabled]="!rangeAt(0)"
                      [value]="rangeAt(0)?.getMinutes() ?? 0"
                      (change)="changeTime('start', 'minute', $event)"
                    >
                      @for (m of minuteOptions(); track m) {
                        <option [value]="m">{{ pad(m) }}</option>
                      }
                    </select>
                  </div>
                </div>
                <div class="sisyphos-datepicker-time-group">
                  <div class="sisyphos-datepicker-time-label">{{ RANGE_LABELS[locale()].end }}</div>
                  <div class="sisyphos-datepicker-time-row">
                    <select
                      [attr.aria-label]="RANGE_LABELS[locale()].end + ' hour'"
                      [disabled]="!rangeAt(1)"
                      [value]="rangeAt(1)?.getHours() ?? 0"
                      (change)="changeTime('end', 'hour', $event)"
                    >
                      @for (h of HOURS; track h) {
                        <option [value]="h">{{ pad(h) }}</option>
                      }
                    </select>
                    :
                    <select
                      [attr.aria-label]="RANGE_LABELS[locale()].end + ' minute'"
                      [disabled]="!rangeAt(1)"
                      [value]="rangeAt(1)?.getMinutes() ?? 0"
                      (change)="changeTime('end', 'minute', $event)"
                    >
                      @for (m of minuteOptions(); track m) {
                        <option [value]="m">{{ pad(m) }}</option>
                      }
                    </select>
                  </div>
                </div>
              } @else {
                <div class="sisyphos-datepicker-time-row">
                  <select
                    aria-label="Hour"
                    [disabled]="!singleValue()"
                    [value]="singleValue()?.getHours() ?? 0"
                    (change)="changeTime('single', 'hour', $event)"
                  >
                    @for (h of HOURS; track h) {
                      <option [value]="h">{{ pad(h) }}</option>
                    }
                  </select>
                  :
                  <select
                    aria-label="Minute"
                    [disabled]="!singleValue()"
                    [value]="singleValue()?.getMinutes() ?? 0"
                    (change)="changeTime('single', 'minute', $event)"
                  >
                    @for (m of minuteOptions(); track m) {
                      <option [value]="m">{{ pad(m) }}</option>
                    }
                  </select>
                </div>
              }
            </div>
          }
        </div>
      }

      @if (error() && errorMessage()) {
        <span class="sisyphos-datepicker-error" role="alert">{{ errorMessage() }}</span>
      }
    </div>
  `,
})
export class DatePicker implements OnDestroy {
  readonly fieldId = `sisyphos-datepicker-${++dpCounter}`;
  protected readonly MONTHS = MONTHS;
  protected readonly WEEK_DAYS = WEEK_DAYS;
  protected readonly PLACEHOLDERS = PLACEHOLDERS;
  protected readonly RANGE_LABELS = RANGE_LABELS;
  protected readonly HOURS = Array.from({ length: 24 }, (_, i) => i);
  protected readonly pad = (n: number) => String(n).padStart(2, "0");

  // ── inputs ────────────────────────────────────────────────────────────
  private readonly _label = signal<string | undefined>(undefined);
  private readonly _placeholder = signal<string | undefined>(undefined);
  private readonly _disabled = signal(false);
  private readonly _readOnly = signal(false);
  private readonly _required = signal(false);
  private readonly _error = signal(false);
  private readonly _errorMessage = signal<string | undefined>(undefined);
  private readonly _variant = signal<"standard" | "outlined">("outlined");
  private readonly _size = signal<"sm" | "md" | "lg">("md");
  private readonly _minDate = signal<Date | undefined>(undefined);
  private readonly _maxDate = signal<Date | undefined>(undefined);
  private readonly _format = signal<string | undefined>(undefined);
  private readonly _locale = signal<DateLocale>("tr");
  private readonly _showTime = signal(false);
  private readonly _minuteStep = signal(15);
  private readonly _defaultHour = signal(0);
  private readonly _defaultMinute = signal(0);
  private readonly _defaultStartHour = signal<number | undefined>(undefined);
  private readonly _defaultStartMinute = signal<number | undefined>(undefined);
  private readonly _defaultEndHour = signal<number | undefined>(undefined);
  private readonly _defaultEndMinute = signal<number | undefined>(undefined);
  private readonly _allowClear = signal(false);
  private readonly _fullWidth = signal(false);
  private readonly _placement = signal<Placement>("bottom-start");
  private readonly _isRange = signal(false);
  private readonly _value = signal<Date | null>(null);
  private readonly _values = signal<[Date | null, Date | null]>([null, null]);

  // ── internal state ───────────────────────────────────────────────────
  private readonly _isOpen = signal(false);
  private readonly _viewMode = signal<ViewMode>("days");
  private readonly _cursor = signal<Date>(new Date());
  protected readonly pos = signal<{
    left: number;
    top: number;
    placement: Placement;
    width: number;
  } | null>(null);

  // ── public reads ─────────────────────────────────────────────────────
  readonly label = this._label.asReadonly();
  readonly placeholder = this._placeholder.asReadonly();
  readonly disabled = this._disabled.asReadonly();
  readonly error = this._error.asReadonly();
  readonly errorMessage = this._errorMessage.asReadonly();
  readonly locale = this._locale.asReadonly();
  readonly showTime = this._showTime.asReadonly();
  readonly allowClear = this._allowClear.asReadonly();
  readonly isRange = this._isRange.asReadonly();
  readonly isOpen = this._isOpen.asReadonly();
  readonly viewMode = this._viewMode.asReadonly();
  readonly cursor = this._cursor.asReadonly();
  readonly singleValue = this._value.asReadonly();
  readonly rangeValue = this._values.asReadonly();

  @NgInput("label") set labelInput(v: string | undefined) {
    this._label.set(v);
  }
  @NgInput("placeholder") set placeholderInput(v: string | undefined) {
    this._placeholder.set(v);
  }
  @NgInput("disabled") set disabledInput(v: boolean) {
    this._disabled.set(v);
  }
  @NgInput("readOnly") set readOnlyInput(v: boolean) {
    this._readOnly.set(v);
  }
  @NgInput("required") set requiredInput(v: boolean) {
    this._required.set(v);
  }
  @NgInput("error") set errorInput(v: boolean) {
    this._error.set(v);
  }
  @NgInput("errorMessage") set errorMessageInput(v: string | undefined) {
    this._errorMessage.set(v);
  }
  @NgInput("variant") set variantInput(v: "standard" | "outlined") {
    this._variant.set(v);
  }
  @NgInput("size") set sizeInput(v: "sm" | "md" | "lg") {
    this._size.set(v);
  }
  @NgInput("minDate") set minDateInput(v: Date | undefined) {
    this._minDate.set(v);
  }
  @NgInput("maxDate") set maxDateInput(v: Date | undefined) {
    this._maxDate.set(v);
  }
  @NgInput("format") set formatInput(v: string | undefined) {
    this._format.set(v);
  }
  @NgInput("locale") set localeInput(v: DateLocale) {
    this._locale.set(v);
  }
  @NgInput("showTime") set showTimeInput(v: boolean) {
    this._showTime.set(v);
  }
  @NgInput("minuteStep") set minuteStepInput(v: number) {
    this._minuteStep.set(v);
  }
  @NgInput("defaultHour") set defaultHourInput(v: number) {
    this._defaultHour.set(v);
  }
  @NgInput("defaultMinute") set defaultMinuteInput(v: number) {
    this._defaultMinute.set(v);
  }
  @NgInput("defaultStartHour") set defaultStartHourInput(v: number | undefined) {
    this._defaultStartHour.set(v);
  }
  @NgInput("defaultStartMinute") set defaultStartMinuteInput(v: number | undefined) {
    this._defaultStartMinute.set(v);
  }
  @NgInput("defaultEndHour") set defaultEndHourInput(v: number | undefined) {
    this._defaultEndHour.set(v);
  }
  @NgInput("defaultEndMinute") set defaultEndMinuteInput(v: number | undefined) {
    this._defaultEndMinute.set(v);
  }
  @NgInput("allowClear") set allowClearInput(v: boolean) {
    this._allowClear.set(v);
  }
  @NgInput("fullWidth") set fullWidthInput(v: boolean) {
    this._fullWidth.set(v);
  }
  @NgInput("placement") set placementInput(v: Placement) {
    this._placement.set(v);
  }
  @NgInput("isRange") set isRangeInput(v: boolean) {
    this._isRange.set(v);
  }

  /** Single-mode value. */
  @NgInput("value") set valueInput(v: Date | null | undefined) {
    if (v !== undefined) {
      this._value.set(v);
      // Reset cursor to the picked month so opening the picker shows the right page.
      if (v && !this._isOpen()) this._cursor.set(new Date(v));
    }
  }
  /** Range-mode values (tuple). */
  @NgInput("values") set valuesInput(v: [Date | null, Date | null] | undefined) {
    if (v !== undefined) {
      this._values.set([v[0], v[1]]);
      if (v[0] && !this._isOpen()) this._cursor.set(new Date(v[0]));
    }
  }

  @Output() readonly valueChange = new EventEmitter<Date | null>();
  @Output() readonly valuesChange = new EventEmitter<[Date | null, Date | null]>();

  @ViewChild("trigger") triggerRef?: ElementRef<HTMLDivElement>;
  @ViewChild("dropdown") dropdownRef?: ElementRef<HTMLDivElement>;

  // ── computeds ────────────────────────────────────────────────────────
  readonly defaultFormat = computed(() => (this._showTime() ? "dd.MM.yyyy HH:mm" : "dd.MM.yyyy"));
  readonly fmt = computed(() => this._format() ?? this.defaultFormat());

  readonly displayValue = computed(() => {
    if (this._isRange()) {
      const [s, e] = this._values();
      if (s && e) return `${formatDate(s, this.fmt())} - ${formatDate(e, this.fmt())}`;
      if (s) return formatDate(s, this.fmt());
      return "";
    }
    return this._value() ? formatDate(this._value()!, this.fmt()) : "";
  });

  readonly hasValue = computed(() =>
    this._isRange() ? !!(this._values()[0] || this._values()[1]) : !!this._value()
  );

  readonly minuteOptions = computed(() => {
    const out: number[] = [];
    for (let m = 0; m < 60; m += this._minuteStep()) out.push(m);
    return out;
  });

  readonly decadeStart = computed(() => Math.floor(this._cursor().getFullYear() / 10) * 10);
  readonly years = computed(() => Array.from({ length: 10 }, (_, i) => this.decadeStart() + i));
  readonly calendarDays = computed(() => buildCalendar(this._cursor(), this._locale()));

  readonly rootClasses = computed(() =>
    [
      "sisyphos-datepicker",
      this._size(),
      this._variant(),
      this._error() && "error",
      this._disabled() && "disabled",
      this._fullWidth() && "full-width",
    ]
      .filter(Boolean)
      .join(" ")
  );

  readonly labelClasses = computed(() =>
    ["sisyphos-datepicker-label", this._error() && "error", this._required() && "required"]
      .filter(Boolean)
      .join(" ")
  );

  readonly triggerClasses = computed(() =>
    ["sisyphos-datepicker-trigger", this._isOpen() && "focused"].filter(Boolean).join(" ")
  );

  // ── lifecycle ────────────────────────────────────────────────────────
  private resizeListener?: () => void;
  private scrollListener?: () => void;

  constructor() {
    effect(() => {
      if (this._isOpen()) {
        queueMicrotask(() => requestAnimationFrame(() => this.reposition()));
        this.installScrollListeners();
      } else {
        this.pos.set(null);
        this._viewMode.set("days");
        this.removeScrollListeners();
      }
    });
  }

  ngOnDestroy(): void {
    this.removeScrollListeners();
  }

  // ── trigger ──────────────────────────────────────────────────────────
  openPicker(): void {
    if (this._disabled() || this._readOnly()) return;
    this._isOpen.set(!this._isOpen());
  }

  onClear(event: MouseEvent): void {
    event.stopPropagation();
    if (this._isRange()) {
      this._values.set([null, null]);
      this.valuesChange.emit([null, null]);
    } else {
      this._value.set(null);
      this.valueChange.emit(null);
    }
  }

  // ── helpers ──────────────────────────────────────────────────────────
  rangeAt(idx: number): Date | null {
    return this._values()[idx] ?? null;
  }

  isDateDisabled(date: Date): boolean {
    const min = this._minDate();
    const max = this._maxDate();
    if (min && date < min) return true;
    if (max && date > max) return true;
    return false;
  }

  isSelected(date: Date): boolean {
    if (this._isRange()) {
      const [s, e] = this._values();
      return Boolean((s && sameDay(date, s)) || (e && sameDay(date, e)));
    }
    return this._value() ? sameDay(date, this._value()!) : false;
  }

  isInRange(date: Date): boolean {
    if (!this._isRange()) return false;
    const [s, e] = this._values();
    if (!s || !e) return false;
    return date >= s && date <= e;
  }

  dayClasses(d: Date): string {
    const inOtherMonth = d.getMonth() !== this._cursor().getMonth();
    return [
      "sisyphos-datepicker-day",
      inOtherMonth && "other-month",
      sameDay(d, new Date()) && !this.hasValue() && "today",
      this.isSelected(d) && "selected",
      this.isInRange(d) && "in-range",
      (this.isDateDisabled(d) || inOtherMonth) && "disabled",
    ]
      .filter(Boolean)
      .join(" ");
  }

  private applyDefaultTime(d: Date, target: "single" | "start" | "end"): Date {
    if (!this._showTime()) return d;
    let h = this._defaultHour();
    let m = this._defaultMinute();
    if (target === "start") {
      h = this._defaultStartHour() ?? this._defaultHour();
      m = this._defaultStartMinute() ?? this._defaultMinute();
    } else if (target === "end") {
      h = this._defaultEndHour() ?? this._defaultHour();
      m = this._defaultEndMinute() ?? this._defaultMinute();
    }
    return withTime(d, h, m);
  }

  // ── selection ────────────────────────────────────────────────────────
  onDaySelect(d: Date): void {
    if (this.isDateDisabled(d) || d.getMonth() !== this._cursor().getMonth()) return;
    if (!this._isRange()) {
      const next =
        this._showTime() && this._value()
          ? withTime(d, this._value()!.getHours(), this._value()!.getMinutes())
          : this.applyDefaultTime(d, "single");
      this._value.set(next);
      this.valueChange.emit(next);
      if (!this._showTime()) this._isOpen.set(false);
      return;
    }
    const [s, e] = this._values();
    if (!s || (s && e)) {
      const next: [Date | null, Date | null] = [this.applyDefaultTime(d, "start"), null];
      this._values.set(next);
      this.valuesChange.emit(next);
    } else if (s && !e) {
      let next: [Date | null, Date | null];
      if (d >= s) {
        next = [s, this.applyDefaultTime(d, "end")];
      } else {
        // Earlier than the existing start — flip the range.
        next = [this.applyDefaultTime(d, "start"), s];
      }
      this._values.set(next);
      this.valuesChange.emit(next);
      if (!this._showTime()) this._isOpen.set(false);
    }
  }

  changeTime(target: "single" | "start" | "end", which: "hour" | "minute", event: Event): void {
    const val = Number((event.target as HTMLSelectElement).value);
    if (target === "single") {
      const v = this._value();
      if (!v) return;
      const h = which === "hour" ? val : v.getHours();
      const m = which === "minute" ? val : v.getMinutes();
      const next = withTime(v, h, m);
      this._value.set(next);
      this.valueChange.emit(next);
    } else if (target === "start") {
      const s = this._values()[0];
      if (!s) return;
      const h = which === "hour" ? val : s.getHours();
      const m = which === "minute" ? val : s.getMinutes();
      const next: [Date | null, Date | null] = [withTime(s, h, m), this._values()[1]];
      this._values.set(next);
      this.valuesChange.emit(next);
    } else {
      const e = this._values()[1];
      if (!e) return;
      const h = which === "hour" ? val : e.getHours();
      const m = which === "minute" ? val : e.getMinutes();
      const next: [Date | null, Date | null] = [this._values()[0], withTime(e, h, m)];
      this._values.set(next);
      this.valuesChange.emit(next);
    }
  }

  // ── view navigation ──────────────────────────────────────────────────
  navPrev(): void {
    const c = this._cursor();
    if (this._viewMode() === "days") this._cursor.set(new Date(c.getFullYear(), c.getMonth() - 1));
    else if (this._viewMode() === "months")
      this._cursor.set(new Date(c.getFullYear() - 1, c.getMonth()));
    else this._cursor.set(new Date(c.getFullYear() - 10, c.getMonth()));
  }

  navNext(): void {
    const c = this._cursor();
    if (this._viewMode() === "days") this._cursor.set(new Date(c.getFullYear(), c.getMonth() + 1));
    else if (this._viewMode() === "months")
      this._cursor.set(new Date(c.getFullYear() + 1, c.getMonth()));
    else this._cursor.set(new Date(c.getFullYear() + 10, c.getMonth()));
  }

  cycleViewMode(): void {
    if (this._viewMode() === "days") this._viewMode.set("months");
    else if (this._viewMode() === "months") this._viewMode.set("years");
  }

  selectMonth(idx: number): void {
    const c = this._cursor();
    this._cursor.set(new Date(c.getFullYear(), idx));
    this._viewMode.set("days");
  }

  selectYear(y: number): void {
    const c = this._cursor();
    this._cursor.set(new Date(y, c.getMonth()));
    this._viewMode.set("months");
  }

  // ── outside-click + escape ───────────────────────────────────────────
  @HostListener("document:keydown.escape")
  onEscape(): void {
    if (this._isOpen()) this._isOpen.set(false);
  }

  @HostListener("document:mousedown", ["$event"])
  onDocumentMousedown(event: MouseEvent): void {
    if (!this._isOpen()) return;
    const tgt = event.target as Node | null;
    if (this.triggerRef?.nativeElement.contains(tgt as Node)) return;
    if (this.dropdownRef?.nativeElement.contains(tgt as Node)) return;
    this._isOpen.set(false);
  }

  // ── positioning ──────────────────────────────────────────────────────
  private reposition(): void {
    const anchor = this.triggerRef?.nativeElement;
    const dropdown = this.dropdownRef?.nativeElement;
    if (!anchor || !dropdown) return;
    const a = anchor.getBoundingClientRect();
    const size = { width: dropdown.offsetWidth, height: dropdown.offsetHeight };
    const p = computePosition(a, size, this._placement(), 4);
    this.pos.set({ ...p, width: a.width });
  }

  private installScrollListeners(): void {
    this.scrollListener = () => this.reposition();
    this.resizeListener = () => this.reposition();
    window.addEventListener("scroll", this.scrollListener, true);
    window.addEventListener("resize", this.resizeListener);
  }

  private removeScrollListeners(): void {
    if (this.scrollListener) {
      window.removeEventListener("scroll", this.scrollListener, true);
      this.scrollListener = undefined;
    }
    if (this.resizeListener) {
      window.removeEventListener("resize", this.resizeListener);
      this.resizeListener = undefined;
    }
  }
}

// packages/react/src/datepicker/DatePicker.tsx
/**
 * DatePicker — single-date or range picker with optional time, `min`/`max`
 * constraints, day/month/year views, and localized weekday and month names.
 *
 * The calendar dropdown is portal-mounted with auto-flip placement. Set
 * `isRange` to switch between single-date and range modes.
 */
import type React from "react";
import { useCallback, useEffect, useId, useMemo, useRef, useState } from "react";
import { Portal } from "../internal/portal";
import { cx, computePosition, useEscapeKey, type Placement } from "@sisyphos-ui/core/internal";
import { WEEK_DAYS, MONTHS, PLACEHOLDERS, RANGE_LABELS, type DateLocale } from "./locale";
import { formatDate, sameDay, withTime } from "./format";
import "./DatePicker.scss";

type SingleValue = Date | null;
type RangeValue = [Date | null, Date | null];

type SingleProps = {
  isRange?: false;
  value?: SingleValue;
  onChange?: (value: SingleValue) => void;
};
type RangeProps = {
  isRange: true;
  value?: RangeValue;
  onChange?: (value: RangeValue) => void;
};

type ViewMode = "days" | "months" | "years";

export type DatePickerProps = {
  label?: string;
  placeholder?: string;
  disabled?: boolean;
  readOnly?: boolean;
  required?: boolean;
  error?: boolean;
  errorMessage?: string;
  variant?: "standard" | "outlined";
  size?: "sm" | "md" | "lg";
  minDate?: Date;
  maxDate?: Date;
  /** Format for the trigger input. Supports yyyy/MM/dd/HH/mm. Defaults to `dd.MM.yyyy` (or with time). */
  format?: string;
  locale?: DateLocale;
  showTime?: boolean;
  /** Minute increments in the time picker. Default 15. */
  minuteStep?: number;
  /**
   * Default hour applied when the user picks a date for the first time in
   * `showTime` mode. Avoids the "always lands on 00:00" footgun. Defaults to 0.
   */
  defaultHour?: number;
  /** Default minute applied alongside `defaultHour`. Defaults to 0. */
  defaultMinute?: number;
  /** Range mode: default hour for the start date. Falls back to `defaultHour`. */
  defaultStartHour?: number;
  /** Range mode: default minute for the start date. Falls back to `defaultMinute`. */
  defaultStartMinute?: number;
  /** Range mode: default hour for the end date. Falls back to `defaultHour`. */
  defaultEndHour?: number;
  /** Range mode: default minute for the end date. Falls back to `defaultMinute`. */
  defaultEndMinute?: number;
  allowClear?: boolean;
  fullWidth?: boolean;
  className?: string;
  /** Override the default calendar icon. */
  calendarIcon?: React.ReactNode;
  placement?: Placement;
} & (SingleProps | RangeProps);

const CalendarIcon = () => (
  <svg
    viewBox="0 0 24 24"
    width="20"
    height="20"
    fill="none"
    stroke="currentColor"
    strokeWidth="1.5"
    strokeLinecap="round"
    strokeLinejoin="round"
    aria-hidden="true"
  >
    <rect x="3" y="4" width="18" height="18" rx="2" />
    <line x1="16" y1="2" x2="16" y2="6" />
    <line x1="8" y1="2" x2="8" y2="6" />
    <line x1="3" y1="10" x2="21" y2="10" />
  </svg>
);

const ChevronIcon = ({ rotated }: { rotated?: boolean }) => (
  <svg
    viewBox="0 0 24 24"
    width="16"
    height="16"
    aria-hidden="true"
    style={{ transform: rotated ? "rotate(180deg)" : undefined }}
  >
    <path d="M7 10l5 5 5-5z" fill="currentColor" />
  </svg>
);

const ClearIcon = () => (
  <svg viewBox="0 0 24 24" width="14" height="14" aria-hidden="true">
    <path
      d="M19 6.41 17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12z"
      fill="currentColor"
    />
  </svg>
);

function buildCalendar(month: Date, locale: DateLocale): Date[] {
  const year = month.getFullYear();
  const m = month.getMonth();
  const firstDay = new Date(year, m, 1);
  const lastDay = new Date(year, m + 1, 0);
  const dayOfWeek = locale === "tr" ? (firstDay.getDay() + 6) % 7 : firstDay.getDay();

  const days: Date[] = [];
  for (let i = dayOfWeek - 1; i >= 0; i--) days.push(new Date(year, m, -i));
  for (let d = 1; d <= lastDay.getDate(); d++) days.push(new Date(year, m, d));
  const remaining = 7 - (days.length % 7);
  if (remaining < 7) for (let i = 1; i <= remaining; i++) days.push(new Date(year, m + 1, i));
  return days;
}

export const DatePicker: React.FC<DatePickerProps> = (props) => {
  const {
    label,
    placeholder,
    disabled = false,
    readOnly = false,
    required = false,
    error = false,
    errorMessage,
    variant = "outlined",
    size = "md",
    minDate,
    maxDate,
    locale = "tr",
    showTime = false,
    minuteStep = 15,
    defaultHour = 0,
    defaultMinute = 0,
    defaultStartHour,
    defaultStartMinute,
    defaultEndHour,
    defaultEndMinute,
    allowClear = false,
    fullWidth = false,
    className,
    calendarIcon,
    placement = "bottom-start",
    isRange,
  } = props;

  const defaultFormat = showTime ? "dd.MM.yyyy HH:mm" : "dd.MM.yyyy";
  const format = props.format ?? defaultFormat;

  const reactId = useId();
  const fieldId = `sisyphos-datepicker-${reactId}`;

  const value = props.value;
  const singleValue = !isRange ? ((value as SingleValue | undefined) ?? null) : null;
  const rangeValue: RangeValue = isRange
    ? ((value as RangeValue | undefined) ?? [null, null])
    : [null, null];

  const emitSingle = (v: SingleValue) =>
    (props.onChange as ((v: SingleValue) => void) | undefined)?.(v);
  const emitRange = (v: RangeValue) =>
    (props.onChange as ((v: RangeValue) => void) | undefined)?.(v);

  const [isOpen, setIsOpen] = useState(false);
  const [viewMode, setViewMode] = useState<ViewMode>("days");
  const [cursor, setCursor] = useState<Date>(
    () => (isRange ? rangeValue[0] : singleValue) ?? new Date()
  );

  const triggerRef = useRef<HTMLDivElement | null>(null);
  const dropdownRef = useRef<HTMLDivElement | null>(null);
  const [pos, setPos] = useState<{
    left: number;
    top: number;
    placement: Placement;
    width: number;
  } | null>(null);

  useEscapeKey(() => setIsOpen(false), isOpen);

  useEffect(() => {
    if (!isOpen) return;
    const handler = (e: MouseEvent) => {
      const tgt = e.target as Node | null;
      if (!tgt) return;
      if (triggerRef.current?.contains(tgt)) return;
      if (dropdownRef.current?.contains(tgt)) return;
      setIsOpen(false);
      setViewMode("days");
    };
    document.addEventListener("mousedown", handler);
    return () => document.removeEventListener("mousedown", handler);
  }, [isOpen]);

  useEffect(() => {
    if (!isOpen) {
      setPos(null);
      return;
    }
    let raf = 0;
    const update = () => {
      const anchor = triggerRef.current;
      const dd = dropdownRef.current;
      if (!anchor || !dd) return;
      const a = anchor.getBoundingClientRect();
      const size = { width: dd.offsetWidth, height: dd.offsetHeight };
      const p = computePosition(a, size, placement, 4);
      setPos({ ...p, width: a.width });
    };
    raf = requestAnimationFrame(() => requestAnimationFrame(update));
    const onWin = () => update();
    window.addEventListener("scroll", onWin, true);
    window.addEventListener("resize", onWin);
    return () => {
      cancelAnimationFrame(raf);
      window.removeEventListener("scroll", onWin, true);
      window.removeEventListener("resize", onWin);
    };
  }, [isOpen, placement]);

  const displayValue = useMemo(() => {
    if (isRange) {
      const [s, e] = rangeValue;
      if (s && e) return `${formatDate(s, format)} - ${formatDate(e, format)}`;
      if (s) return formatDate(s, format);
      return "";
    }
    return singleValue ? formatDate(singleValue, format) : "";
  }, [isRange, singleValue, rangeValue, format]);

  const hasValue = isRange ? Boolean(rangeValue[0] || rangeValue[1]) : Boolean(singleValue);

  const openPicker = () => {
    if (disabled || readOnly) return;
    setIsOpen((prev) => !prev);
    setViewMode("days");
  };

  const clear = useCallback(
    (e: React.MouseEvent) => {
      e.stopPropagation();
      if (isRange) emitRange([null, null]);
      else emitSingle(null);
    },
    [isRange]
  );

  const isDateDisabled = useCallback(
    (date: Date) => {
      if (minDate && date < minDate) return true;
      if (maxDate && date > maxDate) return true;
      return false;
    },
    [minDate, maxDate]
  );

  const isSelected = useCallback(
    (date: Date) => {
      if (isRange) {
        const [s, e] = rangeValue;
        return (s && sameDay(date, s)) || (e && sameDay(date, e));
      }
      return singleValue ? sameDay(date, singleValue) : false;
    },
    [isRange, rangeValue, singleValue]
  );

  const isInRange = useCallback(
    (date: Date) => {
      if (!isRange) return false;
      const [s, e] = rangeValue;
      if (!s || !e) return false;
      return date >= s && date <= e;
    },
    [isRange, rangeValue]
  );

  /**
   * Apply the configured default time when the user picks a date for the
   * first time in `showTime` mode. Once a date already has a user-edited
   * time we keep it intact.
   */
  const applyDefaultTime = useCallback(
    (d: Date, target: "single" | "start" | "end"): Date => {
      if (!showTime) return d;
      let h = defaultHour;
      let m = defaultMinute;
      if (target === "start") {
        h = defaultStartHour ?? defaultHour;
        m = defaultStartMinute ?? defaultMinute;
      } else if (target === "end") {
        h = defaultEndHour ?? defaultHour;
        m = defaultEndMinute ?? defaultMinute;
      }
      return withTime(d, h, m);
    },
    [
      showTime,
      defaultHour,
      defaultMinute,
      defaultStartHour,
      defaultStartMinute,
      defaultEndHour,
      defaultEndMinute,
    ]
  );

  const handleDaySelect = (d: Date) => {
    if (isDateDisabled(d)) return;
    if (!isRange) {
      const next =
        showTime && singleValue
          ? withTime(d, singleValue.getHours(), singleValue.getMinutes())
          : applyDefaultTime(d, "single");
      emitSingle(next);
      if (!showTime) setIsOpen(false);
      return;
    }
    const [s, e] = rangeValue;
    if (!s || (s && e)) {
      emitRange([applyDefaultTime(d, "start"), null]);
    } else if (s && !e) {
      if (d >= s) {
        emitRange([s, applyDefaultTime(d, "end")]);
      } else {
        // User picked a date earlier than the existing start — flip the range.
        // The previous start keeps its (possibly edited) time and becomes the
        // end; the freshly picked date receives the default start time.
        emitRange([applyDefaultTime(d, "start"), s]);
      }
      if (!showTime) setIsOpen(false);
    }
  };

  const handleTimeChange = (
    target: "single" | "start" | "end",
    which: "hour" | "minute",
    val: number
  ) => {
    if (target === "single") {
      if (!singleValue) return;
      const h = which === "hour" ? val : singleValue.getHours();
      const m = which === "minute" ? val : singleValue.getMinutes();
      emitSingle(withTime(singleValue, h, m));
    } else if (target === "start") {
      const s = rangeValue[0];
      if (!s) return;
      const h = which === "hour" ? val : s.getHours();
      const m = which === "minute" ? val : s.getMinutes();
      emitRange([withTime(s, h, m), rangeValue[1]]);
    } else {
      const e = rangeValue[1];
      if (!e) return;
      const h = which === "hour" ? val : e.getHours();
      const m = which === "minute" ? val : e.getMinutes();
      emitRange([rangeValue[0], withTime(e, h, m)]);
    }
  };

  const minuteOptions = useMemo(() => {
    const out: number[] = [];
    for (let m = 0; m < 60; m += minuteStep) out.push(m);
    return out;
  }, [minuteStep]);

  const decadeStart = Math.floor(cursor.getFullYear() / 10) * 10;
  const years = Array.from({ length: 10 }, (_, i) => decadeStart + i);

  const calendarDays = useMemo(() => buildCalendar(cursor, locale), [cursor, locale]);

  const nav = {
    prev: () => {
      if (viewMode === "days") setCursor(new Date(cursor.getFullYear(), cursor.getMonth() - 1));
      else if (viewMode === "months")
        setCursor(new Date(cursor.getFullYear() - 1, cursor.getMonth()));
      else setCursor(new Date(cursor.getFullYear() - 10, cursor.getMonth()));
    },
    next: () => {
      if (viewMode === "days") setCursor(new Date(cursor.getFullYear(), cursor.getMonth() + 1));
      else if (viewMode === "months")
        setCursor(new Date(cursor.getFullYear() + 1, cursor.getMonth()));
      else setCursor(new Date(cursor.getFullYear() + 10, cursor.getMonth()));
    },
  };

  return (
    <div
      className={cx(
        "sisyphos-datepicker",
        size,
        variant,
        error && "error",
        disabled && "disabled",
        fullWidth && "full-width",
        className
      )}
    >
      {label && (
        <label
          htmlFor={fieldId}
          className={cx("sisyphos-datepicker-label", error && "error", required && "required")}
        >
          {label}
        </label>
      )}
      <div
        ref={triggerRef}
        className={cx("sisyphos-datepicker-trigger", isOpen && "focused")}
        onClick={openPicker}
      >
        <span className="sisyphos-datepicker-start-icon" aria-hidden="true">
          {calendarIcon ?? <CalendarIcon />}
        </span>
        <input
          id={fieldId}
          className="sisyphos-datepicker-input"
          type="text"
          readOnly
          disabled={disabled}
          value={displayValue}
          placeholder={placeholder ?? PLACEHOLDERS[locale]}
          aria-invalid={error || undefined}
          aria-haspopup="dialog"
          aria-expanded={isOpen}
        />
        <div className="sisyphos-datepicker-end-icons">
          {allowClear && hasValue && !disabled && (
            <button
              type="button"
              className="sisyphos-datepicker-clear"
              onClick={clear}
              aria-label="Clear date"
            >
              <ClearIcon />
            </button>
          )}
          <span className="sisyphos-datepicker-chevron" aria-hidden="true">
            <ChevronIcon rotated={isOpen} />
          </span>
        </div>
      </div>

      {isOpen && (
        <Portal>
          <div
            ref={dropdownRef}
            role="dialog"
            aria-label={label ?? "Date picker"}
            className="sisyphos-datepicker-dropdown"
            style={{
              position: "fixed",
              left: pos?.left ?? 0,
              top: pos?.top ?? 0,
              minWidth: pos?.width ?? 0,
              opacity: pos ? 1 : 0,
            }}
          >
            <div className="sisyphos-datepicker-header">
              <button
                type="button"
                className="sisyphos-datepicker-nav"
                onClick={nav.prev}
                aria-label="Previous"
              >
                ‹
              </button>
              <button
                type="button"
                className="sisyphos-datepicker-header-title"
                onClick={() =>
                  setViewMode((m) => (m === "days" ? "months" : m === "months" ? "years" : "years"))
                }
              >
                {viewMode === "days" &&
                  `${MONTHS[locale][cursor.getMonth()]} ${cursor.getFullYear()}`}
                {viewMode === "months" && cursor.getFullYear()}
                {viewMode === "years" && `${years[0]} - ${years[9]}`}
              </button>
              <button
                type="button"
                className="sisyphos-datepicker-nav"
                onClick={nav.next}
                aria-label="Next"
              >
                ›
              </button>
            </div>

            {viewMode === "days" && (
              <>
                <div className="sisyphos-datepicker-weekdays">
                  {WEEK_DAYS[locale].map((d) => (
                    <div key={d} className="sisyphos-datepicker-weekday">
                      {d}
                    </div>
                  ))}
                </div>
                <div className="sisyphos-datepicker-days">
                  {calendarDays.map((d, i) => {
                    const other = d.getMonth() !== cursor.getMonth();
                    const selected = isSelected(d);
                    const inRange = isInRange(d);
                    const isToday = sameDay(d, new Date());
                    const dis = isDateDisabled(d) || other;
                    return (
                      <button
                        key={i}
                        type="button"
                        className={cx(
                          "sisyphos-datepicker-day",
                          other && "other-month",
                          isToday && !hasValue && "today",
                          selected && "selected",
                          inRange && "in-range",
                          dis && "disabled"
                        )}
                        disabled={dis}
                        onClick={() => handleDaySelect(d)}
                        aria-selected={selected || undefined}
                      >
                        {d.getDate()}
                      </button>
                    );
                  })}
                </div>
              </>
            )}

            {viewMode === "months" && (
              <div className="sisyphos-datepicker-months">
                {MONTHS[locale].map((m, idx) => (
                  <button
                    key={m}
                    type="button"
                    className={cx(
                      "sisyphos-datepicker-month",
                      idx === cursor.getMonth() && "selected"
                    )}
                    onClick={() => {
                      setCursor(new Date(cursor.getFullYear(), idx));
                      setViewMode("days");
                    }}
                  >
                    {m}
                  </button>
                ))}
              </div>
            )}

            {viewMode === "years" && (
              <div className="sisyphos-datepicker-years">
                {years.map((y) => (
                  <button
                    key={y}
                    type="button"
                    className={cx(
                      "sisyphos-datepicker-year",
                      y === cursor.getFullYear() && "selected"
                    )}
                    onClick={() => {
                      setCursor(new Date(y, cursor.getMonth()));
                      setViewMode("months");
                    }}
                  >
                    {y}
                  </button>
                ))}
              </div>
            )}

            {showTime && (
              <div className={cx("sisyphos-datepicker-time", isRange && "range")}>
                {isRange ? (
                  (["start", "end"] as const).map((which, i) => {
                    const v = rangeValue[i];
                    const h = v?.getHours() ?? 0;
                    const m = v?.getMinutes() ?? 0;
                    return (
                      <div key={which} className="sisyphos-datepicker-time-group">
                        <div className="sisyphos-datepicker-time-label">
                          {RANGE_LABELS[locale][which]}
                        </div>
                        <div className="sisyphos-datepicker-time-row">
                          <select
                            aria-label={`${RANGE_LABELS[locale][which]} hour`}
                            disabled={!v}
                            value={h}
                            onChange={(e) =>
                              handleTimeChange(which, "hour", Number(e.target.value))
                            }
                          >
                            {Array.from({ length: 24 }).map((_, idx) => (
                              <option key={idx} value={idx}>
                                {String(idx).padStart(2, "0")}
                              </option>
                            ))}
                          </select>
                          :
                          <select
                            aria-label={`${RANGE_LABELS[locale][which]} minute`}
                            disabled={!v}
                            value={m}
                            onChange={(e) =>
                              handleTimeChange(which, "minute", Number(e.target.value))
                            }
                          >
                            {minuteOptions.map((mm) => (
                              <option key={mm} value={mm}>
                                {String(mm).padStart(2, "0")}
                              </option>
                            ))}
                          </select>
                        </div>
                      </div>
                    );
                  })
                ) : (
                  <div className="sisyphos-datepicker-time-row">
                    <select
                      aria-label="Hour"
                      disabled={!singleValue}
                      value={singleValue?.getHours() ?? 0}
                      onChange={(e) => handleTimeChange("single", "hour", Number(e.target.value))}
                    >
                      {Array.from({ length: 24 }).map((_, idx) => (
                        <option key={idx} value={idx}>
                          {String(idx).padStart(2, "0")}
                        </option>
                      ))}
                    </select>
                    :
                    <select
                      aria-label="Minute"
                      disabled={!singleValue}
                      value={singleValue?.getMinutes() ?? 0}
                      onChange={(e) => handleTimeChange("single", "minute", Number(e.target.value))}
                    >
                      {minuteOptions.map((mm) => (
                        <option key={mm} value={mm}>
                          {String(mm).padStart(2, "0")}
                        </option>
                      ))}
                    </select>
                  </div>
                )}
              </div>
            )}
          </div>
        </Portal>
      )}

      {error && errorMessage && (
        <span className="sisyphos-datepicker-error" role="alert">
          {errorMessage}
        </span>
      )}
    </div>
  );
};
