// packages/card/src/Card.tsx
/**
 * Card — surface container. Use on its own for simple content or compose with
 * `Card.Header`, `Card.Body`, and `Card.Footer` for structured layouts.
 */
import React from "react";
import { cx } from "@sisyphos-ui/core/internal";
import "./Card.scss";

export type CardVariant = "elevated" | "outlined" | "filled";
export type CardPadding = "none" | "sm" | "md" | "lg";

export interface CardProps extends React.HTMLAttributes<HTMLDivElement> {
  variant?: CardVariant;
  /** Body padding when the compound slots are not used. */
  padding?: CardPadding;
  /** Marks the whole card as focusable/clickable (role="button", tabIndex=0). */
  interactive?: boolean;
}

interface CardComponent extends React.ForwardRefExoticComponent<CardProps & React.RefAttributes<HTMLDivElement>> {
  Header: typeof CardHeader;
  Body: typeof CardBody;
  Footer: typeof CardFooter;
}

const CardRoot = React.forwardRef<HTMLDivElement, CardProps>(function Card(
  { variant = "elevated", padding = "md", interactive = false, className, children, ...rest },
  ref
) {
  return (
    <div
      ref={ref}
      className={cx("sisyphos-card", variant, `padding-${padding}`, interactive && "interactive", className)}
      tabIndex={interactive ? 0 : undefined}
      role={interactive ? "button" : undefined}
      {...rest}
    >
      {children}
    </div>
  );
});

const CardHeader = React.forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement>>(function CardHeader(
  { className, children, ...rest },
  ref
) {
  return (
    <header ref={ref} className={cx("sisyphos-card-header", className)} {...rest}>
      {children}
    </header>
  );
});

const CardBody = React.forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement>>(function CardBody(
  { className, children, ...rest },
  ref
) {
  return (
    <div ref={ref} className={cx("sisyphos-card-body", className)} {...rest}>
      {children}
    </div>
  );
});

const CardFooter = React.forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement>>(function CardFooter(
  { className, children, ...rest },
  ref
) {
  return (
    <footer ref={ref} className={cx("sisyphos-card-footer", className)} {...rest}>
      {children}
    </footer>
  );
});

CardRoot.displayName = "Card";
CardHeader.displayName = "Card.Header";
CardBody.displayName = "Card.Body";
CardFooter.displayName = "Card.Footer";

export const Card = CardRoot as CardComponent;
Card.Header = CardHeader;
Card.Body = CardBody;
Card.Footer = CardFooter;

// packages/angular/src/card/card.component.ts
/**
 * Card — Angular 18 standalone surface container.
 *
 * Use on its own for simple content or compose with `<sui-card-header>`,
 * `<sui-card-body>`, `<sui-card-footer>` for structured layouts. The
 * compound API mirrors `Card.Header / Card.Body / Card.Footer` from the React
 * binding — Angular doesn't have static class members for components, so each
 * slot is its own standalone component.
 *
 * Usage:
 *   <sui-card variant="elevated" padding="md">
 *     <sui-card-header>Title</sui-card-header>
 *     <sui-card-body>...</sui-card-body>
 *     <sui-card-footer>...</sui-card-footer>
 *   </sui-card>
 */
import { ChangeDetectionStrategy, Component, Input, computed, signal } from "@angular/core";

export type CardVariant = "elevated" | "outlined" | "filled";
export type CardPadding = "none" | "sm" | "md" | "lg";

@Component({
  selector: "sui-card",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div
      [class]="rootClasses()"
      [attr.tabindex]="interactive() ? 0 : null"
      [attr.role]="interactive() ? 'button' : null"
    >
      <ng-content />
    </div>
  `,
})
export class Card {
  private readonly _variant = signal<CardVariant>("elevated");
  private readonly _padding = signal<CardPadding>("md");
  private readonly _interactive = signal(false);

  readonly variant = this._variant.asReadonly();
  readonly padding = this._padding.asReadonly();
  readonly interactive = this._interactive.asReadonly();

  @Input("variant") set variantInput(v: CardVariant) {
    this._variant.set(v);
  }
  @Input("padding") set paddingInput(v: CardPadding) {
    this._padding.set(v);
  }
  @Input("interactive") set interactiveInput(v: boolean) {
    this._interactive.set(v);
  }

  readonly rootClasses = computed(() =>
    [
      "sisyphos-card",
      this._variant(),
      `padding-${this._padding()}`,
      this._interactive() && "interactive",
    ]
      .filter(Boolean)
      .join(" ")
  );
}

@Component({
  selector: "sui-card-header",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<header class="sisyphos-card-header"><ng-content /></header>`,
})
export class CardHeader {}

@Component({
  selector: "sui-card-body",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<div class="sisyphos-card-body"><ng-content /></div>`,
})
export class CardBody {}

@Component({
  selector: "sui-card-footer",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<footer class="sisyphos-card-footer"><ng-content /></footer>`,
})
export class CardFooter {}
