// packages/vue/src/carousel/Carousel.vue
<script setup lang="ts">
/**
 * Carousel — Vue 3 binding. Slot-based content with autoplay, loop,
 * arrows, and dot navigation. Mirrors the React Carousel API shape.
 */
import { computed, onBeforeUnmount, onMounted, ref, watch } from "vue";

interface Props {
  /** Controlled active index. */
  index?: number;
  /** Default active index (uncontrolled). */
  defaultIndex?: number;
  /** Number of slides. Required so we can render dots / aria labels. */
  count: number;
  /** Auto-advance every `autoPlayInterval` ms. */
  autoPlay?: boolean;
  /** Time between auto-advances in ms. Defaults to 5000. */
  autoPlayInterval?: number;
  /** Wrap from last to first / first to last. */
  loop?: boolean;
  showArrows?: boolean;
  showDots?: boolean;
  /** Pause autoplay on hover / focus. */
  pauseOnHover?: boolean;
  ariaLabel?: string;
}

const props = withDefaults(defineProps<Props>(), {
  defaultIndex: 0,
  autoPlay: false,
  autoPlayInterval: 5000,
  loop: true,
  showArrows: true,
  showDots: true,
  pauseOnHover: true,
  ariaLabel: "carousel",
});

const emit = defineEmits<{
  (e: "update:index", index: number): void;
  (e: "indexChange", index: number): void;
}>();

const internal = ref(props.defaultIndex);
const current = computed(() => props.index ?? internal.value);
const paused = ref(false);

function setIndex(next: number) {
  let normalized = next;
  if (normalized < 0) normalized = props.loop ? props.count - 1 : 0;
  if (normalized >= props.count) normalized = props.loop ? 0 : props.count - 1;
  if (props.index === undefined) internal.value = normalized;
  emit("update:index", normalized);
  emit("indexChange", normalized);
}

let timer: ReturnType<typeof setInterval> | null = null;
function startAuto() {
  stopAuto();
  if (!props.autoPlay || paused.value || props.count < 2) return;
  timer = setInterval(() => setIndex(current.value + 1), props.autoPlayInterval);
}
function stopAuto() {
  if (timer) {
    clearInterval(timer);
    timer = null;
  }
}
onMounted(startAuto);
watch(
  () => [props.autoPlay, props.autoPlayInterval, props.count, paused.value, current.value],
  startAuto
);
onBeforeUnmount(stopAuto);

const trackStyle = computed(() => ({
  transform: `translateX(-${current.value * 100}%)`,
}));
</script>

<template>
  <div
    class="sisyphos-carousel"
    role="region"
    :aria-roledescription="ariaLabel"
    @mouseenter="pauseOnHover && (paused = true)"
    @mouseleave="pauseOnHover && (paused = false)"
    @focusin="pauseOnHover && (paused = true)"
    @focusout="pauseOnHover && (paused = false)"
  >
    <div class="sisyphos-carousel-viewport">
      <div class="sisyphos-carousel-track" :style="trackStyle">
        <slot />
      </div>
    </div>
    <button
      v-if="showArrows && count > 1"
      type="button"
      class="sisyphos-carousel-arrow start"
      aria-label="Previous slide"
      @click="setIndex(current - 1)"
    >
      <svg viewBox="0 0 24 24" width="20" height="20" aria-hidden="true">
        <path d="M15 18L9 12L15 6" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
      </svg>
    </button>
    <button
      v-if="showArrows && count > 1"
      type="button"
      class="sisyphos-carousel-arrow end"
      aria-label="Next slide"
      @click="setIndex(current + 1)"
    >
      <svg viewBox="0 0 24 24" width="20" height="20" aria-hidden="true">
        <path d="M9 18L15 12L9 6" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
      </svg>
    </button>
    <div v-if="showDots && count > 1" class="sisyphos-carousel-dots" role="tablist" aria-label="Slide selector">
      <button
        v-for="i in count"
        :key="i - 1"
        type="button"
        role="tab"
        :aria-selected="i - 1 === current"
        :aria-label="`Go to slide ${i}`"
        :class="['sisyphos-carousel-dot', i - 1 === current && 'active']"
        @click="setIndex(i - 1)"
      />
    </div>
  </div>
</template>

<style src="./Carousel.scss"></style>

// packages/carousel/src/Carousel.tsx
/**
 * Carousel — sliding content area with optional autoplay (paused on hover and
 * focus), navigation arrows, dot indicators, and arrow-key keyboard support.
 *
 * Works controlled (`index`) or uncontrolled (`defaultIndex`).
 */
import React, {
  Children,
  useCallback,
  useEffect,
  useRef,
  useState,
} from "react";
import { cx } from "@sisyphos-ui/core/internal";
import "./Carousel.scss";

export interface CarouselProps extends Omit<React.HTMLAttributes<HTMLDivElement>, "onChange"> {
  /** Controlled active index. */
  index?: number;
  /** Default active index (uncontrolled). */
  defaultIndex?: number;
  onIndexChange?: (index: number) => void;
  /** Auto-advance every `autoPlayInterval` ms. */
  autoPlay?: boolean;
  /** Time between auto-advances in ms. Defaults to 5000. */
  autoPlayInterval?: number;
  /** Wrap from last to first / first to last. Default `true`. */
  loop?: boolean;
  showArrows?: boolean;
  showDots?: boolean;
  /** Pause autoplay on mouse enter / focus. Default `true`. */
  pauseOnHover?: boolean;
  /** Override label for the container `aria-roledescription`. Default `"carousel"`. */
  ariaLabel?: string;
}

const Chevron: React.FC<{ direction: "left" | "right" }> = ({ direction }) => (
  <svg viewBox="0 0 24 24" width="20" height="20" aria-hidden="true">
    <path
      d={direction === "left" ? "M15 18L9 12L15 6" : "M9 18L15 12L9 6"}
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    />
  </svg>
);

export const Carousel: React.FC<CarouselProps> = ({
  index: indexProp,
  defaultIndex = 0,
  onIndexChange,
  autoPlay = false,
  autoPlayInterval = 5000,
  loop = true,
  showArrows = true,
  showDots = true,
  pauseOnHover = true,
  ariaLabel = "carousel",
  className,
  children,
  ...rest
}) => {
  const slides = Children.toArray(children);
  const count = slides.length;

  const isControlled = indexProp !== undefined;
  const [internal, setInternal] = useState(defaultIndex);
  const current = isControlled ? indexProp! : internal;

  const [paused, setPaused] = useState(false);
  const timerRef = useRef<ReturnType<typeof setInterval> | null>(null);

  const setIndex = useCallback(
    (next: number) => {
      const clamped = ((next % count) + count) % count;
      if (!loop) {
        if (next < 0 || next >= count) return;
      }
      if (!isControlled) setInternal(clamped);
      onIndexChange?.(clamped);
    },
    [count, loop, isControlled, onIndexChange]
  );

  const next = useCallback(() => setIndex(current + 1), [current, setIndex]);
  const prev = useCallback(() => setIndex(current - 1), [current, setIndex]);

  useEffect(() => {
    if (!autoPlay || paused || count <= 1) return;
    timerRef.current = setInterval(next, autoPlayInterval);
    return () => {
      if (timerRef.current) clearInterval(timerRef.current);
    };
  }, [autoPlay, paused, count, autoPlayInterval, next]);

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === "ArrowRight") {
      e.preventDefault();
      next();
    } else if (e.key === "ArrowLeft") {
      e.preventDefault();
      prev();
    }
  };

  if (count === 0) return null;

  const hasMultiple = count > 1;

  return (
    <div
      role="region"
      aria-roledescription={ariaLabel}
      tabIndex={0}
      className={cx("sisyphos-carousel", className)}
      onKeyDown={handleKeyDown}
      onMouseEnter={pauseOnHover ? () => setPaused(true) : undefined}
      onMouseLeave={pauseOnHover ? () => setPaused(false) : undefined}
      onFocus={pauseOnHover ? () => setPaused(true) : undefined}
      onBlur={pauseOnHover ? () => setPaused(false) : undefined}
      {...rest}
    >
      <div className="sisyphos-carousel-viewport">
        <div
          className="sisyphos-carousel-track"
          style={{ transform: `translateX(-${current * 100}%)` }}
        >
          {slides.map((child, i) => (
            <div
              key={i}
              className="sisyphos-carousel-slide"
              role="group"
              aria-roledescription="slide"
              aria-label={`${i + 1} of ${count}`}
              aria-hidden={i !== current}
            >
              {child}
            </div>
          ))}
        </div>

        {showArrows && hasMultiple && (
          <>
            <button
              type="button"
              className="sisyphos-carousel-arrow prev"
              onClick={prev}
              aria-label="Previous slide"
              disabled={!loop && current === 0}
            >
              <Chevron direction="left" />
            </button>
            <button
              type="button"
              className="sisyphos-carousel-arrow next"
              onClick={next}
              aria-label="Next slide"
              disabled={!loop && current === count - 1}
            >
              <Chevron direction="right" />
            </button>
          </>
        )}
      </div>

      {showDots && hasMultiple && (
        <div className="sisyphos-carousel-dots" role="tablist" aria-label="Slide selector">
          {slides.map((_, i) => (
            <button
              key={i}
              type="button"
              role="tab"
              aria-selected={i === current}
              aria-label={`Go to slide ${i + 1}`}
              className={cx("sisyphos-carousel-dot", i === current && "active")}
              onClick={() => setIndex(i)}
            />
          ))}
        </div>
      )}
    </div>
  );
};
