// apps/preview-vue/src/demos/chip-default.vue
<script setup lang="ts">
import { Chip } from "@sisyphos-ui/vue";
</script>

<template>
  <div style="display: flex; gap: 8px;">
    <Chip variant="soft" color="primary">Featured</Chip>
    <Chip variant="soft" color="success">Active</Chip>
    <Chip variant="soft" color="warning">Pending</Chip>
  </div>
</template>

// apps/preview-angular/src/demos/chip-default.component.ts
import { ChangeDetectionStrategy, Component } from "@angular/core";
import { Chip } from "@sisyphos-ui/angular";

@Component({
  standalone: true,
  selector: "demo-chip-default",
  imports: [Chip],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div style="display:flex;gap:8px">
      <sui-chip variant="soft" color="primary">Featured</sui-chip>
      <sui-chip variant="soft" color="success">Active</sui-chip>
      <sui-chip variant="soft" color="warning">Pending</sui-chip>
    </div>
  `,
})
export class ChipDefaultDemo {}
