// apps/preview-vue/src/demos/form-control-default.vue
<script setup lang="ts">
import { FormControl, FormLabel, FormHelperText, Input } from "@sisyphos-ui/vue";
</script>

<template>
  <FormControl>
    <FormLabel>Email</FormLabel>
    <Input type="email" placeholder="name@example.com" />
    <FormHelperText>We'll never share your email.</FormHelperText>
  </FormControl>
</template>

// apps/preview-angular/src/demos/form-control-default.component.ts
import { ChangeDetectionStrategy, Component } from "@angular/core";
import { FormControl, FormHelperText, FormLabel, Input } from "@sisyphos-ui/angular";

@Component({
  standalone: true,
  selector: "demo-form-control-default",
  imports: [FormControl, FormLabel, FormHelperText, Input],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <sui-form-control>
      <sui-form-label>Email</sui-form-label>
      <sui-input type="email" placeholder="name@example.com" />
      <sui-form-helper-text>We'll never share your email.</sui-form-helper-text>
    </sui-form-control>
  `,
})
export class FormControlDefaultDemo {}
