// apps/preview-vue/src/demos/popover-default.vue
<script setup lang="ts">
import { Popover, Button } from "@sisyphos-ui/vue";
</script>

<template>
  <Popover>
    <Button variant="outlined">Open popover</Button>
    <template #content>
      <div style="padding:12px; max-width:240px;">Popovers carry rich interactive content with focus management.</div>
    </template>
  </Popover>
</template>

// apps/preview-angular/src/demos/popover-default.component.ts
import { ChangeDetectionStrategy, Component } from "@angular/core";
import { Button, Popover } from "@sisyphos-ui/angular";

@Component({
  standalone: true,
  selector: "demo-popover-default",
  imports: [Popover, Button],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <sui-popover>
      <sui-button variant="outlined">Open popover</sui-button>
      <div popover-content style="padding:12px; max-width:240px;">
        Popovers carry rich interactive content with focus management.
      </div>
    </sui-popover>
  `,
})
export class PopoverDefaultDemo {}
