// apps/preview-vue/src/demos/radio-default.vue
<script setup lang="ts">
import { ref } from "vue";
import { RadioGroup, Radio } from "@sisyphos-ui/vue";

const plan = ref<string | number>("pro");
</script>

<template>
  <RadioGroup label="Plan" v-model:value="plan" variant="card">
    <Radio value="free" label="Free" description="All the basics, forever." />
    <Radio value="pro" label="Pro" description="For growing teams." />
    <Radio value="enterprise" label="Enterprise" description="Dedicated support." />
  </RadioGroup>
</template>

// apps/preview-angular/src/demos/radio-default.component.ts
import { ChangeDetectionStrategy, Component, signal } from "@angular/core";
import { Radio, RadioGroup } from "@sisyphos-ui/angular";

@Component({
  standalone: true,
  selector: "demo-radio-default",
  imports: [RadioGroup, Radio],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <sui-radio-group label="Plan" [(value)]="plan" variant="card">
      <sui-radio value="free" label="Free" description="All the basics, forever." />
      <sui-radio value="pro" label="Pro" description="For growing teams." />
      <sui-radio value="enterprise" label="Enterprise" description="Dedicated support." />
    </sui-radio-group>
  `,
})
export class RadioDefaultDemo {
  protected readonly plan = signal<string | number>("pro");
}
