// packages/angular/src/select/select.component.ts
/**
 * Select — Angular 18 standalone single- or multi-value combobox.
 *
 * Optional search, clearable, creatable, infinite scroll. Mirrors the
 * React/Vue versions: same class names, same keyboard navigation
 * (Arrow keys, Home/End, Enter, Escape), same ARIA combobox + listbox.
 *
 * @example
 *   <sui-select [options]="opts" [(value)]="picked" placeholder="Pick one" />
 *   <sui-select [options]="opts" [(values)]="picked" multiple searchable />
 */
import type { ElementRef, OnDestroy } from "@angular/core";
import {
  ChangeDetectionStrategy,
  Component,
  EventEmitter,
  HostListener,
  Input,
  Output,
  ViewChild,
  computed,
  effect,
  signal,
} from "@angular/core";
import { computePosition, type Placement } from "@sisyphos-ui/core/internal";
import type { SelectOption, SelectValue } from "./types";

let selectCounter = 0;

@Component({
  selector: "sui-select",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div [class]="rootClasses()">
      @if (label()) {
        <label [class]="labelClasses()">{{ label() }}</label>
      }
      <div
        #trigger
        class="sisyphos-select-control"
        [class.open]="open()"
        [class.has-value]="hasValue()"
        role="combobox"
        [attr.aria-expanded]="open()"
        aria-haspopup="listbox"
        [attr.aria-controls]="open() ? listboxId : null"
        [attr.aria-disabled]="disabled() || null"
        [attr.aria-invalid]="error() || null"
        [tabindex]="disabled() ? -1 : 0"
        (click)="onTriggerClick()"
        (keydown)="onTriggerKeydown($event)"
      >
        <div class="sisyphos-select-value">
          @if (multiple() && selectedValues().length > 0) {
            <div class="sisyphos-select-tags">
              @for (v of selectedValues(); track v) {
                <span class="sisyphos-select-tag" [title]="labelOf(v)">
                  {{ labelOf(v) }}
                  <button
                    type="button"
                    class="sisyphos-select-tag-delete"
                    [attr.aria-label]="'Remove ' + labelOf(v)"
                    [disabled]="disabled()"
                    (click)="removeTag(v, $event)"
                  >
                    ×
                  </button>
                </span>
              }
            </div>
          } @else if (singleLabel()) {
            <span class="sisyphos-select-single">{{ singleLabel() }}</span>
          } @else {
            <span class="sisyphos-select-placeholder">{{ placeholder() }}</span>
          }
        </div>
        @if (clearable() && hasValue() && !disabled()) {
          <button
            type="button"
            aria-label="Clear selection"
            class="sisyphos-select-clear"
            (click)="onClear($event)"
          >
            <svg viewBox="0 0 24 24" width="14" height="14" aria-hidden="true">
              <path
                d="M19 6.41 17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12z"
                fill="currentColor"
              />
            </svg>
          </button>
        }
        <span class="sisyphos-select-chevron">
          <svg
            viewBox="0 0 24 24"
            width="18"
            height="18"
            aria-hidden="true"
            [style.transform]="open() ? 'rotate(180deg)' : null"
            [style.transition]="'transform 150ms'"
          >
            <path d="M7 10l5 5 5-5z" fill="currentColor" />
          </svg>
        </span>
      </div>

      @if (open()) {
        <ul
          #list
          [id]="listboxId"
          role="listbox"
          [attr.aria-multiselectable]="multiple() || null"
          [class]="listClasses()"
          [style.position]="'fixed'"
          [style.left.px]="pos()?.left ?? 0"
          [style.top.px]="pos()?.top ?? 0"
          [style.min-width.px]="pos()?.width ?? 0"
          [style.opacity]="pos() ? 1 : 0"
          [style.z-index]="1100"
          (scroll)="onScroll($event)"
        >
          @if (searchable() || creatable()) {
            <li class="sisyphos-select-search-row">
              <input
                #searchInput
                class="sisyphos-select-search"
                type="text"
                [placeholder]="creatable() ? 'Type to add…' : 'Search…'"
                [value]="search()"
                (input)="onSearchInput($event)"
                (keydown)="onTriggerKeydown($event)"
              />
            </li>
          }
          @if (filtered().length === 0 && !loading()) {
            <li class="sisyphos-select-empty">No options</li>
          }
          @for (opt of filtered(); track opt.value; let i = $index) {
            <li
              role="option"
              [attr.aria-selected]="isSelected(opt.value)"
              [attr.aria-disabled]="opt.disabled || null"
              [class]="optionClasses(opt, i)"
              (mouseenter)="setActive(i)"
              (click)="onOptionClick(opt)"
            >
              @if (opt.icon) {
                <span class="sisyphos-select-option-icon">{{ opt.icon }}</span>
              }
              <span class="sisyphos-select-option-body">
                <span class="sisyphos-select-option-label">{{ opt.label }}</span>
                @if (opt.description) {
                  <span class="sisyphos-select-option-description">{{ opt.description }}</span>
                }
              </span>
              @if (isSelected(opt.value)) {
                <span class="sisyphos-select-option-check" aria-hidden="true">✓</span>
              }
            </li>
          }
          @if (loading()) {
            <li class="sisyphos-select-loading">
              <span class="sisyphos-select-loading-spinner" aria-hidden="true"></span>
              <span>Loading…</span>
            </li>
          }
        </ul>
      }

      @if (error() && errorMessage()) {
        <span class="sisyphos-select-error" role="alert">{{ errorMessage() }}</span>
      } @else if (helperText()) {
        <span class="sisyphos-select-helper">{{ helperText() }}</span>
      }
    </div>
  `,
})
export class Select implements OnDestroy {
  readonly listboxId = `sisyphos-select-${++selectCounter}`;

  // Inputs ─────────────────────────────────────────────────────────────
  private readonly _options = signal<SelectOption[]>([]);
  private readonly _value = signal<SelectValue | null>(null);
  private readonly _values = signal<SelectValue[]>([]);
  private readonly _multiple = signal(false);
  private readonly _placeholder = signal<string>("Select…");
  private readonly _label = signal<string | undefined>(undefined);
  private readonly _helperText = signal<string | undefined>(undefined);
  private readonly _error = signal(false);
  private readonly _errorMessage = signal<string | undefined>(undefined);
  private readonly _disabled = signal(false);
  private readonly _required = signal(false);
  private readonly _size = signal<"xs" | "sm" | "md" | "lg" | "xl">("md");
  private readonly _radius = signal<"none" | "sm" | "md" | "lg" | "full">("sm");
  private readonly _fullWidth = signal(false);
  private readonly _searchable = signal(false);
  private readonly _clearable = signal(false);
  private readonly _creatable = signal(false);
  private readonly _loading = signal(false);
  private readonly _hasMore = signal<boolean | undefined>(undefined);
  private readonly _placement = signal<Placement>("bottom-start");

  // Internal state ─────────────────────────────────────────────────────
  private readonly _open = signal(false);
  private readonly _search = signal("");
  private readonly _activeIndex = signal(-1);
  protected readonly pos = signal<{
    left: number;
    top: number;
    placement: Placement;
    width: number;
  } | null>(null);

  // Public read API ────────────────────────────────────────────────────
  readonly options = this._options.asReadonly();
  readonly multiple = this._multiple.asReadonly();
  readonly placeholder = this._placeholder.asReadonly();
  readonly label = this._label.asReadonly();
  readonly helperText = this._helperText.asReadonly();
  readonly error = this._error.asReadonly();
  readonly errorMessage = this._errorMessage.asReadonly();
  readonly disabled = this._disabled.asReadonly();
  readonly required = this._required.asReadonly();
  readonly searchable = this._searchable.asReadonly();
  readonly clearable = this._clearable.asReadonly();
  readonly creatable = this._creatable.asReadonly();
  readonly loading = this._loading.asReadonly();
  readonly open = this._open.asReadonly();
  readonly search = this._search.asReadonly();
  readonly activeIndex = this._activeIndex.asReadonly();

  @Input("options") set optionsInput(v: SelectOption[]) {
    this._options.set(v ?? []);
  }
  /** Single-mode value. Use only when `multiple=false`. */
  @Input("value") set valueInput(v: SelectValue | null | undefined) {
    if (v !== undefined) this._value.set(v);
  }
  /** Multi-mode values. Use only when `multiple=true`. */
  @Input("values") set valuesInput(v: SelectValue[] | undefined) {
    if (v !== undefined) this._values.set(v ?? []);
  }
  @Input("multiple") set multipleInput(v: boolean) {
    this._multiple.set(v);
  }
  @Input("placeholder") set placeholderInput(v: string) {
    this._placeholder.set(v);
  }
  @Input("label") set labelInput(v: string | undefined) {
    this._label.set(v);
  }
  @Input("helperText") set helperTextInput(v: string | undefined) {
    this._helperText.set(v);
  }
  @Input("error") set errorInput(v: boolean) {
    this._error.set(v);
  }
  @Input("errorMessage") set errorMessageInput(v: string | undefined) {
    this._errorMessage.set(v);
  }
  @Input("disabled") set disabledInput(v: boolean) {
    this._disabled.set(v);
  }
  @Input("required") set requiredInput(v: boolean) {
    this._required.set(v);
  }
  @Input("size") set sizeInput(v: "xs" | "sm" | "md" | "lg" | "xl") {
    this._size.set(v);
  }
  @Input("radius") set radiusInput(v: "none" | "sm" | "md" | "lg" | "full") {
    this._radius.set(v);
  }
  @Input("fullWidth") set fullWidthInput(v: boolean) {
    this._fullWidth.set(v);
  }
  @Input("searchable") set searchableInput(v: boolean) {
    this._searchable.set(v);
  }
  @Input("clearable") set clearableInput(v: boolean) {
    this._clearable.set(v);
  }
  @Input("creatable") set creatableInput(v: boolean) {
    this._creatable.set(v);
  }
  @Input("loading") set loadingInput(v: boolean) {
    this._loading.set(v);
  }
  @Input("hasMore") set hasMoreInput(v: boolean | undefined) {
    this._hasMore.set(v);
  }
  @Input("placement") set placementInput(v: Placement) {
    this._placement.set(v);
  }

  /** Two-way bindings — single & multi modes use separate output names. */
  @Output() readonly valueChange = new EventEmitter<SelectValue | null>();
  @Output() readonly valuesChange = new EventEmitter<SelectValue[]>();
  @Output() readonly searchChange = new EventEmitter<string>();
  @Output() readonly loadMore = new EventEmitter<void>();

  @ViewChild("trigger") triggerRef?: ElementRef<HTMLDivElement>;
  @ViewChild("list") listRef?: ElementRef<HTMLUListElement>;
  @ViewChild("searchInput") searchInputRef?: ElementRef<HTMLInputElement>;

  readonly selectedValues = computed<SelectValue[]>(() => {
    if (this._multiple()) return this._values();
    const v = this._value();
    return v != null && v !== "" ? [v] : [];
  });

  readonly hasValue = computed(() => this.selectedValues().length > 0);

  readonly singleLabel = computed(() => {
    if (this._multiple()) return null;
    const v = this.selectedValues()[0];
    if (v === undefined) return null;
    return this._options().find((o) => o.value === v)?.label ?? String(v);
  });

  readonly filtered = computed<SelectOption[]>(() => {
    const all = this._options();
    if (!this._searchable() || !this._search()) return all;
    const term = this._search().toLowerCase();
    return all.filter((o) => o.label.toLowerCase().includes(term));
  });

  readonly rootClasses = computed(() =>
    [
      "sisyphos-select",
      this._size(),
      `radius-${this._radius()}`,
      this._disabled() && "disabled",
      this._error() && "error",
      this._fullWidth() && "full-width",
    ]
      .filter(Boolean)
      .join(" ")
  );

  readonly labelClasses = computed(() =>
    ["sisyphos-select-label", this._error() && "error", this._required() && "required"]
      .filter(Boolean)
      .join(" ")
  );

  readonly listClasses = computed(
    () => `sisyphos-select-list ${this.pos()?.placement ?? this._placement()}`
  );

  isSelected(v: SelectValue): boolean {
    return this.selectedValues().includes(v);
  }

  optionClasses(opt: SelectOption, i: number): string {
    return [
      "sisyphos-select-option",
      this.isSelected(opt.value) && "selected",
      opt.disabled && "disabled",
      i === this._activeIndex() && "active",
    ]
      .filter(Boolean)
      .join(" ");
  }

  labelOf(v: SelectValue): string {
    return this._options().find((o) => o.value === v)?.label ?? String(v);
  }

  private resizeListener?: () => void;
  private scrollListener?: () => void;

  constructor() {
    effect(() => {
      if (this._open()) {
        queueMicrotask(() => requestAnimationFrame(() => this.reposition()));
        this.installScrollListeners();
        if (this._searchable()) {
          queueMicrotask(() => this.searchInputRef?.nativeElement.focus());
        }
      } else {
        this.pos.set(null);
        this._search.set("");
        this._activeIndex.set(-1);
        this.removeScrollListeners();
      }
    });
  }

  ngOnDestroy(): void {
    this.removeScrollListeners();
  }

  // ── Trigger ──────────────────────────────────────────────────────────

  onTriggerClick(): void {
    if (this._disabled()) return;
    this.setOpen(!this._open());
  }

  onTriggerKeydown(event: KeyboardEvent): void {
    if (
      !this._open() &&
      (event.key === "ArrowDown" || event.key === "Enter" || event.key === " ")
    ) {
      event.preventDefault();
      this.setOpen(true);
      return;
    }
    if (!this._open()) return;
    const opts = this.filtered();
    if (event.key === "ArrowDown") {
      event.preventDefault();
      this._activeIndex.set(Math.min(opts.length - 1, this._activeIndex() + 1));
    } else if (event.key === "ArrowUp") {
      event.preventDefault();
      this._activeIndex.set(Math.max(0, this._activeIndex() - 1));
    } else if (event.key === "Home") {
      event.preventDefault();
      this._activeIndex.set(0);
    } else if (event.key === "End") {
      event.preventDefault();
      this._activeIndex.set(opts.length - 1);
    } else if (event.key === "Enter") {
      const opt = opts[this._activeIndex()];
      if (opt && !opt.disabled) {
        event.preventDefault();
        this.selectValue(opt.value);
      } else if (this._creatable() && this._multiple() && this._search().trim()) {
        event.preventDefault();
        const term = this._search().trim();
        const curr = this._values();
        if (!curr.includes(term)) {
          const next = [...curr, term];
          this._values.set(next);
          this.valuesChange.emit(next);
        }
        this._search.set("");
      }
    }
  }

  // ── Selection ────────────────────────────────────────────────────────

  selectValue(v: SelectValue): void {
    if (this._multiple()) {
      const curr = this._values();
      const next = curr.includes(v) ? curr.filter((x) => x !== v) : [...curr, v];
      this._values.set(next);
      this.valuesChange.emit(next);
    } else {
      this._value.set(v);
      this.valueChange.emit(v);
      this.setOpen(false);
    }
  }

  onOptionClick(opt: SelectOption): void {
    if (opt.disabled) return;
    this.selectValue(opt.value);
  }

  removeTag(v: SelectValue, event: MouseEvent): void {
    event.stopPropagation();
    if (this._disabled()) return;
    const next = this._values().filter((x) => x !== v);
    this._values.set(next);
    this.valuesChange.emit(next);
  }

  onClear(event: MouseEvent): void {
    event.stopPropagation();
    if (this._disabled()) return;
    if (this._multiple()) {
      this._values.set([]);
      this.valuesChange.emit([]);
    } else {
      this._value.set(null);
      this.valueChange.emit(null);
    }
  }

  onSearchInput(event: Event): void {
    const v = (event.target as HTMLInputElement).value;
    this._search.set(v);
    this.searchChange.emit(v);
    this._activeIndex.set(0);
  }

  onScroll(event: Event): void {
    if (this._loading() || this._hasMore() === false) return;
    const el = event.currentTarget as HTMLUListElement;
    if (el.scrollHeight - el.scrollTop - el.clientHeight < 24) this.loadMore.emit();
  }

  setActive(i: number): void {
    if (i !== this._activeIndex()) this._activeIndex.set(i);
  }

  setOpen(next: boolean): void {
    if (this._open() === next) return;
    this._open.set(next);
  }

  // ── Document listeners ───────────────────────────────────────────────

  @HostListener("document:keydown.escape")
  onEscape(): void {
    if (this._open()) this.setOpen(false);
  }

  @HostListener("document:mousedown", ["$event"])
  onDocumentMousedown(event: MouseEvent): void {
    if (!this._open()) return;
    const tgt = event.target as Node | null;
    if (this.triggerRef?.nativeElement.contains(tgt as Node)) return;
    if (this.listRef?.nativeElement.contains(tgt as Node)) return;
    this.setOpen(false);
  }

  // ── Positioning ──────────────────────────────────────────────────────

  private reposition(): void {
    const anchor = this.triggerRef?.nativeElement;
    const list = this.listRef?.nativeElement;
    if (!anchor || !list) return;
    const a = anchor.getBoundingClientRect();
    const size = { width: list.offsetWidth, height: list.offsetHeight };
    const p = computePosition(a, size, this._placement(), 4);
    this.pos.set({ ...p, width: a.width });
  }

  private installScrollListeners(): void {
    this.scrollListener = () => this.reposition();
    this.resizeListener = () => this.reposition();
    window.addEventListener("scroll", this.scrollListener, true);
    window.addEventListener("resize", this.resizeListener);
  }

  private removeScrollListeners(): void {
    if (this.scrollListener) {
      window.removeEventListener("scroll", this.scrollListener, true);
      this.scrollListener = undefined;
    }
    if (this.resizeListener) {
      window.removeEventListener("resize", this.resizeListener);
      this.resizeListener = undefined;
    }
  }
}

// packages/select/src/Select.tsx
/**
 * Select — single- or multi-value combobox with optional search, clear,
 * creatable values, and infinite scroll.
 *
 * Dropdown is portal-mounted with auto-flip placement and full keyboard
 * navigation (Arrow Up/Down, Enter, Escape, Home/End).
 */
import React, {
  useCallback,
  useEffect,
  useId,
  useMemo,
  useRef,
  useState,
} from "react";
import { Portal } from "@sisyphos-ui/portal";
import {
  cx,
  computePosition,
  useEscapeKey,
  type Placement,
} from "@sisyphos-ui/core/internal";
import type { Scale, SelectOption, SelectValue } from "./types";
import "./Select.scss";

type SingleProps = {
  multiple?: false;
  value?: SelectValue | null;
  defaultValue?: SelectValue | null;
  onChange?: (value: SelectValue | null) => void;
};
type MultiProps = {
  multiple: true;
  value?: SelectValue[];
  defaultValue?: SelectValue[];
  onChange?: (value: SelectValue[]) => void;
};

export type SelectProps = {
  options: SelectOption[];
  placeholder?: string;
  label?: string;
  helperText?: React.ReactNode;
  error?: boolean;
  errorMessage?: React.ReactNode;
  disabled?: boolean;
  required?: boolean;
  size?: Scale;
  radius?: Scale;
  fullWidth?: boolean;

  searchable?: boolean;
  /** Called when the search input changes. Use for server-side filtering. */
  onSearch?: (term: string) => void;
  /** Custom option filter (client-side). Return true to include. */
  filterOption?: (option: SelectOption, term: string) => boolean;

  clearable?: boolean;
  /** Allow typing in arbitrary new values (multi only). */
  creatable?: boolean;

  loading?: boolean;
  /** Fired when the listbox scrolls near the bottom. */
  onLoadMore?: () => void;
  hasMore?: boolean;

  placement?: Placement;
  className?: string;
} & (SingleProps | MultiProps);

const ChevronIcon = ({ open }: { open: boolean }) => (
  <svg viewBox="0 0 24 24" width={18} height={18} aria-hidden="true" style={{ transform: open ? "rotate(180deg)" : undefined, transition: "transform 150ms" }}>
    <path d="M7 10l5 5 5-5z" fill="currentColor" />
  </svg>
);

const ClearIcon = () => (
  <svg viewBox="0 0 24 24" width={14} height={14} aria-hidden="true">
    <path d="M19 6.41 17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12z" fill="currentColor" />
  </svg>
);

function defaultFilter(option: SelectOption, term: string): boolean {
  if (!term) return true;
  return option.label.toLowerCase().includes(term.toLowerCase());
}

export const Select: React.FC<SelectProps> = (props) => {
  const {
    options,
    placeholder = "Select…",
    label,
    helperText,
    error = false,
    errorMessage,
    disabled = false,
    required = false,
    size = "md",
    radius = "sm",
    fullWidth = false,
    searchable = false,
    onSearch,
    filterOption = defaultFilter,
    clearable = false,
    creatable = false,
    loading = false,
    onLoadMore,
    hasMore,
    placement = "bottom-start",
    className,
    multiple,
  } = props;

  const reactId = useId();
  const listboxId = `sisyphos-select-${reactId}`;

  const isControlled = "value" in props && props.value !== undefined;
  const [internalValue, setInternalValue] = useState<SelectValue | null | SelectValue[] | undefined>(
    props.defaultValue
  );
  const rawValue = isControlled ? (props as { value: unknown }).value : internalValue;

  const selectedValues = useMemo<SelectValue[]>(() => {
    if (multiple) return Array.isArray(rawValue) ? (rawValue as SelectValue[]) : [];
    return rawValue != null && rawValue !== "" ? [rawValue as SelectValue] : [];
  }, [rawValue, multiple]);

  const [open, setOpen] = useState(false);
  const [search, setSearch] = useState("");
  const [activeIndex, setActiveIndex] = useState(-1);
  const [pos, setPos] = useState<{ left: number; top: number; placement: Placement; width: number } | null>(null);

  const triggerRef = useRef<HTMLDivElement | null>(null);
  const listRef = useRef<HTMLUListElement | null>(null);
  const searchRef = useRef<HTMLInputElement | null>(null);
  const containerRef = useRef<HTMLDivElement | null>(null);

  useEscapeKey(() => setOpen(false), open);

  // Outside-click close — exclude both the trigger and the portalled listbox.
  useEffect(() => {
    if (!open) return;
    const handler = (e: MouseEvent) => {
      const tgt = e.target as Node | null;
      if (!tgt) return;
      if (triggerRef.current?.contains(tgt)) return;
      if (listRef.current?.contains(tgt)) return;
      setOpen(false);
    };
    document.addEventListener("mousedown", handler);
    return () => document.removeEventListener("mousedown", handler);
  }, [open]);

  useEffect(() => {
    if (!open) {
      setSearch("");
      setActiveIndex(-1);
      return;
    }
    if (searchable && searchRef.current) {
      searchRef.current.focus();
    }
  }, [open, searchable]);

  useEffect(() => {
    if (!open) {
      setPos(null);
      return;
    }
    let raf = 0;
    const update = () => {
      const anchor = triggerRef.current;
      const list = listRef.current;
      if (!anchor || !list) return;
      const a = anchor.getBoundingClientRect();
      const size = { width: list.offsetWidth, height: list.offsetHeight };
      const p = computePosition(a, size, placement, 4);
      setPos({ ...p, width: a.width });
    };
    raf = requestAnimationFrame(() => requestAnimationFrame(update));
    const onWin = () => update();
    window.addEventListener("scroll", onWin, true);
    window.addEventListener("resize", onWin);
    return () => {
      cancelAnimationFrame(raf);
      window.removeEventListener("scroll", onWin, true);
      window.removeEventListener("resize", onWin);
    };
  }, [open, placement]);

  const filteredOptions = useMemo(() => {
    if (!searchable || !search) return options;
    // When `onSearch` is provided, filtering happens on the server.
    if (onSearch) return options;
    return options.filter((o) => filterOption(o, search));
  }, [options, searchable, search, onSearch, filterOption]);

  const emitChange = useCallback(
    (next: SelectValue[] | SelectValue | null) => {
      if (!isControlled) {
        setInternalValue(next as SelectValue[] | SelectValue | null);
      }
      if (multiple) {
        (props.onChange as ((v: SelectValue[]) => void) | undefined)?.((next as SelectValue[]) ?? []);
      } else {
        (props.onChange as ((v: SelectValue | null) => void) | undefined)?.(next as SelectValue | null);
      }
    },
    [isControlled, multiple, props]
  );

  const selectValue = useCallback(
    (v: SelectValue) => {
      if (multiple) {
        const curr = selectedValues;
        const next = curr.includes(v) ? curr.filter((x) => x !== v) : [...curr, v];
        emitChange(next);
      } else {
        emitChange(v);
        setOpen(false);
      }
    },
    [multiple, selectedValues, emitChange]
  );

  const handleClear = useCallback(
    (e: React.MouseEvent) => {
      e.stopPropagation();
      if (disabled) return;
      emitChange(multiple ? [] : null);
    },
    [disabled, emitChange, multiple]
  );

  const handleScroll = (e: React.UIEvent<HTMLUListElement>) => {
    if (!onLoadMore || loading || hasMore === false) return;
    const el = e.currentTarget;
    if (el.scrollHeight - el.scrollTop - el.clientHeight < 24) onLoadMore();
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (!open && (e.key === "ArrowDown" || e.key === "Enter" || e.key === " ")) {
      e.preventDefault();
      setOpen(true);
      return;
    }
    if (!open) return;
    if (e.key === "ArrowDown") {
      e.preventDefault();
      setActiveIndex((i) => Math.min(filteredOptions.length - 1, i + 1));
    } else if (e.key === "ArrowUp") {
      e.preventDefault();
      setActiveIndex((i) => Math.max(0, i - 1));
    } else if (e.key === "Home") {
      e.preventDefault();
      setActiveIndex(0);
    } else if (e.key === "End") {
      e.preventDefault();
      setActiveIndex(filteredOptions.length - 1);
    } else if (e.key === "Enter") {
      const opt = filteredOptions[activeIndex];
      if (opt && !opt.disabled) {
        e.preventDefault();
        selectValue(opt.value);
      } else if (creatable && multiple && search.trim()) {
        e.preventDefault();
        const term = search.trim();
        if (!selectedValues.includes(term)) emitChange([...selectedValues, term]);
        setSearch("");
      }
    }
  };

  const displayTags = useMemo(() => {
    if (!multiple) return null;
    return selectedValues.map((v) => {
      const opt = options.find((o) => o.value === v);
      const lbl = opt?.label ?? String(v);
      return (
        <span key={String(v)} className="sisyphos-select-tag" title={lbl}>
          {lbl}
          <button
            type="button"
            className="sisyphos-select-tag-delete"
            aria-label={`Remove ${lbl}`}
            onClick={(e) => {
              e.stopPropagation();
              emitChange(selectedValues.filter((x) => x !== v));
            }}
            disabled={disabled}
          >
            ×
          </button>
        </span>
      );
    });
  }, [multiple, selectedValues, options, emitChange, disabled]);

  const singleLabel = useMemo(() => {
    if (multiple) return null;
    const v = selectedValues[0];
    if (v === undefined) return null;
    return options.find((o) => o.value === v)?.label ?? String(v);
  }, [multiple, selectedValues, options]);

  const hasValue = selectedValues.length > 0;

  return (
    <div
      ref={containerRef}
      className={cx(
        "sisyphos-select",
        size,
        `radius-${radius}`,
        disabled && "disabled",
        error && "error",
        fullWidth && "full-width",
        className
      )}
    >
      {label && (
        <label className={cx("sisyphos-select-label", error && "error", required && "required")}>
          {label}
        </label>
      )}
      <div
        ref={triggerRef}
        className={cx("sisyphos-select-control", open && "open", hasValue && "has-value")}
        role="combobox"
        aria-expanded={open}
        aria-haspopup="listbox"
        aria-controls={open ? listboxId : undefined}
        aria-disabled={disabled || undefined}
        aria-invalid={error || undefined}
        tabIndex={disabled ? -1 : 0}
        onClick={() => !disabled && setOpen((o) => !o)}
        onKeyDown={handleKeyDown}
      >
        <div className="sisyphos-select-value">
          {multiple && selectedValues.length > 0 ? (
            <div className="sisyphos-select-tags">{displayTags}</div>
          ) : singleLabel ? (
            <span className="sisyphos-select-single">{singleLabel}</span>
          ) : (
            <span className="sisyphos-select-placeholder">{placeholder}</span>
          )}
        </div>
        {clearable && hasValue && !disabled && (
          <button
            type="button"
            aria-label="Clear selection"
            className="sisyphos-select-clear"
            onClick={handleClear}
          >
            <ClearIcon />
          </button>
        )}
        <span className="sisyphos-select-chevron"><ChevronIcon open={open} /></span>
      </div>
      {open && (
        <Portal>
          <ul
            ref={listRef}
            id={listboxId}
            role="listbox"
            aria-multiselectable={multiple || undefined}
            className={cx("sisyphos-select-list", pos?.placement ?? placement)}
            style={{
              position: "fixed",
              left: pos?.left ?? 0,
              top: pos?.top ?? 0,
              minWidth: pos?.width ?? 0,
              opacity: pos ? 1 : 0,
            }}
            onScroll={handleScroll}
          >
            {(searchable || creatable) && (
              <li className="sisyphos-select-search-row">
                <input
                  ref={searchRef}
                  className="sisyphos-select-search"
                  type="text"
                  placeholder={creatable ? "Type to add…" : "Search…"}
                  value={search}
                  onChange={(e) => {
                    setSearch(e.target.value);
                    onSearch?.(e.target.value);
                    setActiveIndex(0);
                  }}
                  onKeyDown={handleKeyDown}
                />
              </li>
            )}
            {filteredOptions.length === 0 && !loading && (
              <li className="sisyphos-select-empty">No options</li>
            )}
            {filteredOptions.map((opt, i) => {
              const checked = selectedValues.includes(opt.value);
              return (
                <li
                  key={String(opt.value)}
                  role="option"
                  aria-selected={checked}
                  aria-disabled={opt.disabled || undefined}
                  className={cx(
                    "sisyphos-select-option",
                    checked && "selected",
                    opt.disabled && "disabled",
                    i === activeIndex && "active"
                  )}
                  onMouseEnter={() => setActiveIndex(i)}
                  onClick={() => !opt.disabled && selectValue(opt.value)}
                >
                  {opt.icon && <span className="sisyphos-select-option-icon">{opt.icon}</span>}
                  <span className="sisyphos-select-option-body">
                    <span className="sisyphos-select-option-label">{opt.label}</span>
                    {opt.description && (
                      <span className="sisyphos-select-option-description">{opt.description}</span>
                    )}
                  </span>
                  {checked && <span className="sisyphos-select-option-check" aria-hidden="true">✓</span>}
                </li>
              );
            })}
            {loading && (
              <li className="sisyphos-select-loading">
                <span className="sisyphos-select-loading-spinner" aria-hidden="true" />
                <span>Loading…</span>
              </li>
            )}
          </ul>
        </Portal>
      )}
      {error && errorMessage ? (
        <span className="sisyphos-select-error" role="alert">{errorMessage}</span>
      ) : helperText ? (
        <span className="sisyphos-select-helper">{helperText}</span>
      ) : null}
    </div>
  );
};
