// packages/context-menu/src/ContextMenu.tsx
/**
 * ContextMenu — right-click menu anchored at the pointer.
 *
 * Wraps a single child. On `contextmenu` (right-click) the default browser menu
 * is suppressed and a portal-mounted menu is opened at the click coordinates
 * (clamped inside the viewport). Arrow keys navigate, Enter/Space activate,
 * Escape or outside-click close. Items are the same shape as DropdownMenu's
 * so the two feel interchangeable.
 */
import React, {
  cloneElement,
  isValidElement,
  useCallback,
  useEffect,
  useId,
  useMemo,
  useRef,
  useState,
  type ReactElement,
} from "react";
import { Portal } from "@sisyphos-ui/portal";
import { cx, useEscapeKey } from "@sisyphos-ui/core/internal";
import type { ContextMenuItem, ContextMenuAction } from "./types";
import "./ContextMenu.scss";

export interface ContextMenuProps {
  items: ContextMenuItem[];
  /** Viewport margin so the menu never sits flush against an edge. */
  margin?: number;
  disabled?: boolean;
  className?: string;
  /** Rendered when `items` is empty. */
  emptyState?: React.ReactNode;
  /** Fired when the menu opens or closes. */
  onOpenChange?: (open: boolean) => void;
  /** The trigger — any element that accepts `onContextMenu`. */
  children: ReactElement;
}

function isAction(item: ContextMenuItem): item is ContextMenuAction {
  return item.type === undefined || item.type === "action";
}

export const ContextMenu: React.FC<ContextMenuProps> = ({
  items,
  margin = 8,
  disabled = false,
  className,
  emptyState,
  onOpenChange,
  children,
}) => {
  const reactId = useId();
  const menuId = `sisyphos-context-menu-${reactId}`;

  const menuRef = useRef<HTMLUListElement | null>(null);
  const containerRef = useRef<HTMLDivElement | null>(null);
  const itemRefs = useRef<Array<HTMLLIElement | null>>([]);
  const lastTriggerEl = useRef<HTMLElement | null>(null);

  const [open, setOpenState] = useState(false);
  const [coords, setCoords] = useState<{ x: number; y: number } | null>(null);
  const [activeIndex, setActiveIndex] = useState(-1);

  const setOpen = useCallback(
    (next: boolean) => {
      setOpenState(next);
      onOpenChange?.(next);
    },
    [onOpenChange],
  );

  const actionIndexes = useMemo(
    () => items.map((item, i) => (isAction(item) && !item.disabled ? i : -1)).filter((i) => i >= 0),
    [items],
  );

  const firstFocusable = actionIndexes[0] ?? -1;
  const lastFocusable = actionIndexes[actionIndexes.length - 1] ?? -1;

  const moveFocus = useCallback(
    (direction: 1 | -1) => {
      setActiveIndex((current) => {
        const pool = actionIndexes;
        if (pool.length === 0) return -1;
        if (current === -1) return direction === 1 ? pool[0] : pool[pool.length - 1];
        const idx = pool.indexOf(current);
        if (idx === -1) return pool[0];
        return pool[(idx + direction + pool.length) % pool.length];
      });
    },
    [actionIndexes],
  );

  useEscapeKey(() => {
    setOpen(false);
    lastTriggerEl.current?.focus?.();
  }, open);

  useEffect(() => {
    if (!open) return;
    const handler = (e: MouseEvent) => {
      const tgt = e.target as Node | null;
      if (!tgt) return;
      if (containerRef.current?.contains(tgt)) return;
      setOpen(false);
    };
    // `mousedown` beats our own click on items because stopPropagation is on click.
    document.addEventListener("mousedown", handler);
    return () => document.removeEventListener("mousedown", handler);
  }, [open, setOpen]);

  // Clamp coordinates inside the viewport after the menu measures itself.
  useEffect(() => {
    if (!open || !coords) return;
    const raf = requestAnimationFrame(() => {
      const el = containerRef.current;
      if (!el) return;
      const { innerWidth, innerHeight } = window;
      const { width, height } = el.getBoundingClientRect();
      let x = coords.x;
      let y = coords.y;
      if (x + width + margin > innerWidth) x = innerWidth - width - margin;
      if (y + height + margin > innerHeight) y = innerHeight - height - margin;
      if (x < margin) x = margin;
      if (y < margin) y = margin;
      if (x !== coords.x || y !== coords.y) setCoords({ x, y });
    });
    return () => cancelAnimationFrame(raf);
  }, [open, coords, margin]);

  useEffect(() => {
    if (!open) {
      setActiveIndex(-1);
      return;
    }
    setActiveIndex(firstFocusable);
  }, [open, firstFocusable]);

  useEffect(() => {
    if (!open) return;
    const el = itemRefs.current[activeIndex];
    el?.focus?.();
  }, [activeIndex, open]);

  const handleSelect = useCallback(
    (item: ContextMenuAction, event: React.SyntheticEvent) => {
      if (item.disabled) return;
      item.onSelect(event);
      if (item.closeOnSelect !== false) {
        setOpen(false);
        lastTriggerEl.current?.focus?.();
      }
    },
    [setOpen],
  );

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === "ArrowDown") {
      e.preventDefault();
      moveFocus(1);
    } else if (e.key === "ArrowUp") {
      e.preventDefault();
      moveFocus(-1);
    } else if (e.key === "Home") {
      e.preventDefault();
      setActiveIndex(firstFocusable);
    } else if (e.key === "End") {
      e.preventDefault();
      setActiveIndex(lastFocusable);
    } else if ((e.key === "Enter" || e.key === " ") && activeIndex >= 0) {
      e.preventDefault();
      const item = items[activeIndex];
      if (item && isAction(item)) handleSelect(item, e);
    } else if (e.key === "Tab") {
      setOpen(false);
    }
  };

  if (!isValidElement(children)) {
    throw new Error("[@sisyphos-ui/context-menu] Expected a single React element as child.");
  }

  const childProps = children.props as Record<string, unknown>;

  const triggerEl = cloneElement(children as ReactElement<Record<string, unknown>>, {
    onContextMenu: (e: React.MouseEvent<HTMLElement>) => {
      (childProps.onContextMenu as ((e: React.MouseEvent) => void) | undefined)?.(e);
      if (disabled) return;
      e.preventDefault();
      lastTriggerEl.current = e.currentTarget;
      setCoords({ x: e.clientX, y: e.clientY });
      setOpen(true);
    },
  });

  return (
    <>
      {triggerEl}
      {open && coords && (
        <Portal>
          <div
            ref={containerRef}
            className={cx("sisyphos-context-menu", className)}
            style={{ position: "fixed", left: coords.x, top: coords.y }}
            role="presentation"
          >
            {items.length === 0 && emptyState ? (
              <div className="sisyphos-context-menu-empty" role="note">
                {emptyState}
              </div>
            ) : (
              <ul
                ref={menuRef}
                id={menuId}
                role="menu"
                className="sisyphos-context-menu-list"
                onKeyDown={handleKeyDown}
              >
                {items.map((item, i) => {
                  if (item.type === "separator") {
                    return (
                      <li
                        key={item.key ?? `sep-${i}`}
                        className="sisyphos-context-menu-separator"
                        role="separator"
                      />
                    );
                  }
                  if (item.type === "label") {
                    return (
                      <li
                        key={item.key ?? `label-${i}`}
                        className="sisyphos-context-menu-label"
                        role="presentation"
                      >
                        {item.label}
                      </li>
                    );
                  }
                  const action = item;
                  return (
                    <li
                      ref={(el) => {
                        itemRefs.current[i] = el;
                      }}
                      key={action.key ?? `item-${i}`}
                      role="menuitem"
                      tabIndex={activeIndex === i ? 0 : -1}
                      aria-disabled={action.disabled || undefined}
                      className={cx(
                        "sisyphos-context-menu-item",
                        action.destructive && "destructive",
                        action.disabled && "disabled",
                      )}
                      onMouseEnter={() => setActiveIndex(i)}
                      onClick={(e) => handleSelect(action, e)}
                    >
                      {action.icon && (
                        <span className="sisyphos-context-menu-item-icon">{action.icon}</span>
                      )}
                      <span className="sisyphos-context-menu-item-label">{action.label}</span>
                      {action.shortcut && (
                        <span className="sisyphos-context-menu-item-shortcut">{action.shortcut}</span>
                      )}
                    </li>
                  );
                })}
              </ul>
            )}
          </div>
        </Portal>
      )}
    </>
  );
};

ContextMenu.displayName = "ContextMenu";

// packages/angular/src/context-menu/context-menu.component.ts
/**
 * ContextMenu — Angular 18 standalone right-click menu anchored at the
 * pointer. Wraps a single child as its trigger; on `contextmenu` the
 * default browser menu is suppressed and a portal-style menu opens at the
 * click coordinates (clamped inside the viewport).
 *
 * Item shape matches `DropdownMenuItem` exactly — the two components are
 * interchangeable on the consumer side.
 *
 * @example
 *   <sui-context-menu [items]="rowActions">
 *     <div class="row">{{ row.name }}</div>
 *   </sui-context-menu>
 */
import type { ElementRef, OnDestroy } from "@angular/core";
import {
  ChangeDetectionStrategy,
  Component,
  EventEmitter,
  HostListener,
  Input,
  Output,
  ViewChild,
  computed,
  signal,
} from "@angular/core";
import { isContextMenuAction, type ContextMenuItem } from "./types";

let menuCounter = 0;

@Component({
  selector: "sui-context-menu",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <span
      #triggerWrap
      class="sisyphos-context-menu-anchor"
      style="display:contents;"
      (contextmenu)="onContextMenu($event)"
    >
      <ng-content />
    </span>
    @if (open()) {
      <div
        #panel
        [class]="panelClasses()"
        [id]="menuId"
        [style.position]="'fixed'"
        [style.left.px]="coords()?.x ?? 0"
        [style.top.px]="coords()?.y ?? 0"
        [style.opacity]="coords() ? 1 : 0"
        [style.z-index]="1100"
      >
        @if (items().length === 0 && hasEmpty) {
          <div class="sisyphos-context-menu-empty" role="note">
            <ng-content select="[menu-empty]" />
          </div>
        } @else {
          <ul
            #list
            role="menu"
            class="sisyphos-context-menu-list"
            (keydown)="onMenuKeydown($event)"
          >
            @for (item of items(); track $index; let i = $index) {
              @if (item.type === "separator") {
                <li class="sisyphos-context-menu-separator" role="separator"></li>
              } @else if (item.type === "label") {
                <li class="sisyphos-context-menu-label" role="presentation">{{ item.label }}</li>
              } @else {
                <li
                  role="menuitem"
                  [tabindex]="activeIndex() === i ? 0 : -1"
                  [attr.aria-disabled]="item.disabled || null"
                  [class]="itemClasses(item)"
                  [attr.data-index]="i"
                  (mouseenter)="setActive(i)"
                  (click)="select(item, $event)"
                >
                  @if (item.icon) {
                    <span class="sisyphos-context-menu-item-icon">{{ item.icon }}</span>
                  }
                  <span class="sisyphos-context-menu-item-label">{{ item.label }}</span>
                  @if (item.shortcut) {
                    <span class="sisyphos-context-menu-item-shortcut">{{ item.shortcut }}</span>
                  }
                </li>
              }
            }
          </ul>
        }
      </div>
    }
  `,
})
export class ContextMenu implements OnDestroy {
  readonly menuId = `sisyphos-context-menu-${++menuCounter}`;

  private readonly _items = signal<ContextMenuItem[]>([]);
  private readonly _open = signal(false);
  private readonly _disabled = signal(false);
  private readonly _margin = signal(8);
  private readonly _coords = signal<{ x: number; y: number } | null>(null);
  private readonly _activeIndex = signal(-1);

  readonly items = this._items.asReadonly();
  readonly open = this._open.asReadonly();
  readonly coords = this._coords.asReadonly();
  readonly activeIndex = this._activeIndex.asReadonly();

  hasEmpty = false;

  @Input("items") set itemsInput(v: ContextMenuItem[]) {
    this._items.set(v ?? []);
  }
  @Input("disabled") set disabledInput(v: boolean) {
    this._disabled.set(v);
  }
  @Input("margin") set marginInput(v: number) {
    this._margin.set(v);
  }
  @Input("hasEmpty") set hasEmptyInput(v: boolean) {
    this.hasEmpty = v;
  }

  @Output() readonly openChange = new EventEmitter<boolean>();

  @ViewChild("triggerWrap") triggerWrapRef?: ElementRef<HTMLSpanElement>;
  @ViewChild("panel") panelRef?: ElementRef<HTMLDivElement>;
  @ViewChild("list") listRef?: ElementRef<HTMLUListElement>;

  private lastTrigger: HTMLElement | null = null;

  readonly panelClasses = computed(() => `sisyphos-context-menu`);

  readonly actionIndexes = computed(() =>
    this._items()
      .map((it, i) => (isContextMenuAction(it) && !it.disabled ? i : -1))
      .filter((i) => i >= 0)
  );

  itemClasses(item: ContextMenuItem): string {
    if (!isContextMenuAction(item)) return "";
    return [
      "sisyphos-context-menu-item",
      item.destructive && "destructive",
      item.disabled && "disabled",
    ]
      .filter(Boolean)
      .join(" ");
  }

  ngOnDestroy(): void {
    /* no-op */
  }

  // ── trigger ──────────────────────────────────────────────────────────

  onContextMenu(event: MouseEvent): void {
    if (this._disabled()) return;
    event.preventDefault();
    this.lastTrigger = event.target as HTMLElement | null;
    this._coords.set({ x: event.clientX, y: event.clientY });
    this.setOpen(true);
    // Clamp inside viewport after the panel measures itself.
    queueMicrotask(() =>
      requestAnimationFrame(() => {
        const el = this.panelRef?.nativeElement;
        const c = this._coords();
        if (!el || !c) return;
        const m = this._margin();
        const { innerWidth, innerHeight } = window;
        const { width, height } = el.getBoundingClientRect();
        let x = c.x;
        let y = c.y;
        if (x + width + m > innerWidth) x = innerWidth - width - m;
        if (y + height + m > innerHeight) y = innerHeight - height - m;
        if (x < m) x = m;
        if (y < m) y = m;
        if (x !== c.x || y !== c.y) this._coords.set({ x, y });
      })
    );
  }

  setOpen(next: boolean): void {
    if (this._open() === next) return;
    this._open.set(next);
    this.openChange.emit(next);
    if (next) {
      this._activeIndex.set(this.actionIndexes()[0] ?? -1);
    } else {
      this._activeIndex.set(-1);
    }
  }

  // ── menu interactions ────────────────────────────────────────────────

  select(item: ContextMenuItem, event: Event): void {
    if (!isContextMenuAction(item) || item.disabled) return;
    item.onSelect(event);
    if (item.closeOnSelect !== false) {
      this.setOpen(false);
      this.lastTrigger?.focus?.();
    }
  }

  setActive(i: number): void {
    if (i !== this._activeIndex()) this._activeIndex.set(i);
  }

  onMenuKeydown(event: KeyboardEvent): void {
    const pool = this.actionIndexes();
    if (event.key === "ArrowDown") {
      event.preventDefault();
      this.moveFocus(1, pool);
    } else if (event.key === "ArrowUp") {
      event.preventDefault();
      this.moveFocus(-1, pool);
    } else if (event.key === "Home") {
      event.preventDefault();
      if (pool.length) this._activeIndex.set(pool[0]!);
    } else if (event.key === "End") {
      event.preventDefault();
      if (pool.length) this._activeIndex.set(pool[pool.length - 1]!);
    } else if ((event.key === "Enter" || event.key === " ") && this._activeIndex() >= 0) {
      event.preventDefault();
      const item = this._items()[this._activeIndex()];
      if (item) this.select(item, event);
    } else if (event.key === "Tab") {
      this.setOpen(false);
    }
  }

  private moveFocus(direction: 1 | -1, pool: number[]): void {
    if (pool.length === 0) return;
    const current = this._activeIndex();
    if (current === -1) {
      this._activeIndex.set(direction === 1 ? pool[0]! : pool[pool.length - 1]!);
      return;
    }
    const idx = pool.indexOf(current);
    if (idx === -1) {
      this._activeIndex.set(pool[0]!);
      return;
    }
    const next = pool[(idx + direction + pool.length) % pool.length]!;
    this._activeIndex.set(next);
  }

  @HostListener("document:keydown.escape")
  onEscape(): void {
    if (!this._open()) return;
    this.setOpen(false);
    this.lastTrigger?.focus?.();
  }

  @HostListener("document:mousedown", ["$event"])
  onDocumentMousedown(event: MouseEvent): void {
    if (!this._open()) return;
    const tgt = event.target as Node | null;
    const panel = this.panelRef?.nativeElement;
    if (panel?.contains(tgt as Node)) return;
    this.setOpen(false);
  }
}
