// packages/react/src/avatar/Avatar.tsx
/**
 * Avatar — image avatar with graceful fallback to initials, custom content, or
 * semantic-colored placeholder when the image is missing or errors.
 */
import React, { useState, useEffect, useMemo } from "react";
import { cx } from "@sisyphos-ui/core/internal";
import { CN, DEFAULTS, type AvatarColor, type AvatarShape, type Scale } from "./constants";
import { getInitials } from "./initials";
import "./Avatar.scss";

export interface AvatarProps extends Omit<React.HTMLAttributes<HTMLSpanElement>, "color"> {
  /** Image source. Falls back to initials/fallback when omitted or on load error. */
  src?: string;
  /** Alt text. Required when `src` is set for accessibility. */
  alt?: string;
  /** Display name — used to derive initials when `src` is missing/errored. */
  name?: string;
  /** Max initials derived from `name`. Defaults to 2. */
  initialsMax?: number;
  /** Override fallback content (icon, custom text). Takes precedence over derived initials. */
  fallback?: React.ReactNode;
  size?: Scale;
  /** Semantic color (applied to fallback background). */
  color?: AvatarColor;
  /** Shape variant. `circular` (default), `rounded` (slight radius), `square`. */
  shape?: AvatarShape;
}

export const Avatar = React.forwardRef<HTMLSpanElement, AvatarProps>(function Avatar(
  {
    src,
    alt,
    name,
    initialsMax = 2,
    fallback,
    size = DEFAULTS.size,
    color = DEFAULTS.color,
    shape = DEFAULTS.shape,
    className,
    children,
    ...rest
  },
  ref
) {
  const [imgFailed, setImgFailed] = useState(false);

  useEffect(() => {
    setImgFailed(false);
  }, [src]);

  const initials = useMemo(() => getInitials(name, initialsMax), [name, initialsMax]);
  const showImage = src && !imgFailed;

  const rootClass = cx(CN.root, size, color, shape, className);

  return (
    <span ref={ref} className={rootClass} {...rest}>
      {showImage ? (
        <img
          className={CN.image}
          src={src}
          alt={alt ?? name ?? ""}
          onError={() => setImgFailed(true)}
          draggable={false}
        />
      ) : (
        <span className={CN.fallback} aria-label={alt ?? name}>
          {children ?? fallback ?? initials}
        </span>
      )}
    </span>
  );
});

Avatar.displayName = "Avatar";

// packages/vue/src/avatar/Avatar.vue
<script setup lang="ts">
/**
 * Avatar — Vue 3 binding. Image with graceful fallback to initials or
 * custom slot. Mirrors the React binding's `getInitials` rule exactly.
 */
import { computed, ref, watch } from "vue";

interface Props {
  /** Image source. Falls back to initials/slot when omitted or on load error. */
  src?: string;
  /** Alt text. Required when `src` is set for accessibility. */
  alt?: string;
  /** Display name — used to derive initials when `src` is missing/errored. */
  name?: string;
  /** Max initials derived from `name`. Defaults to 2. */
  initialsMax?: number;
  /** Override fallback content (string). Use the default slot for richer markup. */
  fallback?: string;
  size?: "xs" | "sm" | "md" | "lg" | "xl";
  /** Semantic color applied to the fallback background. */
  color?: "primary" | "success" | "error" | "warning" | "info" | "neutral";
  /** Shape variant. `circular` (default), `rounded`, `square`. */
  shape?: "circular" | "rounded" | "square";
}

const props = withDefaults(defineProps<Props>(), {
  initialsMax: 2,
  size: "md",
  color: "neutral",
  shape: "circular",
});

function getInitials(name: string | undefined, max: number): string {
  if (!name) return "";
  const parts = name.trim().split(/\s+/).filter(Boolean);
  if (parts.length === 0) return "";
  return parts
    .slice(0, max)
    .map((p) => p[0]?.toUpperCase() ?? "")
    .join("");
}

const imgFailed = ref(false);
watch(
  () => props.src,
  () => {
    imgFailed.value = false;
  }
);

const showImage = computed(() => Boolean(props.src) && !imgFailed.value);
const initials = computed(() => getInitials(props.name, props.initialsMax));

const rootClasses = computed(() => [
  "sisyphos-avatar",
  props.size,
  props.color,
  props.shape,
]);
</script>

<template>
  <span :class="rootClasses">
    <img
      v-if="showImage"
      class="sisyphos-avatar-image"
      :src="src"
      :alt="alt ?? name ?? ''"
      draggable="false"
      @error="imgFailed = true"
    />
    <span v-else class="sisyphos-avatar-fallback" :aria-label="alt ?? name">
      <slot>{{ fallback ?? initials }}</slot>
    </span>
  </span>
</template>

<style src="./Avatar.scss"></style>
