// packages/breadcrumb/src/Breadcrumb.tsx
/**
 * Breadcrumb — navigation trail with optional middle-collapse (via `maxItems`)
 * and a customizable separator.
 *
 * Rendered inside a `<nav aria-label="breadcrumb">` and marks the final item
 * with `aria-current="page"`.
 */
import React from "react";
import { cx } from "@sisyphos-ui/core/internal";
import "./Breadcrumb.scss";

export interface BreadcrumbItem {
  label: React.ReactNode;
  href?: string;
  onClick?: (event: React.MouseEvent) => void;
  icon?: React.ReactNode;
  key?: string;
}

export interface BreadcrumbProps extends React.HTMLAttributes<HTMLElement> {
  /** Ordered list of breadcrumb entries. The last item is treated as the current page. */
  items: BreadcrumbItem[];
  /** Custom separator rendered between items. Defaults to "/". */
  separator?: React.ReactNode;
  /**
   * When set, collapses middle items into a `…` when total exceeds this count.
   * Keeps `itemsBeforeCollapse` before and `itemsAfterCollapse` after the ellipsis.
   */
  maxItems?: number;
  /** Items kept before the ellipsis when collapsing. */
  itemsBeforeCollapse?: number;
  /** Items kept after the ellipsis when collapsing. */
  itemsAfterCollapse?: number;
}

const DefaultSeparator = () => <span aria-hidden="true">/</span>;

function collapseItems(
  items: BreadcrumbItem[],
  max: number,
  before: number,
  after: number
): Array<BreadcrumbItem | { ellipsis: true }> {
  if (items.length <= max) return items;
  return [...items.slice(0, before), { ellipsis: true }, ...items.slice(items.length - after)];
}

export const Breadcrumb = React.forwardRef<HTMLElement, BreadcrumbProps>(function Breadcrumb(
  {
    items,
    separator = <DefaultSeparator />,
    maxItems,
    itemsBeforeCollapse = 1,
    itemsAfterCollapse = 1,
    className,
    ...rest
  },
  ref
) {
  const rendered =
    typeof maxItems === "number"
      ? collapseItems(items, maxItems, itemsBeforeCollapse, itemsAfterCollapse)
      : items;

  return (
    <nav
      ref={ref}
      aria-label="breadcrumb"
      className={cx("sisyphos-breadcrumb", className)}
      {...rest}
    >
      <ol className="sisyphos-breadcrumb-list">
        {rendered.map((node, idx) => {
          const isLast = idx === rendered.length - 1;
          const sep = !isLast && (
            <li aria-hidden="true" className="sisyphos-breadcrumb-separator">
              {separator}
            </li>
          );

          if ("ellipsis" in node) {
            return (
              <React.Fragment key={`ellipsis-${idx}`}>
                <li className="sisyphos-breadcrumb-ellipsis" aria-hidden="true">
                  …
                </li>
                {sep}
              </React.Fragment>
            );
          }

          const item = node;
          const content = (
            <>
              {item.icon && <span className="sisyphos-breadcrumb-icon">{item.icon}</span>}
              <span>{item.label}</span>
            </>
          );

          let body: React.ReactNode;
          if (isLast) {
            body = (
              <span className="sisyphos-breadcrumb-current" aria-current="page">
                {content}
              </span>
            );
          } else if (item.href) {
            body = (
              <a className="sisyphos-breadcrumb-link" href={item.href} onClick={item.onClick}>
                {content}
              </a>
            );
          } else if (item.onClick) {
            body = (
              <button
                type="button"
                className="sisyphos-breadcrumb-link as-button"
                onClick={item.onClick}
              >
                {content}
              </button>
            );
          } else {
            body = <span className="sisyphos-breadcrumb-text">{content}</span>;
          }

          return (
            <React.Fragment key={item.key ?? idx}>
              <li className="sisyphos-breadcrumb-item">{body}</li>
              {sep}
            </React.Fragment>
          );
        })}
      </ol>
    </nav>
  );
});

Breadcrumb.displayName = "Breadcrumb";

// packages/vue/src/breadcrumb/Breadcrumb.vue
<script setup lang="ts">
/**
 * Breadcrumb — Vue 3 binding. Navigation trail with optional middle-collapse
 * via `maxItems` and a customizable separator slot.
 */
import { computed } from "vue";

export interface BreadcrumbItem {
  label: string;
  href?: string;
  onClick?: (event: MouseEvent) => void;
  icon?: unknown;
  key?: string;
}

interface Props {
  items: BreadcrumbItem[];
  /** Items kept before the ellipsis when collapsing. */
  itemsBeforeCollapse?: number;
  /** Items kept after the ellipsis when collapsing. */
  itemsAfterCollapse?: number;
  /** When set, collapses middle items into a `…` when total exceeds this count. */
  maxItems?: number;
  /** Plain string separator. Use the `separator` slot for richer content. */
  separator?: string;
}

const props = withDefaults(defineProps<Props>(), {
  itemsBeforeCollapse: 1,
  itemsAfterCollapse: 1,
});

interface EllipsisNode {
  ellipsis: true;
}

const rendered = computed<Array<BreadcrumbItem | EllipsisNode>>(() => {
  if (typeof props.maxItems !== "number" || props.items.length <= props.maxItems) {
    return props.items;
  }
  return [
    ...props.items.slice(0, props.itemsBeforeCollapse),
    { ellipsis: true },
    ...props.items.slice(props.items.length - props.itemsAfterCollapse),
  ];
});
</script>

<template>
  <nav aria-label="breadcrumb" class="sisyphos-breadcrumb">
    <ol class="sisyphos-breadcrumb-list">
      <template v-for="(node, idx) in rendered" :key="(node as BreadcrumbItem).key ?? idx">
        <li v-if="'ellipsis' in node" class="sisyphos-breadcrumb-ellipsis" aria-hidden="true">
          …
        </li>
        <li v-else class="sisyphos-breadcrumb-item">
          <span
            v-if="idx === rendered.length - 1"
            class="sisyphos-breadcrumb-current"
            aria-current="page"
          >
            <span v-if="node.icon" class="sisyphos-breadcrumb-icon"><slot name="icon" :item="node" /></span>
            <span>{{ node.label }}</span>
          </span>
          <a
            v-else-if="node.href"
            class="sisyphos-breadcrumb-link"
            :href="node.href"
            @click="node.onClick"
          >
            <span v-if="node.icon" class="sisyphos-breadcrumb-icon"><slot name="icon" :item="node" /></span>
            <span>{{ node.label }}</span>
          </a>
          <button
            v-else-if="node.onClick"
            type="button"
            class="sisyphos-breadcrumb-link as-button"
            @click="node.onClick"
          >
            <span v-if="node.icon" class="sisyphos-breadcrumb-icon"><slot name="icon" :item="node" /></span>
            <span>{{ node.label }}</span>
          </button>
          <span v-else class="sisyphos-breadcrumb-text">
            <span v-if="node.icon" class="sisyphos-breadcrumb-icon"><slot name="icon" :item="node" /></span>
            <span>{{ node.label }}</span>
          </span>
        </li>
        <li
          v-if="idx < rendered.length - 1"
          aria-hidden="true"
          class="sisyphos-breadcrumb-separator"
        >
          <slot name="separator">{{ separator ?? "/" }}</slot>
        </li>
      </template>
    </ol>
  </nav>
</template>

<style src="./Breadcrumb.scss"></style>
