// packages/textarea/src/Textarea.tsx
/**
 * Textarea — multiline text input with variants, sizes, optional auto-resize,
 * character counter, and error state. Works controlled or uncontrolled.
 */
import React, { useState, useRef, useMemo, useCallback, useId } from "react";
import { cx, mergeRefs } from "@sisyphos-ui/core/internal";
import { CN, DEFAULTS, type Scale } from "./constants";
import { useAutosize } from "./use-autosize";
import "./Textarea.scss";

export interface TextareaProps
  extends Omit<React.TextareaHTMLAttributes<HTMLTextAreaElement>, "size" | "cols"> {
  variant?: "standard" | "outlined" | "underline";
  size?: Scale;
  radius?: Scale;
  /** Field label rendered as a `<label>` linked via `id`/`htmlFor`. */
  label?: string;
  /** Marks the field as invalid for styling and ARIA. */
  error?: boolean;
  /** Message rendered below the field when `error` is true. */
  errorMessage?: string;
  /** Show a `current / maxLength` counter. Requires `maxLength`. */
  showCharacterCount?: boolean;
  /** Auto-resize height to content, clamped between `minRows` and `maxRows`. */
  autoResize?: boolean;
  /** Minimum visible rows when `autoResize` is enabled. */
  minRows?: number;
  /** Maximum visible rows when `autoResize` is enabled. */
  maxRows?: number;
  /** Native CSS resize handle direction. */
  resize?: "none" | "vertical" | "horizontal" | "both";
  fullWidth?: boolean;
}

export const Textarea = React.forwardRef<HTMLTextAreaElement, TextareaProps>(
  function Textarea(
    {
      label,
      error = false,
      errorMessage,
      variant = DEFAULTS.variant,
      size = DEFAULTS.size,
      radius = DEFAULTS.radius,
      maxLength,
      showCharacterCount = false,
      autoResize = false,
      minRows = DEFAULTS.minRows,
      maxRows,
      resize = DEFAULTS.resize as TextareaProps["resize"],
      fullWidth = false,
      disabled = false,
      readOnly = false,
      required = false,
      className = "",
      id,
      onFocus,
      onBlur,
      onChange,
      value: valueProp,
      defaultValue,
      ...rest
    },
    ref
  ) {
    const [focused, setFocused] = useState(false);
    const textareaRef = useRef<HTMLTextAreaElement>(null);
    const isControlled = valueProp !== undefined;
    const [internal, setInternal] = useState(() => String(defaultValue ?? ""));
    const displayValue = isControlled ? String(valueProp ?? "") : internal;

    const generatedId = useId();
    const fieldId = id ?? `sisyphos-textarea-${generatedId}`;
    const showCount = Boolean(maxLength && showCharacterCount);

    useAutosize(textareaRef, displayValue, { enabled: autoResize, minRows, maxRows });

    const containerClass = useMemo(
      () =>
        cx(
          CN.container,
          focused && "focused",
          error && "error",
          disabled && "disabled",
          readOnly && "read-only",
          fullWidth && "full-width",
          className
        ),
      [focused, error, disabled, readOnly, fullWidth, className]
    );

    const textareaClass = useMemo(
      () =>
        cx(CN.textarea, variant, CN.size(size), CN.radius(radius), error && "error"),
      [variant, size, radius, error]
    );

    const handleFocus = useCallback(
      (e: React.FocusEvent<HTMLTextAreaElement>) => {
        setFocused(true);
        onFocus?.(e);
      },
      [onFocus]
    );
    const handleBlur = useCallback(
      (e: React.FocusEvent<HTMLTextAreaElement>) => {
        setFocused(false);
        onBlur?.(e);
      },
      [onBlur]
    );
    const handleChange = useCallback(
      (e: React.ChangeEvent<HTMLTextAreaElement>) => {
        if (!isControlled) setInternal(e.target.value);
        onChange?.(e);
      },
      [isControlled, onChange]
    );

    const describedBy =
      [
        error && errorMessage ? `${fieldId}-error` : null,
        showCount ? `${fieldId}-count` : null,
      ]
        .filter(Boolean)
        .join(" ") || undefined;

    return (
      <div className={containerClass}>
        {label && (
          <label
            htmlFor={fieldId}
            className={cx(
              CN.label,
              focused && "focused",
              error && "error",
              disabled && "disabled",
              required && "required"
            )}
          >
            {label}
          </label>
        )}
        <textarea
          {...rest}
          ref={mergeRefs(textareaRef, ref)}
          id={fieldId}
          className={textareaClass}
          value={isControlled ? displayValue : undefined}
          defaultValue={isControlled ? undefined : defaultValue}
          disabled={disabled}
          readOnly={readOnly}
          required={required}
          maxLength={maxLength}
          style={{ resize, ...rest.style }}
          aria-invalid={error || undefined}
          aria-describedby={describedBy}
          onFocus={handleFocus}
          onBlur={handleBlur}
          onChange={handleChange}
        />
        {error && errorMessage && (
          <span id={`${fieldId}-error`} className={CN.error} role="alert">
            {errorMessage}
          </span>
        )}
        {showCount && !error && (
          <span id={`${fieldId}-count`} className={CN.characterCount}>
            {displayValue.length} / {maxLength}
          </span>
        )}
      </div>
    );
  }
);

Textarea.displayName = "Textarea";

// packages/vue/src/textarea/Textarea.vue
<script setup lang="ts">
/**
 * Textarea — Vue 3 binding. v-model + label + error + character count +
 * autosize. Mirrors the React Textarea API surface.
 */
import { computed, nextTick, ref, useId, watch } from "vue";

interface Props {
  modelValue?: string;
  variant?: "standard" | "outlined" | "underline";
  size?: "xs" | "sm" | "md" | "lg" | "xl";
  radius?: "xs" | "sm" | "md" | "lg" | "xl";
  label?: string;
  placeholder?: string;
  error?: boolean;
  errorMessage?: string;
  disabled?: boolean;
  readonly?: boolean;
  required?: boolean;
  maxLength?: number;
  showCharacterCount?: boolean;
  fullWidth?: boolean;
  /** When true, the textarea grows with content between minRows and maxRows. */
  autoResize?: boolean;
  minRows?: number;
  maxRows?: number;
  /** CSS resize behavior. Defaults to "vertical" — set "none" to lock when autoResize is on. */
  resize?: "none" | "vertical" | "horizontal" | "both";
  id?: string;
}

const props = withDefaults(defineProps<Props>(), {
  variant: "standard",
  size: "md",
  error: false,
  disabled: false,
  readonly: false,
  required: false,
  showCharacterCount: false,
  fullWidth: false,
  autoResize: false,
  minRows: 3,
  maxRows: 12,
  resize: "vertical",
});

const emit = defineEmits<{
  (e: "update:modelValue", value: string): void;
}>();

const textareaRef = ref<HTMLTextAreaElement | null>(null);
const reactId = useId();
const inputId = computed(() => props.id ?? `sisyphos-textarea-${reactId}`);
const focused = ref(false);
const value = computed(() => props.modelValue ?? "");

function autosize() {
  if (!props.autoResize) return;
  const node = textareaRef.value;
  if (!node) return;
  node.style.height = "auto";
  const lineHeight = parseFloat(getComputedStyle(node).lineHeight || "16");
  const min = lineHeight * props.minRows;
  const max = lineHeight * props.maxRows;
  const next = Math.max(min, Math.min(max, node.scrollHeight));
  node.style.height = `${next}px`;
  node.style.overflowY = node.scrollHeight > max ? "auto" : "hidden";
}

watch(value, () => nextTick(autosize), { immediate: true });

function onInput(e: Event) {
  emit("update:modelValue", (e.target as HTMLTextAreaElement).value);
}

const containerClasses = computed(() => [
  "sisyphos-textarea-container",
  focused.value && "focused",
  props.error && "error",
  props.disabled && "disabled",
  props.fullWidth && "full-width",
]);

const textareaClasses = computed(() => [
  "sisyphos-textarea",
  props.variant,
  props.size,
  props.radius && `radius-${props.radius}`,
  focused.value && "focused",
  props.error && "error",
]);

const showCount = computed(() => Boolean(props.maxLength && props.showCharacterCount));
const textareaStyle = computed(() => ({ resize: props.resize }));
</script>

<template>
  <div :class="containerClasses">
    <label v-if="label" :for="inputId" class="sisyphos-textarea-label">
      {{ label }}
    </label>
    <textarea
      :id="inputId"
      ref="textareaRef"
      :class="textareaClasses"
      :style="textareaStyle"
      :value="value"
      :placeholder="placeholder"
      :disabled="disabled"
      :readonly="readonly"
      :required="required"
      :maxlength="maxLength"
      :rows="autoResize ? minRows : undefined"
      :aria-invalid="error || undefined"
      @input="onInput"
      @focus="focused = true"
      @blur="focused = false"
    />
    <span v-if="error && errorMessage" class="sisyphos-textarea-error" role="alert">
      {{ errorMessage }}
    </span>
    <span v-else-if="showCount" class="sisyphos-textarea-character-count">
      {{ value.length }} / {{ maxLength }}
    </span>
  </div>
</template>

<style src="./Textarea.scss"></style>
