// packages/table/src/Pagination.tsx
/**
 * Pagination — prev/next + numeric pages with ellipsis elision. Designed as a
 * companion to `Table` but usable anywhere a pager is needed.
 */
import React from "react";
import { cx } from "@sisyphos-ui/core/internal";
import "./Table.scss";

export interface PaginationProps {
  /** Current page (1-based). */
  page: number;
  /** Total number of pages. */
  pageCount: number;
  /** Called with the next page when a page control is activated. */
  onPageChange: (page: number) => void;
  /** Number of sibling pages to show on each side of the current page. Default 1. */
  siblings?: number;
  /** Number of edge pages always shown. Default 1. */
  boundaries?: number;
  size?: "sm" | "md" | "lg";
  className?: string;
}

export function getPageItems(page: number, pageCount: number, siblings = 1, boundaries = 1): Array<number | "ellipsis"> {
  const total = pageCount;
  if (total <= 1) return [1];
  const totalNumbers = boundaries * 2 + siblings * 2 + 3;
  if (totalNumbers >= total) {
    return Array.from({ length: total }, (_, i) => i + 1);
  }

  const left = Math.max(page - siblings, boundaries + 2);
  const right = Math.min(page + siblings, total - boundaries - 1);

  const items: Array<number | "ellipsis"> = [];
  for (let i = 1; i <= boundaries; i++) items.push(i);
  if (left > boundaries + 1) items.push("ellipsis");
  for (let i = left; i <= right; i++) items.push(i);
  if (right < total - boundaries) items.push("ellipsis");
  for (let i = total - boundaries + 1; i <= total; i++) items.push(i);
  return items;
}

const Chevron: React.FC<{ direction: "left" | "right" }> = ({ direction }) => (
  <svg viewBox="0 0 16 16" width="14" height="14" aria-hidden="true">
    <path d={direction === "left" ? "M10 4l-4 4 4 4" : "M6 4l4 4-4 4"} fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
  </svg>
);

export const Pagination: React.FC<PaginationProps> = ({
  page,
  pageCount,
  onPageChange,
  siblings = 1,
  boundaries = 1,
  size = "md",
  className,
}) => {
  const items = getPageItems(page, pageCount, siblings, boundaries);
  return (
    <nav className={cx("sisyphos-pagination", size, className)} aria-label="Pagination">
      <button
        type="button"
        className="sisyphos-pagination-arrow"
        onClick={() => onPageChange(page - 1)}
        disabled={page <= 1}
        aria-label="Previous page"
      >
        <Chevron direction="left" />
      </button>
      <ul className="sisyphos-pagination-list">
        {items.map((it, i) =>
          it === "ellipsis" ? (
            <li key={`e-${i}`} className="sisyphos-pagination-ellipsis" aria-hidden="true">…</li>
          ) : (
            <li key={it}>
              <button
                type="button"
                className={cx("sisyphos-pagination-page", it === page && "active")}
                onClick={() => onPageChange(it)}
                aria-current={it === page ? "page" : undefined}
              >
                {it}
              </button>
            </li>
          )
        )}
      </ul>
      <button
        type="button"
        className="sisyphos-pagination-arrow"
        onClick={() => onPageChange(page + 1)}
        disabled={page >= pageCount}
        aria-label="Next page"
      >
        <Chevron direction="right" />
      </button>
    </nav>
  );
};

// packages/angular/src/table/pagination.component.ts
/**
 * Pagination — Angular 18 standalone prev/next + numeric pages with ellipsis
 * elision. Designed as a companion to `<sui-table>` but usable anywhere a
 * pager is needed. Pure same logic as the React/Vue versions.
 */
import {
  ChangeDetectionStrategy,
  Component,
  EventEmitter,
  Input as NgInput,
  Output,
  computed,
  signal,
} from "@angular/core";

export function getPageItems(
  page: number,
  pageCount: number,
  siblings = 1,
  boundaries = 1
): Array<number | "ellipsis"> {
  const total = pageCount;
  if (total <= 1) return [1];
  const totalNumbers = boundaries * 2 + siblings * 2 + 3;
  if (totalNumbers >= total) {
    return Array.from({ length: total }, (_, i) => i + 1);
  }

  const left = Math.max(page - siblings, boundaries + 2);
  const right = Math.min(page + siblings, total - boundaries - 1);

  const items: Array<number | "ellipsis"> = [];
  for (let i = 1; i <= boundaries; i++) items.push(i);
  if (left > boundaries + 1) items.push("ellipsis");
  for (let i = left; i <= right; i++) items.push(i);
  if (right < total - boundaries) items.push("ellipsis");
  for (let i = total - boundaries + 1; i <= total; i++) items.push(i);
  return items;
}

@Component({
  selector: "sui-pagination",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <nav [class]="rootClasses()" aria-label="Pagination">
      <button
        type="button"
        class="sisyphos-pagination-arrow"
        [disabled]="page() <= 1"
        aria-label="Previous page"
        (click)="goTo(page() - 1)"
      >
        <svg viewBox="0 0 16 16" width="14" height="14" aria-hidden="true">
          <path d="M10 4l-4 4 4 4" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" />
        </svg>
      </button>
      <ul class="sisyphos-pagination-list">
        @for (it of items(); track $index) {
          @if (it === 'ellipsis') {
            <li class="sisyphos-pagination-ellipsis" aria-hidden="true">…</li>
          } @else {
            <li>
              <button
                type="button"
                [class]="'sisyphos-pagination-page' + (it === page() ? ' active' : '')"
                [attr.aria-current]="it === page() ? 'page' : null"
                (click)="goTo(it)"
              >{{ it }}</button>
            </li>
          }
        }
      </ul>
      <button
        type="button"
        class="sisyphos-pagination-arrow"
        [disabled]="page() >= pageCount()"
        aria-label="Next page"
        (click)="goTo(page() + 1)"
      >
        <svg viewBox="0 0 16 16" width="14" height="14" aria-hidden="true">
          <path d="M6 4l4 4-4 4" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" />
        </svg>
      </button>
    </nav>
  `,
})
export class Pagination {
  private readonly _page = signal(1);
  private readonly _pageCount = signal(1);
  private readonly _siblings = signal(1);
  private readonly _boundaries = signal(1);
  private readonly _size = signal<"sm" | "md" | "lg">("md");

  readonly page = this._page.asReadonly();
  readonly pageCount = this._pageCount.asReadonly();

  @NgInput("page") set pageInput(v: number) { this._page.set(v); }
  @NgInput("pageCount") set pageCountInput(v: number) { this._pageCount.set(v); }
  @NgInput("siblings") set siblingsInput(v: number) { this._siblings.set(v); }
  @NgInput("boundaries") set boundariesInput(v: number) { this._boundaries.set(v); }
  @NgInput("size") set sizeInput(v: "sm" | "md" | "lg") { this._size.set(v); }

  @Output() readonly pageChange = new EventEmitter<number>();

  readonly items = computed(() =>
    getPageItems(this._page(), this._pageCount(), this._siblings(), this._boundaries())
  );

  readonly rootClasses = computed(() => `sisyphos-pagination ${this._size()}`);

  goTo(p: number): void {
    if (p < 1 || p > this._pageCount() || p === this._page()) return;
    this.pageChange.emit(p);
  }
}
