// packages/vue/src/select/Select.vue
<script setup lang="ts">
/**
 * Select — Vue 3 binding. Combobox-style picker with single/multi value,
 * search filter, clearable, keyboard navigation, async loading state,
 * and a portal-mounted dropdown.
 *
 * Class names, ARIA, and visual structure mirror the React + Angular
 * bindings: control (with chevron + clear), value wrapper (with tags
 * for multi-select), and a dropdown list with search row + loading +
 * empty states.
 */
import { computed, ref, useId, watch } from "vue";
import { useEscapeKey, useOutsideClick } from "../composables";
import type { SelectOption, SelectValue } from "./types";

interface Props {
  options: SelectOption[];
  modelValue?: SelectValue | SelectValue[] | null;
  placeholder?: string;
  label?: string;
  helperText?: string;
  error?: boolean;
  errorMessage?: string;
  multiple?: boolean;
  searchable?: boolean;
  searchPlaceholder?: string;
  clearable?: boolean;
  disabled?: boolean;
  fullWidth?: boolean;
  size?: "sm" | "md" | "lg";
  loading?: boolean;
  loadingText?: string;
  emptyText?: string;
}

const props = withDefaults(defineProps<Props>(), {
  placeholder: "Select…",
  searchPlaceholder: "Search…",
  multiple: false,
  searchable: false,
  clearable: false,
  disabled: false,
  fullWidth: false,
  error: false,
  size: "md",
  loading: false,
  loadingText: "Loading…",
  emptyText: "No options",
});

const emit = defineEmits<{
  (e: "update:modelValue", value: SelectValue | SelectValue[] | null): void;
}>();

const baseId = `sisyphos-select-${useId()}`;
const triggerRef = ref<HTMLDivElement | null>(null);
const dropdownRef = ref<HTMLDivElement | null>(null);
const searchRef = ref<HTMLInputElement | null>(null);
const open = ref(false);
const search = ref("");
const activeIndex = ref(-1);

useEscapeKey(() => (open.value = false), open);
useOutsideClick([triggerRef, dropdownRef], () => (open.value = false), open);

const filtered = computed(() => {
  if (!props.searchable || !search.value) return props.options;
  const q = search.value.toLowerCase();
  return props.options.filter((o) => o.label.toLowerCase().includes(q));
});

const selectedValues = computed<SelectValue[]>(() => {
  if (props.multiple) return Array.isArray(props.modelValue) ? (props.modelValue as SelectValue[]) : [];
  const v = props.modelValue;
  return v == null ? [] : [v as SelectValue];
});

const singleLabel = computed(() => {
  if (props.multiple) return "";
  const v = props.modelValue;
  if (v == null) return "";
  return props.options.find((o) => o.value === v)?.label ?? "";
});

const hasValue = computed(() =>
  props.multiple ? selectedValues.value.length > 0 : props.modelValue != null
);

const isSelected = (v: SelectValue) => selectedValues.value.some((x) => x === v);

const labelOf = (v: SelectValue) => props.options.find((o) => o.value === v)?.label ?? String(v);

function pick(opt: SelectOption) {
  if (opt.disabled) return;
  if (props.multiple) {
    const set = new Set(selectedValues.value);
    if (set.has(opt.value)) set.delete(opt.value);
    else set.add(opt.value);
    emit("update:modelValue", Array.from(set));
  } else {
    emit("update:modelValue", opt.value);
    open.value = false;
  }
}

function removeTag(v: SelectValue) {
  if (!props.multiple) return;
  emit(
    "update:modelValue",
    selectedValues.value.filter((x) => x !== v)
  );
}

function clear() {
  emit("update:modelValue", props.multiple ? [] : null);
  search.value = "";
}

function handleKeyDown(e: KeyboardEvent) {
  if (!open.value) return;
  const all = filtered.value;
  if (all.length === 0) return;
  if (e.key === "ArrowDown") {
    e.preventDefault();
    activeIndex.value = (activeIndex.value + 1) % all.length;
  } else if (e.key === "ArrowUp") {
    e.preventDefault();
    activeIndex.value = (activeIndex.value - 1 + all.length) % all.length;
  } else if (e.key === "Enter" && activeIndex.value >= 0) {
    e.preventDefault();
    pick(all[activeIndex.value]);
  }
}

watch(open, (v) => {
  if (v && props.searchable) {
    setTimeout(() => searchRef.value?.focus(), 0);
  }
  if (!v) {
    search.value = "";
    activeIndex.value = -1;
  }
});

const containerClasses = computed(() => [
  "sisyphos-select",
  props.size,
  props.error && "error",
  props.disabled && "disabled",
  props.fullWidth && "full-width",
]);

const controlClasses = computed(() => [
  "sisyphos-select-control",
  open.value && "open",
  hasValue.value && "has-value",
]);

const showClear = computed(() => props.clearable && !props.disabled && hasValue.value);
</script>

<template>
  <div :class="containerClasses">
    <label v-if="label" :class="['sisyphos-select-label', error && 'error']">{{ label }}</label>
    <div
      ref="triggerRef"
      role="combobox"
      :aria-expanded="open"
      aria-haspopup="listbox"
      :tabindex="disabled ? -1 : 0"
      :class="controlClasses"
      @click="!disabled && (open = !open)"
      @keydown="handleKeyDown"
    >
      <div class="sisyphos-select-value">
        <template v-if="multiple">
          <span v-if="selectedValues.length === 0" class="sisyphos-select-placeholder">
            {{ placeholder }}
          </span>
          <div v-else class="sisyphos-select-tags">
            <span
              v-for="v in selectedValues"
              :key="String(v)"
              class="sisyphos-select-tag"
              :title="labelOf(v)"
            >
              {{ labelOf(v) }}
              <button
                type="button"
                class="sisyphos-select-tag-delete"
                aria-label="Remove"
                @click.stop="removeTag(v)"
              >
                ✕
              </button>
            </span>
          </div>
        </template>
        <template v-else>
          <span v-if="!singleLabel" class="sisyphos-select-placeholder">{{ placeholder }}</span>
          <span v-else class="sisyphos-select-single">{{ singleLabel }}</span>
        </template>
      </div>
      <button
        v-if="showClear"
        type="button"
        class="sisyphos-select-clear"
        aria-label="Clear"
        @click.stop="clear"
      >
        ✕
      </button>
      <span class="sisyphos-select-chevron" aria-hidden="true">
        <svg viewBox="0 0 24 24" width="16" height="16">
          <path d="M7 10l5 5 5-5z" fill="currentColor" />
        </svg>
      </span>
    </div>
    <Teleport to="body">
      <ul
        v-if="open"
        ref="dropdownRef"
        :id="`${baseId}-list`"
        role="listbox"
        class="sisyphos-select-list"
        @keydown="handleKeyDown"
      >
        <li v-if="searchable" class="sisyphos-select-search-row">
          <input
            ref="searchRef"
            v-model="search"
            type="search"
            class="sisyphos-select-search"
            :placeholder="searchPlaceholder"
          />
        </li>
        <li v-if="loading" class="sisyphos-select-loading">
          <span class="sisyphos-select-loading-spinner" aria-hidden="true" />
          {{ loadingText }}
        </li>
        <li v-else-if="filtered.length === 0" class="sisyphos-select-empty">{{ emptyText }}</li>
        <template v-else>
          <li
            v-for="(opt, idx) in filtered"
            :key="String(opt.value)"
            role="option"
            :aria-selected="isSelected(opt.value)"
            :aria-disabled="opt.disabled || undefined"
            :class="[
              'sisyphos-select-option',
              opt.disabled && 'disabled',
              isSelected(opt.value) && 'selected',
              idx === activeIndex && 'active',
            ]"
            @click="pick(opt)"
            @mouseenter="activeIndex = idx"
          >
            <span v-if="multiple" class="sisyphos-select-option-check" aria-hidden="true">
              {{ isSelected(opt.value) ? "✓" : "" }}
            </span>
            <span v-if="opt.icon" class="sisyphos-select-option-icon">
              <slot name="icon" :option="opt" />
            </span>
            <span class="sisyphos-select-option-body">
              <span class="sisyphos-select-option-label">{{ opt.label }}</span>
              <span v-if="opt.description" class="sisyphos-select-option-description">
                {{ opt.description }}
              </span>
            </span>
          </li>
        </template>
      </ul>
    </Teleport>
    <span v-if="error && errorMessage" class="sisyphos-select-error" role="alert">
      {{ errorMessage }}
    </span>
    <span v-else-if="helperText" class="sisyphos-select-helper">{{ helperText }}</span>
  </div>
</template>

<style src="./Select.scss"></style>

// packages/react/src/select/Select.tsx
/**
 * Select — single- or multi-value combobox with optional search, clear,
 * creatable values, and infinite scroll.
 *
 * Dropdown is portal-mounted with auto-flip placement and full keyboard
 * navigation (Arrow Up/Down, Enter, Escape, Home/End).
 */
import type React from "react";
import { useCallback, useEffect, useId, useMemo, useRef, useState } from "react";
import { Portal } from "../internal/portal";
import { cx, computePosition, useEscapeKey, type Placement } from "@sisyphos-ui/core/internal";
import type { Scale, SelectOption, SelectValue } from "./types";
import "./Select.scss";

type SingleProps = {
  multiple?: false;
  value?: SelectValue | null;
  defaultValue?: SelectValue | null;
  onChange?: (value: SelectValue | null) => void;
};
type MultiProps = {
  multiple: true;
  value?: SelectValue[];
  defaultValue?: SelectValue[];
  onChange?: (value: SelectValue[]) => void;
};

export type SelectProps = {
  options: SelectOption[];
  placeholder?: string;
  label?: string;
  helperText?: React.ReactNode;
  error?: boolean;
  errorMessage?: React.ReactNode;
  disabled?: boolean;
  required?: boolean;
  size?: Scale;
  radius?: Scale;
  fullWidth?: boolean;

  searchable?: boolean;
  /** Called when the search input changes. Use for server-side filtering. */
  onSearch?: (term: string) => void;
  /** Custom option filter (client-side). Return true to include. */
  filterOption?: (option: SelectOption, term: string) => boolean;

  clearable?: boolean;
  /** Allow typing in arbitrary new values (multi only). */
  creatable?: boolean;

  loading?: boolean;
  /** Fired when the listbox scrolls near the bottom. */
  onLoadMore?: () => void;
  hasMore?: boolean;

  placement?: Placement;
  className?: string;
} & (SingleProps | MultiProps);

const ChevronIcon = ({ open }: { open: boolean }) => (
  <svg
    viewBox="0 0 24 24"
    width={18}
    height={18}
    aria-hidden="true"
    style={{ transform: open ? "rotate(180deg)" : undefined, transition: "transform 150ms" }}
  >
    <path d="M7 10l5 5 5-5z" fill="currentColor" />
  </svg>
);

const ClearIcon = () => (
  <svg viewBox="0 0 24 24" width={14} height={14} aria-hidden="true">
    <path
      d="M19 6.41 17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12z"
      fill="currentColor"
    />
  </svg>
);

function defaultFilter(option: SelectOption, term: string): boolean {
  if (!term) return true;
  return option.label.toLowerCase().includes(term.toLowerCase());
}

export const Select: React.FC<SelectProps> = (props) => {
  const {
    options,
    placeholder = "Select…",
    label,
    helperText,
    error = false,
    errorMessage,
    disabled = false,
    required = false,
    size = "md",
    radius = "sm",
    fullWidth = false,
    searchable = false,
    onSearch,
    filterOption = defaultFilter,
    clearable = false,
    creatable = false,
    loading = false,
    onLoadMore,
    hasMore,
    placement = "bottom-start",
    className,
    multiple,
  } = props;

  const reactId = useId();
  const listboxId = `sisyphos-select-${reactId}`;

  const isControlled = "value" in props && props.value !== undefined;
  const [internalValue, setInternalValue] = useState<
    SelectValue | null | SelectValue[] | undefined
  >(props.defaultValue);
  const rawValue = isControlled ? (props as { value: unknown }).value : internalValue;

  const selectedValues = useMemo<SelectValue[]>(() => {
    if (multiple) return Array.isArray(rawValue) ? (rawValue as SelectValue[]) : [];
    return rawValue != null && rawValue !== "" ? [rawValue as SelectValue] : [];
  }, [rawValue, multiple]);

  const [open, setOpen] = useState(false);
  const [search, setSearch] = useState("");
  const [activeIndex, setActiveIndex] = useState(-1);
  const [pos, setPos] = useState<{
    left: number;
    top: number;
    placement: Placement;
    width: number;
  } | null>(null);

  const triggerRef = useRef<HTMLDivElement | null>(null);
  const listRef = useRef<HTMLUListElement | null>(null);
  const searchRef = useRef<HTMLInputElement | null>(null);
  const containerRef = useRef<HTMLDivElement | null>(null);

  useEscapeKey(() => setOpen(false), open);

  // Outside-click close — exclude both the trigger and the portalled listbox.
  useEffect(() => {
    if (!open) return;
    const handler = (e: MouseEvent) => {
      const tgt = e.target as Node | null;
      if (!tgt) return;
      if (triggerRef.current?.contains(tgt)) return;
      if (listRef.current?.contains(tgt)) return;
      setOpen(false);
    };
    document.addEventListener("mousedown", handler);
    return () => document.removeEventListener("mousedown", handler);
  }, [open]);

  useEffect(() => {
    if (!open) {
      setSearch("");
      setActiveIndex(-1);
      return;
    }
    if (searchable && searchRef.current) {
      searchRef.current.focus();
    }
  }, [open, searchable]);

  useEffect(() => {
    if (!open) {
      setPos(null);
      return;
    }
    let raf = 0;
    const update = () => {
      const anchor = triggerRef.current;
      const list = listRef.current;
      if (!anchor || !list) return;
      const a = anchor.getBoundingClientRect();
      const size = { width: list.offsetWidth, height: list.offsetHeight };
      const p = computePosition(a, size, placement, 4);
      setPos({ ...p, width: a.width });
    };
    raf = requestAnimationFrame(() => requestAnimationFrame(update));
    const onWin = () => update();
    window.addEventListener("scroll", onWin, true);
    window.addEventListener("resize", onWin);
    return () => {
      cancelAnimationFrame(raf);
      window.removeEventListener("scroll", onWin, true);
      window.removeEventListener("resize", onWin);
    };
  }, [open, placement]);

  const filteredOptions = useMemo(() => {
    if (!searchable || !search) return options;
    // When `onSearch` is provided, filtering happens on the server.
    if (onSearch) return options;
    return options.filter((o) => filterOption(o, search));
  }, [options, searchable, search, onSearch, filterOption]);

  const emitChange = useCallback(
    (next: SelectValue[] | SelectValue | null) => {
      if (!isControlled) {
        setInternalValue(next as SelectValue[] | SelectValue | null);
      }
      if (multiple) {
        (props.onChange as ((v: SelectValue[]) => void) | undefined)?.(
          (next as SelectValue[]) ?? []
        );
      } else {
        (props.onChange as ((v: SelectValue | null) => void) | undefined)?.(
          next as SelectValue | null
        );
      }
    },
    [isControlled, multiple, props]
  );

  const selectValue = useCallback(
    (v: SelectValue) => {
      if (multiple) {
        const curr = selectedValues;
        const next = curr.includes(v) ? curr.filter((x) => x !== v) : [...curr, v];
        emitChange(next);
      } else {
        emitChange(v);
        setOpen(false);
      }
    },
    [multiple, selectedValues, emitChange]
  );

  const handleClear = useCallback(
    (e: React.MouseEvent) => {
      e.stopPropagation();
      if (disabled) return;
      emitChange(multiple ? [] : null);
    },
    [disabled, emitChange, multiple]
  );

  const handleScroll = (e: React.UIEvent<HTMLUListElement>) => {
    if (!onLoadMore || loading || hasMore === false) return;
    const el = e.currentTarget;
    if (el.scrollHeight - el.scrollTop - el.clientHeight < 24) onLoadMore();
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (!open && (e.key === "ArrowDown" || e.key === "Enter" || e.key === " ")) {
      e.preventDefault();
      setOpen(true);
      return;
    }
    if (!open) return;
    if (e.key === "ArrowDown") {
      e.preventDefault();
      setActiveIndex((i) => Math.min(filteredOptions.length - 1, i + 1));
    } else if (e.key === "ArrowUp") {
      e.preventDefault();
      setActiveIndex((i) => Math.max(0, i - 1));
    } else if (e.key === "Home") {
      e.preventDefault();
      setActiveIndex(0);
    } else if (e.key === "End") {
      e.preventDefault();
      setActiveIndex(filteredOptions.length - 1);
    } else if (e.key === "Enter") {
      const opt = filteredOptions[activeIndex];
      if (opt && !opt.disabled) {
        e.preventDefault();
        selectValue(opt.value);
      } else if (creatable && multiple && search.trim()) {
        e.preventDefault();
        const term = search.trim();
        if (!selectedValues.includes(term)) emitChange([...selectedValues, term]);
        setSearch("");
      }
    }
  };

  const displayTags = useMemo(() => {
    if (!multiple) return null;
    return selectedValues.map((v) => {
      const opt = options.find((o) => o.value === v);
      const lbl = opt?.label ?? String(v);
      return (
        <span key={String(v)} className="sisyphos-select-tag" title={lbl}>
          {lbl}
          <button
            type="button"
            className="sisyphos-select-tag-delete"
            aria-label={`Remove ${lbl}`}
            onClick={(e) => {
              e.stopPropagation();
              emitChange(selectedValues.filter((x) => x !== v));
            }}
            disabled={disabled}
          >
            ×
          </button>
        </span>
      );
    });
  }, [multiple, selectedValues, options, emitChange, disabled]);

  const singleLabel = useMemo(() => {
    if (multiple) return null;
    const v = selectedValues[0];
    if (v === undefined) return null;
    return options.find((o) => o.value === v)?.label ?? String(v);
  }, [multiple, selectedValues, options]);

  const hasValue = selectedValues.length > 0;

  return (
    <div
      ref={containerRef}
      className={cx(
        "sisyphos-select",
        size,
        `radius-${radius}`,
        disabled && "disabled",
        error && "error",
        fullWidth && "full-width",
        className
      )}
    >
      {label && (
        <label className={cx("sisyphos-select-label", error && "error", required && "required")}>
          {label}
        </label>
      )}
      <div
        ref={triggerRef}
        className={cx("sisyphos-select-control", open && "open", hasValue && "has-value")}
        role="combobox"
        aria-expanded={open}
        aria-haspopup="listbox"
        aria-controls={open ? listboxId : undefined}
        aria-disabled={disabled || undefined}
        aria-invalid={error || undefined}
        tabIndex={disabled ? -1 : 0}
        onClick={() => !disabled && setOpen((o) => !o)}
        onKeyDown={handleKeyDown}
      >
        <div className="sisyphos-select-value">
          {multiple && selectedValues.length > 0 ? (
            <div className="sisyphos-select-tags">{displayTags}</div>
          ) : singleLabel ? (
            <span className="sisyphos-select-single">{singleLabel}</span>
          ) : (
            <span className="sisyphos-select-placeholder">{placeholder}</span>
          )}
        </div>
        {clearable && hasValue && !disabled && (
          <button
            type="button"
            aria-label="Clear selection"
            className="sisyphos-select-clear"
            onClick={handleClear}
          >
            <ClearIcon />
          </button>
        )}
        <span className="sisyphos-select-chevron">
          <ChevronIcon open={open} />
        </span>
      </div>
      {open && (
        <Portal>
          <ul
            ref={listRef}
            id={listboxId}
            role="listbox"
            aria-multiselectable={multiple || undefined}
            className={cx("sisyphos-select-list", pos?.placement ?? placement)}
            style={{
              position: "fixed",
              left: pos?.left ?? 0,
              top: pos?.top ?? 0,
              minWidth: pos?.width ?? 0,
              opacity: pos ? 1 : 0,
            }}
            onScroll={handleScroll}
          >
            {(searchable || creatable) && (
              <li className="sisyphos-select-search-row">
                <input
                  ref={searchRef}
                  className="sisyphos-select-search"
                  type="text"
                  placeholder={creatable ? "Type to add…" : "Search…"}
                  value={search}
                  onChange={(e) => {
                    setSearch(e.target.value);
                    onSearch?.(e.target.value);
                    setActiveIndex(0);
                  }}
                  onKeyDown={handleKeyDown}
                />
              </li>
            )}
            {filteredOptions.length === 0 && !loading && (
              <li className="sisyphos-select-empty">No options</li>
            )}
            {filteredOptions.map((opt, i) => {
              const checked = selectedValues.includes(opt.value);
              return (
                <li
                  key={String(opt.value)}
                  role="option"
                  aria-selected={checked}
                  aria-disabled={opt.disabled || undefined}
                  className={cx(
                    "sisyphos-select-option",
                    checked && "selected",
                    opt.disabled && "disabled",
                    i === activeIndex && "active"
                  )}
                  onMouseEnter={() => setActiveIndex(i)}
                  onClick={() => !opt.disabled && selectValue(opt.value)}
                >
                  {opt.icon && <span className="sisyphos-select-option-icon">{opt.icon}</span>}
                  <span className="sisyphos-select-option-body">
                    <span className="sisyphos-select-option-label">{opt.label}</span>
                    {opt.description && (
                      <span className="sisyphos-select-option-description">{opt.description}</span>
                    )}
                  </span>
                  {checked && (
                    <span className="sisyphos-select-option-check" aria-hidden="true">
                      ✓
                    </span>
                  )}
                </li>
              );
            })}
            {loading && (
              <li className="sisyphos-select-loading">
                <span className="sisyphos-select-loading-spinner" aria-hidden="true" />
                <span>Loading…</span>
              </li>
            )}
          </ul>
        </Portal>
      )}
      {error && errorMessage ? (
        <span className="sisyphos-select-error" role="alert">
          {errorMessage}
        </span>
      ) : helperText ? (
        <span className="sisyphos-select-helper">{helperText}</span>
      ) : null}
    </div>
  );
};
